import { useCallback, useEffect, useState } from "react";
import { portalFetch, checkoutCashfreeOrder } from "../../utils/portal";
const inr=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v));
export default function PartnerWallet({admin=false}) {
  const [data,setData]=useState(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[amount,setAmount]=useState(""),[filter,setFilter]=useState("");
  const load=useCallback(async()=>{try{setData(await portalFetch(admin?"/api/admin/wallet":"/api/b2b/wallet",{},admin?"admin":"agent"));setError("")}catch(e){setError(e.message)}},[admin]);
  const verify=useCallback(async orderId=>{setBusy(true);try{const r=await portalFetch("/api/b2b/wallet",{method:"POST",body:JSON.stringify({action:"verify",orderId})},"agent");setMessage(r.status==="paid"?"Payment verified and credit added.":"Payment is not yet confirmed. You can check it again.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}},[load]);
  useEffect(()=>{load();const orderId=new URLSearchParams(window.location.search).get("wallet_order_id");if(orderId&&!admin)verify(orderId)},[admin,load,verify]);
  const add=async e=>{e.preventDefault();setBusy(true);setError("");try{const order=await portalFetch("/api/b2b/wallet",{method:"POST",body:JSON.stringify({action:"create",amount})},"agent");await checkoutCashfreeOrder(order);await verify(order.order_id);setAmount("")}catch(e){setError(e.message)}finally{setBusy(false);load()}};
  return <section className="mt-5 rounded-2xl border bg-white p-5"><h3 className="font-display text-2xl">{admin?"Partner wallet transactions":"My Wallet / Credit"}</h3>{error&&<p role="alert" className="mt-3 text-rose-700">{error}</p>}{message&&<p role="status" className="mt-3 text-emerald-700">{message}</p>}<button type="button" className="btn-secondary mt-3" onClick={load} disabled={busy}>Refresh</button>{!data&&!error&&<p>Loading wallet…</p>}{data&&<>{!admin&&<><p className="mt-4">Available wallet balance <strong className="block text-3xl">{inr(data.balance)}</strong></p><form onSubmit={add} className="mt-4 flex flex-wrap items-end gap-3"><label><span className="label-field">Amount (INR)</span><input required type="number" min="1" max="100000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="input-field"/></label><button disabled={busy} className="btn-primary">{busy?"Processing…":"Add Funds"}</button></form></>}<h4 className="mt-6 font-bold">Transaction History</h4>{admin&&<input aria-label="Filter wallet by Agent ID or order" placeholder="Agent ID, agency or order" className="input-field mt-3" value={filter} onChange={e=>setFilter(e.target.value)}/>}<div className="mt-3 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead><tr><th className="p-3">Order / date</th>{admin&&<th className="p-3">Agent</th>}<th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{data.transactions.filter(t=>`${t.agent_id} ${t.agent?.business_name} ${t.order_id}`.toLowerCase().includes(filter.toLowerCase())).map(t=><tr key={t.order_id} className="border-t"><td className="p-3 break-all">{t.order_id}<span className="block text-xs">{new Date(t.created_at).toLocaleString("en-IN")}</span></td>{admin&&<td className="p-3">{t.agent?.business_name}<span className="block text-xs">{t.agent_id}</span></td>}<td className="p-3">{inr(t.amount)}</td><td className="p-3">{t.status==="paid"?"Credited":"Awaiting payment verification"}</td><td className="p-3">{!admin&&t.status!=="paid"&&<button className="btn-secondary" disabled={busy} onClick={()=>verify(t.order_id)}>Check payment</button>}</td></tr>)}</tbody></table>{!data.transactions.length&&<p className="p-4 text-slate-500">No wallet transactions yet.</p>}<p className="mt-2 text-xs text-slate-500">Latest {admin?500:100} orders. Balance includes all verified credits.</p></div></>}</section>
}
