import { useCallback, useEffect, useState } from "react";
import { portalFetch } from "../../utils/portal";
const blank={code:"",title:"",discount_type:"percentage",value:"",audience:"b2b",starts_at:"",ends_at:"",package_id:"",active:false};
export default function PartnerDeals({admin=false}){
 const [deals,setDeals]=useState([]),[form,setForm]=useState(blank),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(()=>portalFetch(admin?"/api/admin/deals":"/api/b2b/deals",{},admin?"admin":"agent").then(r=>setDeals(r.deals)).catch(e=>setError(e.message)),[admin]);
 useEffect(()=>{load()},[load]);
 const save=async e=>{e.preventDefault();setBusy(true);setError("");try{await portalFetch("/api/admin/deals",{method:"POST",body:JSON.stringify(form)},"admin");setForm(blank);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <section className="mt-8 rounded-2xl border bg-white p-5"><h2 className="font-display text-2xl">Deals & Promotions / Coupon Code</h2>{error&&<p role="alert" className="text-rose-700">{error}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2">{deals.map(d=><article key={d.id} className="rounded-xl border p-4"><strong>{d.title||d.code}</strong><p className="font-mono">{d.code}</p><p>{d.discount_type==="percentage"?`${d.value}%`:`INR ${Number(d.value).toLocaleString("en-IN")}`} benefit</p><p className="text-sm">{d.starts_at?new Date(d.starts_at).toLocaleDateString("en-IN"):"Open start"} – {d.ends_at?new Date(d.ends_at).toLocaleDateString("en-IN"):"No end date"}</p>{d.package_id&&<p className="break-all text-xs">Package: {d.package_id}</p>}{d.usage_limit!==null&&<p className="text-xs">Limited-use offer: contact support to apply.</p>}{admin&&<button className="btn-secondary mt-2" onClick={()=>setForm({...d,starts_at:d.starts_at||"",ends_at:d.ends_at||"",package_id:d.package_id||""})}>Edit · {d.active?"Active":"Inactive"}</button>}</article>)}</div>{!deals.length&&!error&&<p className="mt-3 text-slate-500">No configured promotions available.</p>}{admin&&<form onSubmit={save} className="mt-5 grid gap-3 sm:grid-cols-2">{[["code","Coupon code"],["title","Title"],["value","Benefit value"],["starts_at","Starts at (ISO date/time, optional)"],["ends_at","Ends at (ISO date/time, optional)"],["package_id","Package UUID (optional)"]].map(([key,label])=><label key={key}><span className="label-field">{label}</span><input required={["code","title","value"].includes(key)} value={form[key]} onChange={e=>setForm({...form,[key]:key==="code"?e.target.value.toUpperCase():e.target.value})} className="input-field"/></label>)}<label><span className="label-field">Discount type</span><select value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})} className="input-field"><option value="percentage">Percentage</option><option value="fixed">Fixed INR</option></select></label><label><span className="label-field">Audience</span><select className="input-field" value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="b2b">B2B</option><option value="customer">Customer</option><option value="all">All</option></select></label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><div className="flex gap-2"><button disabled={busy} className="btn-primary">Save promotion</button><button type="button" className="btn-secondary" onClick={()=>setForm(blank)}>New</button></div></form>}</section>
}
