import assert from "node:assert/strict";
import test from "node:test";
import bookingHandler from "../server/documents/booking.js";
import {generateAndStoreBookingDocuments} from "../server/_document-service.js";
import {generateBookingDocument} from "../server/documents/_booking-docs.js";
import {buildDocumentModel} from "../server/documents/_document-data.js";
import {deliverNotification} from "../server/_notifications.js";

const response=()=>({statusCode:200,headers:{},body:null,status(code){this.statusCode=code;return this},setHeader(key,value){this.headers[key]=value;return this},end(value){this.body=JSON.parse(value);return this},send(value){this.body=value;return this}});

test("booking document route handles a PostgREST error object without iterable destructuring",async()=>{
 const previous={url:process.env.SUPABASE_URL,anon:process.env.SUPABASE_ANON_KEY,key:process.env.SUPABASE_SERVICE_ROLE_KEY,fetch:global.fetch,error:console.error};
 process.env.SUPABASE_URL="https://example.supabase.co";process.env.SUPABASE_ANON_KEY="anon";process.env.SUPABASE_SERVICE_ROLE_KEY="service";
 let bookingUrl="";global.fetch=async(url)=>{if(String(url).includes("/auth/v1/user"))return new Response(JSON.stringify({id:"user-1"}),{status:200});bookingUrl=String(url);return new Response(JSON.stringify({code:"PGRST200",message:"relationship unavailable"}),{status:400})};console.error=()=>{};
 try{const res=response();await bookingHandler({method:"GET",headers:{authorization:"Bearer token"},query:{reference:"NTB-20260830-ABC123",type:"invoice"}},res);assert.equal(res.statusCode,502);assert.deepEqual(res.body,{error:"Booking document data could not be loaded"});assert.match(bookingUrl,/package%3Apackages|package:packages/);assert.match(decodeURIComponent(bookingUrl),/itinerary:package_itinerary_days/)}finally{global.fetch=previous.fetch;console.error=previous.error;if(previous.url===undefined)delete process.env.SUPABASE_URL;else process.env.SUPABASE_URL=previous.url;if(previous.anon===undefined)delete process.env.SUPABASE_ANON_KEY;else process.env.SUPABASE_ANON_KEY=previous.anon;if(previous.key===undefined)delete process.env.SUPABASE_SERVICE_ROLE_KEY;else process.env.SUPABASE_SERVICE_ROLE_KEY=previous.key}
});

test("automatic document storage reports the same PostgREST object safely",async()=>{
 const previous={url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY,fetch:global.fetch,error:console.error};process.env.SUPABASE_URL="https://example.supabase.co";process.env.SUPABASE_SERVICE_ROLE_KEY="service";global.fetch=async()=>new Response(JSON.stringify({code:"PGRST200",message:"relationship unavailable"}),{status:400});console.error=()=>{};
 try{await assert.rejects(()=>generateAndStoreBookingDocuments("booking-1"),/Booking document data could not be loaded/)}finally{global.fetch=previous.fetch;console.error=previous.error;if(previous.url===undefined)delete process.env.SUPABASE_URL;else process.env.SUPABASE_URL=previous.url;if(previous.key===undefined)delete process.env.SUPABASE_SERVICE_ROLE_KEY;else process.env.SUPABASE_SERVICE_ROLE_KEY=previous.key}
});

const sampleBooking={id:"11111111-1111-4111-8111-111111111111",reference:"NTB-20260831-DOC123",operational_status:"confirmed",billing:{name:"Asha Patil",email:"asha@example.com",phone:"919999999999"},document_details:{hotel_voucher:{hotelName:"Sea View Residency",hotelAddress:"Mumbai",roomType:"Deluxe",cancellationPolicy:"Free cancellation until 48 hours before check-in."},transport_voucher:{route:"Mumbai to Pune",vehicleType:"Sedan",pickup:"Mumbai",drop:"Pune",inclusions:"Fuel\nDriver allowance"}},package:{title:"Maharashtra Explorer",days:3,nights:2,itinerary:[{day_number:1,title:"Arrival",description:"Pickup and hotel transfer"}]},travel_date:"2026-12-01",end_date:"2026-12-03",room_count:1,traveller_count:1,travellers:[{full_name:"Asha Patil"}],subtotal:10000,tax:0,total:10000,amount_paid:5000,balance_due:5000};

test("hotel and transport generators produce real PDF and editable DOCX files",async()=>{
 for(const type of ["hotel_voucher","transport_voucher"]){const pdf=await generateBookingDocument(sampleBooking,type,"pdf",{settings:{brandName:"NaysTrip",email:"hello@naystrip.com",phone:"+91 8097132424"}});assert.equal(pdf.bytes.subarray(0,4).toString(),"%PDF");assert.match(pdf.model.filenameBase,/^NAYSTRIP-(Hotel|Transport)-Voucher-/);const docx=await generateBookingDocument(sampleBooking,type,"docx",{settings:{brandName:"NaysTrip",email:"hello@naystrip.com",phone:"+91 8097132424"}});assert.equal(docx.bytes.subarray(0,2).toString(),"PK");assert.ok(docx.bytes.length>5000);assert.match(docx.contentType,/wordprocessingml/)}
});

test("hotel model hides policies that were not configured",()=>{const model=buildDocumentModel(sampleBooking,"hotel_voucher");const headings=model.sections.map(item=>item.heading);assert.ok(headings.includes("Cancellation Policy"));assert.ok(!headings.includes("No-show"));assert.ok(!headings.includes("Refund Information"))});

test("Resend rejection remains a failed notification and is never reported as sent",async()=>{const previous={url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY,resend:process.env.RESEND_API_KEY,from:process.env.RESEND_FROM,fetch:global.fetch};process.env.SUPABASE_URL="https://example.supabase.co";process.env.SUPABASE_SERVICE_ROLE_KEY="service";process.env.RESEND_API_KEY="re_test";process.env.RESEND_FROM="NaysTrip <documents@example.com>";global.fetch=async(url,options={})=>{if(String(url).includes("/rest/v1/notifications")&&options.method==="POST")return new Response(JSON.stringify([{id:"22222222-2222-4222-8222-222222222222"}]),{status:201});if(String(url).includes("/rest/v1/notifications"))return new Response("[]",{status:200});if(String(url).includes("api.resend.com"))return new Response(JSON.stringify({message:"Rejected sender"}),{status:422});throw new Error(`Unexpected ${url}`)};try{const result=await deliverNotification({event:"document_ready",recipient:"asha@example.com",payload:{documentType:"invoice",invoiceNumber:"INV-1",reference:"NTB-1",documentUrl:"https://signed.example/doc"},idempotencyKey:"failure-test"});assert.equal(result.status,"failed");assert.match(result.error,/Rejected sender/)}finally{global.fetch=previous.fetch;for(const [key,value] of [["SUPABASE_URL",previous.url],["SUPABASE_SERVICE_ROLE_KEY",previous.key],["RESEND_API_KEY",previous.resend],["RESEND_FROM",previous.from]]){if(value===undefined)delete process.env[key];else process.env[key]=value}}});
