import assert from "node:assert/strict";
import test from "node:test";
import newsletter from "../server/newsletter.js";
import {buildDocumentModel,humanTime} from "../server/documents/_document-data.js";
import {quotationDocumentModel} from "../server/documents/quotation.js";

const response=()=>({statusCode:200,status(code){this.statusCode=code;return this},setHeader(){return this},end(body){this.body=JSON.parse(body)}});

test("newsletter safely accepts a duplicate email without updating schema-dependent fields",async t=>{const previous={fetch:global.fetch,url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY};process.env.SUPABASE_URL="https://db.example";process.env.SUPABASE_SERVICE_ROLE_KEY="service";let request;global.fetch=async(url,options)=>{request={url:String(url),options};return Response.json([],{status:200})};t.after(()=>{global.fetch=previous.fetch;for(const [key,value] of [["SUPABASE_URL",previous.url],["SUPABASE_SERVICE_ROLE_KEY",previous.key]]){if(value===undefined)delete process.env[key];else process.env[key]=value}});const res=response();await newsletter({method:"POST",headers:{origin:"http://localhost"},body:{email:" Demo@Example.com "}},res);assert.equal(res.statusCode,200);assert.equal(res.body.message,"Already subscribed.");assert.match(request.url,/on_conflict=email/);assert.match(request.options.headers.Prefer,/ignore-duplicates/);assert.deepEqual(JSON.parse(request.options.body),{email:"demo@example.com",source:"homepage",status:"subscribed"})});

test("voucher times use human-readable AM/PM without changing stored values",()=>{assert.equal(humanTime("00:15"),"12:15 AM");assert.equal(humanTime("14:05"),"2:05 PM");const booking={reference:"NTB-1",billing:{name:"Guest"},document_details:{hotel_voucher:{checkInTime:"14:00",checkOutTime:"11:00"}},package:{},travel_date:"2026-10-01",end_date:"2026-10-02"};const rows=buildDocumentModel(booking,"hotel_voucher").sections.find(section=>section.heading==="Booking Details").rows;assert.equal(rows.find(row=>row.label==="Check-in time").value,"2:00 PM");assert.equal(booking.document_details.hotel_voucher.checkInTime,"14:00")});

test("B2B and admin quotations share a non-overlapping structured document model",()=>{const model=quotationDocumentModel({reference:"NTQ-1",title:"Goa",customer_name:"Asha",customer_email:"asha@example.com",customer_phone:"9876543210",subtotal:10000,total:10000,status:"draft",quotation_lines:[{description:"Hotel",quantity:1,unit_price:10000,sort_order:0}]});assert.equal(model.metaLayout,"compact");assert.equal(model.sections.find(section=>section.heading==="Customer").layout,"grid");assert.deepEqual(model.sections.find(section=>section.heading==="Services").table.headers,["Description","Qty","Unit price","Amount"])});
