import {hasFinancialPermission,requireAdmin} from "../_admin.js";
import {json,supabaseRequest} from "../_shared.js";
import {clean,money,uuidPattern} from "../_validation.js";
import {deliverNotification} from "../_notifications.js";
const allowedStatuses=["draft","pending_payment","payment_verification","confirmed","partially_paid","fully_paid","on_hold","completed","cancelled","refund_pending","refunded"];
async function bookingById(id){const response=await supabaseRequest(`bookings?id=eq.${id}&select=*,package:packages(title,slug,destination_names),customer:customers(*),travellers:booking_travellers(*),addons:booking_addons(*),payments:payments(*),documents:booking_documents(*),activity:booking_activity(*),cancellations:cancellation_requests(*)&limit=1`);return (await response.json())[0]}
const payload=(booking)=>({reference:booking.reference,customerName:booking.billing?.name,packageTitle:booking.package?.title,travelDate:booking.travel_date,amountPaid:booking.amount_paid,balanceDue:booking.balance_due,portalUrl:`${(process.env.PUBLIC_SITE_URL||"https://www.naystrip.com").replace(/\/$/,"")}/account/dashboard`});
const documentDetails=(value={})=>Object.fromEntries(["hotel_voucher","transport_voucher"].map(type=>[type,Object.fromEntries(Object.entries(value[type]||{}).slice(0,80).map(([key,item])=>[clean(key,60),Array.isArray(item)?item.slice(0,100).map(entry=>typeof entry==="object"?entry:clean(entry,1000)):clean(item,5000)]))]));
export default async function handler(req,res){const admin=await requireAdmin(req,res);if(!admin)return;try{
 if(req.method==="GET"){if(req.query?.id){if(!uuidPattern.test(req.query.id))return json(res,422,{error:"Invalid booking"});return json(res,200,{booking:await bookingById(req.query.id)})}const filters=["select=id,reference,travel_date,traveller_count,total,amount_paid,balance_due,currency,payment_state,operational_status,status,created_at,assigned_staff,billing,package:packages(title,slug,destination_names)","order=created_at.desc","limit=500"];if(req.query?.status)filters.push(`operational_status=eq.${encodeURIComponent(req.query.status)}`);if(req.query?.payment)filters.push(`payment_state=eq.${encodeURIComponent(req.query.payment)}`);const response=await supabaseRequest(`bookings?${filters.join("&")}`);return response.ok?json(res,200,{bookings:await response.json()}):json(res,502,{error:"Bookings could not be loaded"})}
 if(req.method!=="PATCH")return json(res,405,{error:"Method not allowed"});const {id,action}=req.body||{};if(!uuidPattern.test(id))return json(res,422,{error:"Invalid booking"});const booking=await bookingById(id);if(!booking)return json(res,404,{error:"Booking not found"});
 if(action==="status"){const status=clean(req.body.status,40);if(!allowedStatuses.includes(status))return json(res,422,{error:"Invalid status"});const publicStatus=status==="cancelled"?"cancelled":status==="completed"?"completed":["confirmed","partially_paid","fully_paid"].includes(status)?"confirmed":booking.status;await supabaseRequest(`bookings?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({operational_status:status,status:publicStatus,updated_at:new Date().toISOString()})});await supabaseRequest("booking_activity",{method:"POST",body:JSON.stringify({booking_id:id,action:"status_updated",actor_id:admin.user_id,actor_type:"admin",details:{from:booking.operational_status,to:status}})});let notification=null;if(status==="confirmed"&&booking.operational_status!=="confirmed")notification=await deliverNotification({bookingId:id,event:"booking_confirmed",recipient:booking.billing?.email,payload:payload(booking),idempotencyKey:`${booking.reference}:booking_confirmed`});return json(res,200,{updated:true,notification})}
 if(action==="note"){const note=clean(req.body.note,4000);await supabaseRequest(`bookings?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({admin_notes:note,updated_at:new Date().toISOString()})});await supabaseRequest("booking_activity",{method:"POST",body:JSON.stringify({booking_id:id,action:"admin_note",actor_id:admin.user_id,actor_type:"admin",details:{note}})});return json(res,200,{updated:true})}
 if(action==="save_document_details"){const details=documentDetails(req.body.documentDetails);const response=await supabaseRequest(`bookings?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({document_details:details,updated_at:new Date().toISOString()})});if(!response.ok){console.error("booking_document_details_save_failed",{bookingId:id,status:response.status,error:await response.text()});return json(res,502,{error:"Document details could not be saved"})}await supabaseRequest("booking_activity",{method:"POST",body:JSON.stringify({booking_id:id,action:"document_details_updated",actor_id:admin.user_id,actor_type:"admin",details:{types:Object.keys(details)}})});return json(res,200,{updated:true})}
 if(action==="manual_payment"){if(!hasFinancialPermission(admin))return json(res,403,{error:"Accounts or Super Admin permission is required"});const amount=money(req.body.amount);if(amount<=0||amount>Number(booking.balance_due))return json(res,422,{error:"Amount must be within the outstanding balance"});const payment=await supabaseRequest("payments",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({booking_id:id,gateway:"manual",amount,currency:booking.currency,status:"successful",payment_method:clean(req.body.method,40)||"bank_transfer",captured_at:new Date().toISOString(),payment_purpose:"balance",idempotency_key:`manual:${id}:${crypto.randomUUID()}`,metadata:{reference:clean(req.body.reference,120),recorded_by:admin.user_id}})});if(!payment.ok)return json(res,502,{error:"Manual payment could not be recorded"});const paid=money(Number(booking.amount_paid)+amount);const balance=money(Math.max(0,Number(booking.total)-paid));await supabaseRequest(`bookings?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({amount_paid:paid,balance_due:balance,payment_state:balance===0?"fully_paid":"partially_paid",operational_status:balance===0?"fully_paid":"confirmed",status:"confirmed",updated_at:new Date().toISOString()})});await supabaseRequest("booking_activity",{method:"POST",body:JSON.stringify({booking_id:id,action:"manual_payment_recorded",actor_id:admin.user_id,actor_type:"admin",details:{amount,method:req.body.method,reference:req.body.reference}})});if(!["confirmed","partially_paid","fully_paid"].includes(booking.operational_status))await deliverNotification({bookingId:id,event:"booking_confirmed",recipient:booking.billing?.email,payload:{...payload(booking),amountPaid:paid,balanceDue:balance},idempotencyKey:`${booking.reference}:booking_confirmed`});return json(res,200,{payment:(await payment.json())[0]})}
 if(action==="cancellation_review"){if(!hasFinancialPermission(admin))return json(res,403,{error:"Accounts or Super Admin permission is required"});const requestId=clean(req.body.requestId,40);const decision=["approved","rejected","refund_pending","refunded"].includes(req.body.decision)?req.body.decision:null;if(!uuidPattern.test(requestId)||!decision)return json(res,422,{error:"Invalid cancellation decision"});await supabaseRequest(`cancellation_requests?id=eq.${requestId}&booking_id=eq.${id}`,{method:"PATCH",body:JSON.stringify({status:decision,calculated_fee:money(req.body.fee),approved_refund:money(req.body.refund),admin_notes:clean(req.body.notes,3000),reviewed_by:admin.user_id,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(["approved","refund_pending","refunded"].includes(decision))await supabaseRequest(`bookings?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({operational_status:decision==="refunded"?"refunded":decision==="refund_pending"?"refund_pending":"cancelled",status:"cancelled",updated_at:new Date().toISOString()})});return json(res,200,{updated:true})}
 if(action==="send_document")return json(res,409,{error:"Use the secure document delivery action so the exact stored document and recipient are verified"});
 if(action==="resend"){const event=["booking_confirmed","payment_received","trip_reminder"].includes(req.body.event)?req.body.event:"booking_confirmed";const result=await deliverNotification({bookingId:id,event,recipient:booking.billing?.email,payload:payload(booking),idempotencyKey:`${booking.reference}:${event}:manual:${crypto.randomUUID()}`});if(result.status!=="sent")return json(res,result.status==="skipped_not_configured"?503:502,{error:result.error||"Email delivery was not accepted by Resend"});return json(res,200,{notification:result})}
 return json(res,422,{error:"Unknown booking action"});
}catch(error){console.error("admin_bookings_failed",error);return json(res,500,{error:"Booking operation failed"})}}
