import { requireAdmin } from "../_admin.js";
import { bookingForDocuments, generateAndStoreDocument } from "../_document-service.js";
import { json, supabaseRequest } from "../_shared.js";
import { clean, uuidPattern } from "../_validation.js";

const invoiceNumber=()=>`INV-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;
const numeric=(value)=>Math.max(0,Number(value)||0);
function sanitizeData(value={}){
  const billing=value.billing||{},charges=value.charges||{};
  return {bookingReference:clean(value.bookingReference,60),invoiceDate:clean(value.invoiceDate,20),billing:{name:clean(billing.name,160),companyName:clean(billing.companyName,160),address:clean(billing.address,500),city:clean(billing.city,80),state:clean(billing.state,80),postalCode:clean(billing.postalCode||billing.postal_code,20),email:clean(billing.email,160),phone:clean(billing.phone,30),gstNumber:clean(billing.gstNumber,30)},lineItems:(Array.isArray(value.lineItems)?value.lineItems:[]).slice(0,100).map(item=>({description:clean(item.description,500),travellerDetails:clean(item.travellerDetails||item.details,500),quantity:numeric(item.quantity||1),rate:numeric(item.rate),amount:numeric(item.amount??numeric(item.quantity||1)*numeric(item.rate))})).filter(item=>item.description),charges:{convenienceFee:numeric(charges.convenienceFee),serviceFee:numeric(charges.serviceFee),managementFee:numeric(charges.managementFee),discount:numeric(charges.discount),tax:numeric(charges.tax),tds:numeric(charges.tds),adjustments:Number(charges.adjustments)||0},paid:numeric(value.paid),netAmount:value.netAmount===""||value.netAmount==null?null:numeric(value.netAmount),amountInWords:clean(value.amountInWords,300),notes:clean(value.notes,2000)};
}
function fromBooking(booking){return {bookingReference:booking.reference,invoiceDate:new Date().toISOString().slice(0,10),billing:{...(booking.billing||{}),companyName:booking.gst_details?.company_name||"",gstNumber:booking.gst_details?.gst_number||""},lineItems:[{description:booking.package?.title||"Travel services",travellerDetails:(booking.travellers||[]).map(item=>item.full_name).filter(Boolean).join(", "),quantity:1,rate:Number(booking.subtotal||booking.total||0),amount:Number(booking.subtotal||booking.total||0)}],charges:{discount:Number(booking.discount||0),tax:Number(booking.tax||0)},paid:Number(booking.amount_paid||0),netAmount:Number(booking.total||0),notes:""};}

export default async function handler(req,res){const admin=await requireAdmin(req,res);if(!admin)return;try{
  if(req.method==="GET"){
    if(req.query?.id){if(!uuidPattern.test(req.query.id))return json(res,422,{error:"Invalid invoice"});const response=await supabaseRequest(`invoices?id=eq.${req.query.id}&select=*,booking:bookings(id,reference,billing)&limit=1`);const body=await response.json();if(!response.ok||!Array.isArray(body)){console.error("admin_invoice_lookup_failed",{status:response.status,error:body});return json(res,502,{error:"Invoice could not be loaded"})}return body[0]?json(res,200,{invoice:body[0]}):json(res,404,{error:"Invoice not found"});}
    const response=await supabaseRequest("invoices?select=*,booking:bookings(id,reference,billing)&order=updated_at.desc&limit=500");const body=await response.json();if(!response.ok||!Array.isArray(body)){console.error("admin_invoice_list_failed",{status:response.status,error:body});return json(res,502,{error:"Invoices could not be loaded"})}return json(res,200,{invoices:body});
  }
  if(req.method==="POST"){
    const bookingId=clean(req.body?.bookingId,40);let booking=null;if(bookingId){if(!uuidPattern.test(bookingId))return json(res,422,{error:"Choose a valid booking"});booking=await bookingForDocuments({id:bookingId});}
    const number=clean(req.body?.invoiceNumber,60).replace(/[^A-Za-z0-9-]/g,"")||invoiceNumber();const data=sanitizeData({...fromBooking(booking||{}),...(req.body?.invoiceData||{})});if(!booking&&!data.billing.name&&!data.billing.companyName)return json(res,422,{error:"Enter a customer or company name for a manual invoice"});
    const response=await supabaseRequest("invoices",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({booking_id:booking?.id||null,invoice_number:number,invoice_date:data.invoiceDate||new Date().toISOString().slice(0,10),status:"draft",invoice_data:data,created_by:admin.user_id})});const body=await response.json();if(!response.ok||!Array.isArray(body)){console.error("admin_invoice_create_failed",{status:response.status,error:body});return json(res,response.status===409?409:502,{error:response.status===409?"Invoice number already exists":"Invoice draft could not be created"})}return json(res,201,{invoice:body[0]});
  }
  if(req.method==="PATCH"){
    const id=clean(req.body?.id,40);if(!uuidPattern.test(id))return json(res,422,{error:"Invalid invoice"});const data=sanitizeData(req.body?.invoiceData||{});if(!data.lineItems.length)return json(res,422,{error:"Add at least one invoice line item"});if(!data.billing.name&&!data.billing.companyName)return json(res,422,{error:"Customer or company name is required"});const finalize=req.body?.action==="finalize";const currentResponse=await supabaseRequest(`invoices?id=eq.${id}&select=*&limit=1`),currentBody=await currentResponse.json();if(!currentResponse.ok||!Array.isArray(currentBody)){console.error("admin_invoice_preflight_failed",{status:currentResponse.status,error:currentBody});return json(res,502,{error:"Invoice could not be loaded for saving"})}const current=currentBody[0];if(!current)return json(res,404,{error:"Invoice not found"});if(finalize){const booking=current.booking_id?await bookingForDocuments({id:current.booking_id}):null;const proposed={...current,invoice_date:data.invoiceDate||new Date().toISOString().slice(0,10),invoice_data:data,status:"finalized"};for(const format of ["pdf","docx"])await generateAndStoreDocument({booking,invoice:proposed,type:"invoice",format,actorId:admin.user_id})}const update={invoice_date:data.invoiceDate||new Date().toISOString().slice(0,10),invoice_data:data,status:finalize?"finalized":"draft",finalized_at:finalize?new Date().toISOString():null,updated_at:new Date().toISOString()};const response=await supabaseRequest(`invoices?id=eq.${id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(update)});const body=await response.json();if(!response.ok||!Array.isArray(body)){console.error("admin_invoice_update_failed",{status:response.status,error:body});return json(res,502,{error:"Invoice could not be saved"})}return body[0]?json(res,200,{invoice:body[0]}):json(res,404,{error:"Invoice not found"});
  }
  return json(res,405,{error:"Method not allowed"});
}catch(error){console.error("admin_invoices_failed",{error});return json(res,error.statusCode||500,{error:error.statusCode===404?error.message:"Invoice operation failed"})}}
