import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { PDFDocument, StandardFonts, rgb, degrees } from "pdf-lib";

const C={navy:rgb(35/255,59/255,79/255),orange:rgb(244/255,92/255,15/255),forest:rgb(23/255,60/255,52/255),grey:rgb(.35,.39,.43),pale:rgb(1,.98,.95),line:rgb(.84,.87,.89),white:rgb(1,1,1)};
const wrap=(font,value,size,width)=>{const lines=[];let line="";const printable=Array.from(String(value??"")).map((char)=>{const code=char.charCodeAt(0);return code===9||code===10||code===13||(code>=32&&code<=255)?char:"-"}).join("");for(const word of printable.split(/\s+/).filter(Boolean)){const candidate=line?`${line} ${word}`:word;if(line&&font.widthOfTextAtSize(candidate,size)>width){lines.push(line);line=word}else line=candidate}if(line)lines.push(line);return lines.length?lines:[""]};

export async function createDocumentPdf(model,settings){
 const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let logo=null;try{logo=await pdf.embedPng(await readFile(join(process.cwd(),"public","branding","naystrip-logo.png")))}catch{}let page,y;
 const addPage=()=>{page=pdf.addPage([595.28,841.89]);page.drawRectangle({x:0,y:0,width:595.28,height:841.89,color:C.pale});page.drawRectangle({x:0,y:823,width:595.28,height:19,color:C.orange});if(logo){const scaled=logo.scaleToFit(116,65);page.drawImage(logo,{x:40,y:742,width:scaled.width,height:scaled.height});const watermark=logo.scaleToFit(250,150);page.drawImage(logo,{x:(595.28-watermark.width)/2,y:340,width:watermark.width,height:watermark.height,opacity:.04})}page.drawText(String(settings.brandName||"NaysTrip & Treks"),{x:365,y:790,size:10,font:bold,color:C.forest});page.drawText(settings.tagline||"Leisure to Adventure",{x:365,y:775,size:8,font:regular,color:C.grey});page.drawText(`${settings.phone||""} | ${settings.email||""}`,{x:365,y:760,size:7,font:regular,color:C.grey});y=720};
 const ensure=(height=80)=>{if(!page||y-height<55)addPage()};
 const drawLines=(value,{x=42,width=510,size=9,font=regular,color=C.navy,leading=12}={})=>{const lines=wrap(font,value,size,width);ensure(lines.length*leading+8);for(const line of lines){page.drawText(line,{x,y,size,font,color});y-=leading}return lines.length*leading};
 const sectionHeading=(value)=>{ensure(38);y-=8;page.drawRectangle({x:40,y:y-18,width:515,height:24,color:C.forest});page.drawText(value.toUpperCase(),{x:50,y:y-11,size:9,font:bold,color:C.white});y-=31};
 const keyRows=(items)=>{for(const item of items||[]){const valueLines=wrap(regular,item.value,8.5,350),height=Math.max(26,valueLines.length*11+10);ensure(height+5);page.drawRectangle({x:40,y:y-height,width:515,height,color:C.white,borderColor:C.line,borderWidth:.5});page.drawRectangle({x:40,y:y-height,width:145,height,color:C.pale});page.drawText(String(item.label).toUpperCase(),{x:48,y:y-16,size:7,font:bold,color:C.orange});let ly=y-15;for(const line of valueLines){page.drawText(line,{x:195,y:ly,size:8.5,font:regular,color:C.navy});ly-=11}y-=height}y-=5};
 const compactMeta=(items)=>{ensure(58);const width=515/Math.max(1,items.length),height=52;for(const [index,item] of items.entries()){const x=40+index*width;page.drawRectangle({x,y:y-height,width,height,color:C.white,borderColor:C.line,borderWidth:.75});page.drawText(String(item.label).toUpperCase(),{x:x+8,y:y-14,size:6.5,font:bold,color:C.orange});for(const [lineIndex,line] of wrap(bold,item.value,9,width-16).slice(0,2).entries())page.drawText(line,{x:x+8,y:y-31-lineIndex*10,size:9,font:bold,color:C.navy})}y-=height+5};
 const gridRows=(items)=>{for(let index=0;index<items.length;index+=2){const pair=items.slice(index,index+2),width=257.5,wrapped=pair.map((item)=>wrap(regular,item.value,8.5,width-110)),height=Math.max(34,...wrapped.map((lines)=>lines.length*10+16));ensure(height+3);for(let column=0;column<pair.length;column++){const x=40+column*width;page.drawRectangle({x,y:y-height,width,height,color:C.white,borderColor:C.line,borderWidth:.5});page.drawText(String(pair[column].label).toUpperCase(),{x:x+8,y:y-14,size:6.5,font:bold,color:C.orange});let ly=y-14;for(const line of wrapped[column]){page.drawText(line,{x:x+105,y:ly,size:8.5,font:regular,color:C.navy});ly-=10}}y-=height}y-=5};
 const fareRows=(items)=>{const x=300,width=255;ensure(items.length*25+10);for(const [index,item] of items.entries()){const total=index===items.length-1;if(total)page.drawLine({start:{x,y:y-2},end:{x:x+width,y:y-2},thickness:1,color:C.forest});page.drawText(String(item.label),{x:x+10,y:y-17,size:total?10:8.5,font:total?bold:regular,color:total?C.forest:C.navy});const value=String(item.value),font=total?bold:regular,size=total?10:8.5;page.drawText(value,{x:x+width-10-font.widthOfTextAtSize(value,size),y:y-17,size,font,color:total?C.forest:C.navy});y-=total?30:24}y-=5};
 const drawTable=(data)=>{const columns=data.headers.length,raw=data.widths?.length===columns?data.widths:Array(columns).fill(1),sum=raw.reduce((a,b)=>a+b,0),widths=raw.map((item)=>515*item/sum),offsets=widths.map((_,index)=>widths.slice(0,index).reduce((a,b)=>a+b,0));const renderHeader=()=>{ensure(32);for(let i=0;i<columns;i++){page.drawRectangle({x:40+offsets[i],y:y-29,width:widths[i],height:29,color:C.forest,borderColor:C.line,borderWidth:.5});wrap(bold,data.headers[i],7,widths[i]-12).slice(0,2).forEach((line,index)=>page.drawText(line,{x:46+offsets[i],y:y-13-index*8,size:7,font:bold,color:C.white}))}y-=29};renderHeader();for(const values of data.rows){const wrapped=values.map((value,index)=>wrap(regular,value,7.5,widths[index]-12)),height=Math.max(28,...wrapped.map((lines)=>lines.length*10+10));if(y-height<55){addPage();sectionHeading(`${model.title} - continued`);renderHeader()}for(let i=0;i<columns;i++){page.drawRectangle({x:40+offsets[i],y:y-height,width:widths[i],height,color:C.white,borderColor:C.line,borderWidth:.5});let ly=y-14;for(const line of wrapped[i]){page.drawText(line,{x:46+offsets[i],y:ly,size:7.5,font:regular,color:C.navy});ly-=10}}y-=height}y-=5};
 addPage();const titleWidth=bold.widthOfTextAtSize(model.title,19);drawLines(model.title,{x:Math.max(42,(595.28-titleWidth)/2),width:511,size:19,font:bold,color:C.forest});y-=2;const subtitleWidth=bold.widthOfTextAtSize(model.subtitle,10);drawLines(model.subtitle,{x:Math.max(42,(595.28-subtitleWidth)/2),width:511,size:10,font:bold,color:C.orange});y-=8;if(model.status==="draft")page.drawText("DRAFT",{x:420,y:675,size:28,font:bold,color:rgb(.85,.85,.85),rotate:degrees(25)});if(model.metaLayout==="compact")compactMeta(model.meta);else keyRows(model.meta);
 for(const section of model.sections||[]){if(!section?.heading||(!section.rows?.length&&!section.table?.rows?.length&&!section.bullets?.length&&!section.text))continue;if(section.layout==="fare")ensure(48+section.rows.length*25);sectionHeading(section.heading);if(section.text){drawLines(section.text,{size:8.5});y-=8}if(section.rows?.length){if(section.layout==="grid")gridRows(section.rows);else if(section.layout==="fare")fareRows(section.rows);else keyRows(section.rows)}if(section.table?.rows?.length)drawTable(section.table);for(const bullet of section.bullets||[]){const lines=wrap(regular,bullet,8.5,490);ensure(lines.length*11+8);page.drawCircle({x:47,y:y-3,size:2,color:C.orange});let ly=y;for(const line of lines){page.drawText(line,{x:56,y:ly,size:8.5,font:regular,color:C.navy});ly-=11}y-=lines.length*11+5}}
 const pages=pdf.getPages();pages.forEach((item,index)=>{item.drawLine({start:{x:40,y:38},end:{x:555,y:38},thickness:.5,color:C.line});item.drawText(`${settings.brandName||"NaysTrip"} | ${settings.email||""} | ${settings.phone||""}`,{x:40,y:22,size:7,font:regular,color:C.grey});item.drawText(`Page ${index+1} of ${pages.length}`,{x:500,y:22,size:7,font:regular,color:C.grey})});return Buffer.from(await pdf.save());
}
