import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { defaultSiteSettings } from "../../src/data/siteConfig.js";
import { supabaseRequest } from "../_shared.js";

export const colours={navy:rgb(35/255,59/255,79/255),orange:rgb(244/255,92/255,15/255),forest:rgb(23/255,60/255,52/255),grey:rgb(.35,.39,.43),cream:rgb(1,.98,.95),sand:rgb(1,.94,.84),white:rgb(1,1,1)};
export const wrap=(font,text,size,width)=>{const words=String(text||"").split(/\s+/);const lines=[];let line="";for(const word of words){const candidate=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(candidate,size)>width&&line){lines.push(line);line=word}else line=candidate}if(line)lines.push(line);return lines};

export async function embedPdfImage(pdf,source){
 if(!source)return null;
 try{if(String(source).startsWith("/")){const bytes=await readFile(join(process.cwd(),String(source).replace(/^\/+/,"")));return /\.png$/i.test(source)?await pdf.embedPng(bytes):await pdf.embedJpg(bytes)}const response=await fetch(source,{signal:AbortSignal.timeout(4500)});if(!response.ok)return null;const bytes=await response.arrayBuffer();const type=response.headers.get("content-type")||"";return type.includes("png")?await pdf.embedPng(bytes):await pdf.embedJpg(bytes)}catch{return null}
}

export async function createBrandedPdf(title,subtitle=""){
 const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);
 let siteSettings=defaultSiteSettings;try{const response=await supabaseRequest("website_settings?id=eq.true&select=data&limit=1");if(response.ok){const [row]=await response.json();siteSettings={...defaultSiteSettings,...(row?.data||{})}}}catch{}
 let logo=null;try{logo=await pdf.embedPng(await readFile(join(process.cwd(),"public","branding","naystrip-logo.png")))}catch(error){console.error("pdf_logo_unavailable",error.message)}
 const siteHost=(()=>{try{return new URL(siteSettings.website||process.env.PUBLIC_SITE_URL||"https://www.naystrip.com").host}catch{return "www.naystrip.com"}})();
 const decorate=(page,{compact=false}={})=>{page.drawRectangle({x:0,y:0,width:595.28,height:841.89,color:colours.cream});page.drawRectangle({x:0,y:823,width:595.28,height:19,color:colours.orange});if(logo){const mark=logo.scaleToFit(260,260);page.drawImage(logo,{x:(595.28-mark.width)/2,y:(841.89-mark.height)/2-20,width:mark.width,height:mark.height,opacity:.055});const scaled=logo.scaleToFit(compact?58:104,compact?58:104);page.drawImage(logo,{x:42,y:compact?748:700,width:scaled.width,height:scaled.height})}page.drawText(`${siteSettings.email}  |  ${siteSettings.phone}`,{x:330,y:792,size:7,font:regular,color:colours.grey});page.drawText(siteHost,{x:459,y:30,size:7,font:bold,color:colours.forest});page.drawText(`${siteSettings.brandName||"NaysTrip & Treks"}  -  ${siteSettings.tagline||"Leisure to Adventure"}`,{x:42,y:30,size:7,font:regular,color:colours.grey});};
 const addPage=()=>{const page=pdf.addPage([595.28,841.89]);decorate(page);page.drawText("NAYSTRIP  -  LEISURE TO ADVENTURE",{x:365,y:790,size:8,font:bold,color:colours.forest});page.drawText(title,{x:42,y:650,size:25,font:bold,color:colours.forest,maxWidth:510});if(subtitle)page.drawText(subtitle,{x:42,y:625,size:10,font:regular,color:colours.grey,maxWidth:510});return {page,y:590}};
 const addContentPage=(heading="")=>{const page=pdf.addPage([595.28,841.89]);decorate(page,{compact:true});if(heading)page.drawText(heading.toUpperCase(),{x:42,y:742,size:11,font:bold,color:colours.orange});page.drawLine({start:{x:42,y:732},end:{x:553,y:732},thickness:1,color:rgb(.86,.83,.76)});return {page,y:710}};
 const addCoverPage=({hero,summary=[],meta=[]}={})=>{const page=pdf.addPage([595.28,841.89]);decorate(page,{compact:true});page.drawText("CURATED TRAVEL DOCUMENT",{x:42,y:718,size:8,font:bold,color:colours.orange});for(const [index,line] of wrap(bold,title,28,510).slice(0,2).entries())page.drawText(line,{x:42,y:680-index*32,size:28,font:bold,color:colours.forest});page.drawText(subtitle,{x:42,y:608,size:10,font:regular,color:colours.grey,maxWidth:510});page.drawRectangle({x:42,y:340,width:330,height:230,color:rgb(.9,.91,.88)});if(hero){const fitted=hero.scaleToFit(330,230);page.drawImage(hero,{x:42+(330-fitted.width)/2,y:340+(230-fitted.height)/2,width:fitted.width,height:fitted.height})}page.drawRectangle({x:388,y:340,width:165,height:230,color:colours.forest});page.drawText("PACKAGE SUMMARY",{x:405,y:542,size:8,font:bold,color:rgb(1,.72,.3)});let sy=512;for(const [label,value] of summary){page.drawText(String(label).toUpperCase(),{x:405,y:sy,size:6.5,font:bold,color:rgb(.72,.82,.78)});sy-=15;for(const line of wrap(bold,value||"On request",10,130).slice(0,2)){page.drawText(line,{x:405,y:sy,size:10,font:bold,color:colours.white});sy-=13}sy-=12}let my=312;for(const [label,value] of meta){page.drawText(`${label}: ${value}`,{x:42,y:my,size:7.5,font:regular,color:colours.grey});my-=13}return {page,y:my-12}};
 return {pdf,regular,bold,logo,settings:siteSettings,addPage,addContentPage,addCoverPage};
}

export function sendPdf(res,bytes,filename){res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",`attachment; filename="${filename}"`);res.setHeader("Cache-Control","private, no-store");return res.status(200).send(Buffer.from(bytes))}
