import {json,supabaseRequest} from "../_shared.js";
import {authUser} from "../_auth.js";
import {bookingDocument} from "./_booking-docs.js";
import {downloadBookingDocument,uploadBookingDocument} from "../_storage.js";

async function isAdmin(userId){const response=await supabaseRequest(`admin_users?user_id=eq.${userId}&status=eq.active&select=user_id&limit=1`);return response.ok&&(await response.json()).length>0}
export default async function handler(req,res){
 if(req.method!=="GET")return json(res,405,{error:"Method not allowed"});const user=await authUser(req);if(!user)return json(res,401,{error:"Sign in to download documents"});
 const documentId=String(req.query?.documentId||"").replace(/[^a-f0-9-]/gi,"");
 if(documentId){const response=await supabaseRequest(`booking_documents?id=eq.${documentId}&select=*,booking:bookings(reference,customer_id)&limit=1`);const documents=await response.json();if(!response.ok){console.error("booking_document_lookup_failed",{status:response.status,error:documents});return json(res,502,{error:"Document could not be loaded"})}const document=documents[0];if(!document)return json(res,404,{error:"Document not found"});if(document.booking?.customer_id!==user.id&&!await isAdmin(user.id))return json(res,403,{error:"You do not have access to this document"});try{const bytes=await downloadBookingDocument(document.storage_path);const filename=(document.display_name||`${document.booking.reference}-${document.document_type}`).replace(/[^a-z0-9-]+/gi,"-");res.setHeader("Content-Type",document.content_type||"application/pdf");res.setHeader("Content-Disposition",`inline; filename="${filename}.pdf"`);res.setHeader("Cache-Control","private, no-store");return res.status(200).send(bytes)}catch(error){console.error("booking_document_download_failed",{documentId,error});return json(res,404,{error:"Document file is unavailable"})}}
 const reference=String(req.query?.reference||"").replace(/[^A-Z0-9-]/g,"").slice(0,40);const type=["voucher","invoice","receipt","itinerary"].includes(req.query?.type)?req.query.type:"voucher";const bookingResponse=await supabaseRequest(`bookings?reference=eq.${encodeURIComponent(reference)}&select=*,package:packages(title,slug,destination_names,days,nights,start_point,itinerary:package_itinerary_days(day_number,title,description,meals,stay,transfers,activities)),travellers:booking_travellers(full_name,first_name,last_name,traveller_type),addons:booking_addons(*),payments(*)&limit=1`);const bookings=await bookingResponse.json();if(!bookingResponse.ok){console.error("booking_document_booking_query_failed",{reference,type,status:bookingResponse.status,error:bookings});return json(res,502,{error:"Booking document data could not be loaded"})}const booking=bookings[0];if(!booking)return json(res,404,{error:"Booking not found"});booking.itinerary=booking.package?.itinerary||[];if(booking.customer_id!==user.id&&!await isAdmin(user.id))return json(res,403,{error:"You do not have access to this document"});
 try{const bytes=await bookingDocument(booking,type);const path=`bookings/${booking.id}/${type}.pdf`;try{const storage=await uploadBookingDocument(path,bytes);if(storage.configured){const existing=await supabaseRequest(`booking_documents?booking_id=eq.${booking.id}&document_type=eq.${type}&select=version&order=version.desc&limit=1`);const rows=await existing.json();const version=Number(rows[0]?.version||0)+1;await supabaseRequest("booking_documents",{method:"POST",body:JSON.stringify({booking_id:booking.id,document_type:type,storage_path:path,version,display_name:`${type} - ${reference}`,content_type:"application/pdf"})});const column={voucher:"voucher_storage_path",invoice:"invoice_storage_path",receipt:"receipt_storage_path",itinerary:"itinerary_storage_path"}[type];await supabaseRequest(`bookings?id=eq.${booking.id}`,{method:"PATCH",body:JSON.stringify({[column]:path,updated_at:new Date().toISOString()})})}}catch(error){console.error("document_storage_failed",error.message)}const names={invoice:`NAYSTRIP-Invoice-INV-${reference.replace("NTB-","")}.pdf`,voucher:`NAYSTRIP-Booking-Voucher-${reference}.pdf`,itinerary:`NAYSTRIP-Itinerary-${reference}.pdf`,receipt:`NAYSTRIP-Receipt-${reference}.pdf`};res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",`attachment; filename="${names[type]}"`);res.setHeader("Cache-Control","private, no-store");return res.status(200).send(bytes)}catch(error){console.error("document_generation_failed",error);return json(res,500,{error:"Document could not be generated"})}
}
