import {requireAdmin} from "../_admin.js";
import {json,supabaseRequest} from "../_shared.js";
import {uploadBookingDocument} from "../_storage.js";
import {colours,createBrandedPdf,sendPdf,wrap} from "./_pdf.js";

const clean=(value,max=2000)=>String(value??"").trim().replace(/[<>]/g,"").slice(0,max);
const money=value=>{if(!value)return "";const numeric=Number(String(value).replace(/[^0-9.]/g,""));return Number.isFinite(numeric)?`INR ${numeric.toLocaleString("en-IN")}`:clean(value,60)};

export default async function handler(req,res){
 const admin=await requireAdmin(req,res);if(!admin)return;if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});
 const type=req.body?.type==="taxi"?"taxi":"hotel";const fields=req.body?.fields||{};const reference=clean(fields.reference,40).replace(/[^A-Za-z0-9-]/g,"");const voucherNumber=clean(fields.voucherNumber,40).replace(/[^A-Za-z0-9-]/g,"")||reference;if(!clean(fields.customer,120)||!reference)return json(res,422,{error:"Customer and booking reference are required"});
 try{
  const title=type==="hotel"?"Hotel Booking Voucher":"Taxi / Transport Voucher";const {pdf,regular,bold,settings,addContentPage}=await createBrandedPdf(title,`Booking reference ${reference}`);let {page,y}=addContentPage(title);
  const ensure=(space=90)=>{if(y<space)({page,y}=addContentPage(title))};
  const line=(label,value,{wide=false}={})=>{const safe=clean(value);if(!safe)return;ensure(wide?100:55);page.drawText(clean(label,80).toUpperCase(),{x:42,y,size:7,font:bold,color:colours.orange});y-=15;for(const item of wrap(regular,safe,9.5,500)){page.drawText(item,{x:42,y,size:9.5,font:regular,color:colours.forest});y-=13}y-=10};
  page.drawText(voucherNumber,{x:405,y:700,size:12,font:bold,color:colours.forest});y=682;line("Voucher number",voucherNumber);line("Booking reference",reference);line("Prepared for",fields.customer);line("Confirmation status",fields.status||"Confirmed");
  const rows=type==="hotel"?[["Hotel",[fields.hotel,fields.category].filter(Boolean).join(" · ")],["Address / contact",[fields.location,fields.hotelContact].filter(Boolean).join(" · ")],["Stay",[fields.checkIn,fields.checkInTime,fields.checkOut&&`to ${fields.checkOut}`,fields.checkOutTime].filter(Boolean).join(" ")],["Duration / accommodation",[fields.duration,fields.accommodation].filter(Boolean).join(" · ")],["Rooms / guests",[fields.rooms&&`${fields.rooms} room(s)`,fields.adults&&`${fields.adults} adult(s)`,fields.children&&`${fields.children} child(ren)`].filter(Boolean).join(" · ")],["Room and occupancy",[fields.roomType,fields.occupancy].filter(Boolean).join(" · ")],["Room-wise guests",fields.guestNames,{wide:true}],["Meal plan",fields.mealPlan],["Inclusions",fields.inclusions,{wide:true}],["Special requests",fields.specialRequests,{wide:true}],["Price",[fields.baseAmount&&`Base ${money(fields.baseAmount)}`,fields.taxes&&`Taxes ${money(fields.taxes)}`,fields.fees&&`Fees ${money(fields.fees)}`,fields.amount&&`Total ${money(fields.amount)}`].filter(Boolean).join(" · ")],["Cancellation policy",fields.cancellationPolicy,{wide:true}],["Check-in instructions",fields.checkInInstructions,{wide:true}],["Hotel booking policy",fields.hotelPolicy,{wide:true}],["No-show / amendments / refunds",fields.policyNotes,{wide:true}],["Important information",fields.notes,{wide:true}]]:[["Pickup date / time",[fields.travelDate,fields.pickupTime].filter(Boolean).join(" · ")],["Pickup",fields.pickup],["Drop",[fields.drop,fields.dropDate,fields.dropTime].filter(Boolean).join(" · ")],["Vehicle(s)",[fields.vehicle,fields.vehicleCount&&`${fields.vehicleCount} vehicle(s)`,fields.vehicleNumber].filter(Boolean).join(" · ")],["Driver",[fields.driverName,fields.driverPhone].filter(Boolean).join(" · ")],["Passengers",fields.passengers],["Included use",[fields.duration,fields.kilometres&&`${fields.kilometres} km`].filter(Boolean).join(" · ")],["Extra charges",fields.extraCharges,{wide:true}],["Toll / parking / state tax",fields.tolls,{wide:true}],["Driver room / night arrangement",fields.room],["Route",fields.route,{wide:true}],["Sightseeing",fields.sightseeing,{wide:true}],["Detailed itinerary",fields.itinerary,{wide:true}],["Inclusions",fields.inclusions,{wide:true}],["Exclusions",fields.exclusions,{wide:true}],["Special instructions",fields.specialRequests,{wide:true}],["Cancellation policy",fields.cancellationPolicy,{wide:true}],["Total amount",money(fields.amount)],["Important information",fields.notes,{wide:true}]];
  for(const [label,value,options] of rows)line(label,value,options);line("Customer contact",fields.contact);line("NaysTrip assistance",`${settings.supportPhone||settings.phone} · ${settings.email}`);
  pdf.getPages().forEach((item,index)=>item.drawText(`Page ${index+1} of ${pdf.getPageCount()}`,{x:275,y:30,size:7,font:regular,color:colours.grey}));const bytes=await pdf.save();const bookingResponse=await supabaseRequest(`bookings?reference=eq.${encodeURIComponent(reference)}&select=id&limit=1`);const [booking]=bookingResponse.ok?await bookingResponse.json():[];if(booking){const documentType=type==="hotel"?"hotel_voucher":"transport_voucher";const versions=await supabaseRequest(`booking_documents?booking_id=eq.${booking.id}&document_type=eq.${documentType}&select=version&order=version.desc&limit=1`);const version=Number((await versions.json())[0]?.version||0)+1;const path=`bookings/${booking.id}/${documentType}-${version}.pdf`;const stored=await uploadBookingDocument(path,bytes,"application/pdf");if(stored.configured){const saved=await supabaseRequest("booking_documents",{method:"POST",body:JSON.stringify({booking_id:booking.id,document_type:documentType,storage_path:path,version,display_name:title,original_filename:`NAYSTRIP-${type==="hotel"?"Hotel":"Transport"}-Voucher-${voucherNumber}.pdf`,content_type:"application/pdf",uploaded_by:admin.user_id})});if(!saved.ok)return json(res,502,{error:"Voucher was generated but could not be saved securely"})}}return sendPdf(res,bytes,`NAYSTRIP-${type==="hotel"?"Hotel":"Transport"}-Voucher-${voucherNumber}.pdf`);
 }catch(error){console.error("service_voucher_failed",error);return json(res,500,{error:"Voucher could not be generated"})}
}
