import { requireAdmin } from "../_admin.js";
import { json, supabaseRequest } from "../_shared.js";
import { uploadBookingDocument } from "../_storage.js";
import { generateBookingDocument } from "./_booking-docs.js";

const clean=(value,max=3000)=>String(value??"").trim().replace(/[<>]/g,"").slice(0,max);
const numeric=value=>{const result=Number(String(value||"").replace(/[^0-9.-]/g,""));return Number.isFinite(result)?result:null};

export default async function handler(req,res){const admin=await requireAdmin(req,res);if(!admin)return;if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});const kind=req.body?.type==="taxi"?"transport_voucher":"hotel_voucher",format=req.body?.format==="docx"?"docx":"pdf",fields=req.body?.fields||{},reference=clean(fields.reference,60).replace(/[^A-Za-z0-9-]/g,"");if(!clean(fields.customer,160)||!reference)return json(res,422,{error:"Customer and booking reference are required"});try{
 const response=await supabaseRequest(`bookings?reference=eq.${encodeURIComponent(reference)}&select=id,reference,customer_id,billing,operational_status,travel_date,end_date,total,subtotal,tax,room_count,traveller_count,package:packages(title,days,nights,start_point,end_point)&limit=1`);const body=await response.json();if(!response.ok||!Array.isArray(body)){console.error("service_voucher_booking_lookup_failed",{status:response.status,error:body});return json(res,502,{error:"Booking could not be verified"})}const existing=body[0]||null;
 const hotel={voucherNumber:fields.voucherNumber,hotelName:fields.hotel,hotelAddress:[fields.location,fields.hotelContact].filter(Boolean).join(" | "),rating:fields.category,checkIn:fields.checkIn,checkOut:fields.checkOut,checkInTime:fields.checkInTime,checkOutTime:fields.checkOutTime,duration:fields.duration,accommodationType:fields.accommodation,rooms:fields.rooms,guests:[fields.adults&&`${fields.adults} adult(s)`,fields.children&&`${fields.children} child(ren)`].filter(Boolean).join(", "),roomType:fields.roomType,guestNames:fields.guestNames,inclusions:[fields.mealPlan,fields.inclusions,fields.specialRequests].filter(Boolean).join("\n"),baseAmount:numeric(fields.baseAmount),taxes:numeric(fields.taxes),serviceCharges:numeric(fields.fees),total:numeric(fields.amount),cancellationPolicy:fields.cancellationPolicy,checkInInstructions:fields.checkInInstructions,importantInformation:fields.notes,bookingPolicy:fields.hotelPolicy,otherInformation:fields.policyNotes};
 const transport={voucherNumber:fields.voucherNumber,passengerName:fields.customer,travelDate:fields.travelDate,duration:fields.duration,totalKm:fields.kilometres,vehicleType:[fields.vehicle,fields.vehicleCount&&`${fields.vehicleCount} vehicle(s)`,fields.vehicleNumber].filter(Boolean).join(" | "),pickup:[fields.pickup,fields.pickupTime].filter(Boolean).join(" | "),drop:[fields.drop,fields.dropDate,fields.dropTime].filter(Boolean).join(" | "),route:fields.route,sightseeing:fields.sightseeing,inclusions:fields.inclusions,exclusions:fields.exclusions,rules:[fields.tolls,fields.extraCharges,fields.room,fields.specialRequests,fields.cancellationPolicy,fields.notes].filter(Boolean).join("\n"),totalAmount:numeric(fields.amount),itinerary:clean(fields.itinerary,10000).split(/\r?\n/).filter(Boolean).map((line,index)=>({day:index+1,title:line,details:""}))};
 const booking={...(existing||{}),reference,billing:{...(existing?.billing||{}),name:fields.customer,email:clean(fields.contact,160)},operational_status:fields.status||existing?.operational_status||"confirmed",travel_date:fields.travelDate||fields.checkIn||existing?.travel_date,end_date:fields.checkOut||fields.dropDate||existing?.end_date,total:numeric(fields.amount)??existing?.total,subtotal:numeric(fields.baseAmount)??existing?.subtotal,tax:numeric(fields.taxes)??existing?.tax,room_count:fields.rooms||existing?.room_count,traveller_count:fields.passengers||existing?.traveller_count,document_details:{[kind]:kind==="hotel_voucher"?hotel:transport},package:{...(existing?.package||{}),itinerary:transport.itinerary}};
 const generated=await generateBookingDocument(booking,kind,format);if(existing?.id){const versions=await supabaseRequest(`booking_documents?booking_id=eq.${existing.id}&document_type=eq.${kind}&document_format=eq.${format}&select=version&order=version.desc&limit=1`);const versionBody=await versions.json();if(!versions.ok||!Array.isArray(versionBody)){console.error("service_voucher_version_lookup_failed",{status:versions.status,error:versionBody});return json(res,502,{error:"Voucher version could not be prepared"})}const version=Number(versionBody[0]?.version||0)+1,path=`bookings/${existing.id}/${kind}/v${version}.${format}`;const stored=await uploadBookingDocument(path,generated.bytes,generated.contentType);if(!stored.configured)return json(res,503,{error:"Private booking-document storage is not configured"});const saved=await supabaseRequest("booking_documents",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({booking_id:existing.id,document_type:kind,document_format:format,storage_path:path,version,display_name:generated.model.filenameBase,original_filename:`${generated.model.filenameBase}.${format}`,content_type:generated.contentType,uploaded_by:admin.user_id})});const savedBody=await saved.json();if(!saved.ok||!Array.isArray(savedBody)){console.error("service_voucher_metadata_save_failed",{status:saved.status,error:savedBody});return json(res,502,{error:"Voucher was generated but could not be saved securely"})}if(savedBody[0]?.id)res.setHeader("X-Document-Id",savedBody[0].id)}
 res.setHeader("Content-Type",generated.contentType);res.setHeader("Content-Disposition",`attachment; filename="${generated.model.filenameBase}.${format}"`);res.setHeader("Cache-Control","private, no-store");return res.status(200).send(generated.bytes);
 }catch(error){console.error("service_voucher_failed",{reference,kind,format,error});return json(res,500,{error:"Voucher could not be generated"})}}
