import MediaUploader from "./MediaUploader";
import {monthlyPicks,pickGroups} from "../../data/monthlyPicks";
import usePublicPackages from "../../hooks/usePublicPackages";
import {tours} from "../../data/tours";
import {treks,expeditions} from "../../data/treksExpeditions";
export default function HomeContentSettings({form,update}) {
 const picks=form.monthlyPicks||monthlyPicks,photos=form.travellerPhotos||[],{packages}=usePublicPackages();
 const catalogue=[...new Map([...packages,...tours,...treks,...expeditions].map(p=>[p.slug,p])).values()];
 const pick=(id,key,value)=>update("monthlyPicks",picks.map(p=>p.id===id?{...p,[key]:value}:p));
 const photo=(id,key,value)=>update("travellerPhotos",photos.map(p=>p.id===id?{...p,[key]:value}:p));
 return <><section className="space-y-4 rounded-2xl border bg-white p-6"><h3 className="font-bold">Traveller Photos</h3><p className="text-sm text-slate-500">Upload approved traveller media for Recent Trips / Experiences. Save settings to publish.</p>{photos.map(p=><div key={p.id} className="space-y-3 rounded-xl border p-4"><MediaUploader label="Traveller photo" value={p.image} onChange={value=>photo(p.id,"image",value)} scope={`travellers/${p.id}`} context="traveller experience"/><label><span className="label-field">Caption (optional)</span><input className="input-field" value={p.caption||""} onChange={e=>photo(p.id,"caption",e.target.value)}/></label><label><input type="checkbox" checked={p.active!==false} onChange={e=>photo(p.id,"active",e.target.checked)}/> Visible</label><button type="button" className="btn-secondary ml-3" onClick={()=>update("travellerPhotos",photos.filter(v=>v.id!==p.id))}>Remove photo</button></div>)}<button type="button" className="btn-secondary" onClick={()=>update("travellerPhotos",[...photos,{id:crypto.randomUUID(),image:"",caption:"",active:false}])}>Add Traveller Photo</button></section><section className="space-y-4 rounded-2xl border bg-white p-6"><h3 className="font-bold">September 2026 Picks</h3>{picks.map(p=><details key={p.id} className="rounded-xl border p-4"><summary className="cursor-pointer font-bold">{p.title}</summary><div className="mt-4 space-y-3"><label><span className="label-field">Title</span><input className="input-field" value={p.title} onChange={e=>pick(p.id,"title",e.target.value)}/></label><label><span className="label-field">Duration</span><input className="input-field" value={p.duration} onChange={e=>pick(p.id,"duration",e.target.value)}/></label><label><span className="label-field">Category</span><select className="input-field" value={p.group} onChange={e=>pick(p.id,"group",Number(e.target.value))}>{pickGroups.map((g,i)=><option key={g} value={i}>{g}</option>)}</select></label><label><span className="label-field">Approved package / itinerary</span><select className="input-field" value={p.slug} onChange={e=>pick(p.id,"slug",e.target.value)}><option value="">Details on request</option>{catalogue.map(c=><option key={c.slug} value={c.slug}>{c.title||c.name}</option>)}</select></label><MediaUploader label="Approved image (optional override)" value={p.image} onChange={value=>pick(p.id,"image",value)} scope={`picks/${p.id}`} context={p.title}/><label><input type="checkbox" checked={p.active!==false} onChange={e=>pick(p.id,"active",e.target.checked)}/> Visible</label></div></details>)}</section></>
}
