import {useEffect,useRef,useState} from "react";
import {Link} from "react-router-dom";
import {MessageCircle,Phone,X} from "lucide-react";
import {getSiteSettings,loadSiteSettings} from "../../data/siteConfig";
export default function FloatingActions(){
 const [open,setOpen]=useState(false),[settings,setSettings]=useState(getSiteSettings()),root=useRef(null),trigger=useRef(null);
 useEffect(()=>{loadSiteSettings().then(setSettings).catch(()=>{})},[]);
 useEffect(()=>{if(!open)return;const close=e=>{if(e.type==="keydown"&&e.key==="Escape"){setOpen(false);trigger.current?.focus()}else if(e.type==="pointerdown"&&!root.current?.contains(e.target))setOpen(false)};document.addEventListener("pointerdown",close);document.addEventListener("keydown",close);return()=>{document.removeEventListener("pointerdown",close);document.removeEventListener("keydown",close)}},[open]);
 const phone=String(settings.phone||"").replace(/[^+\d]/g,""),whatsapp=String(settings.whatsapp||settings.phone||"").replace(/\D/g,"");
 return <div ref={root} className="fixed bottom-[max(18px,env(safe-area-inset-bottom))] right-4 z-40 flex flex-col items-end gap-2 sm:right-6">{open&&<div id="floating-contact-actions" className="grid min-w-44 gap-1 rounded-xl border bg-white p-2 shadow-2xl"><a href={`https://wa.me/${whatsapp}?text=${encodeURIComponent("Hi NaysTrip, I would like help planning a trip.")}`} target="_blank" rel="noopener noreferrer" className="flex min-h-11 items-center gap-3 rounded-lg px-4 text-sm font-bold text-[#173c34] hover:bg-emerald-50"><MessageCircle size={18}/> WhatsApp Us</a><a href={`tel:${phone}`} className="flex min-h-11 items-center gap-3 rounded-lg px-4 text-sm font-bold text-[#173c34] hover:bg-orange-50"><Phone size={18}/> Call</a><Link onClick={()=>setOpen(false)} to="/custom-trip" className="flex min-h-11 items-center rounded-lg px-4 text-sm font-bold text-[#173c34] hover:bg-orange-50">Enquiry</Link></div>}<button ref={trigger} onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="floating-contact-actions" aria-label={open?"Close contact options":"Open contact options"} className="grid h-12 w-12 place-items-center rounded-full bg-[#15803d] text-white shadow-xl hover:bg-[#166534] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4">{open?<X size={22}/>:<MessageCircle size={22}/>}</button></div>
}
