import { Facebook, Instagram, Mail, MapPin, Phone, Send, Youtube } from "lucide-react";
import { Link } from "react-router-dom";
import { getSiteSettings } from "../../data/siteConfig";
const columns={
 Company:[["About us","/about"],["Corporate travel","/corporate-travel"],["Careers","/careers"],["Contact","/contact"]],
 Explore:[["Maharashtra tours","/tours"],["Destinations","/destinations"],["Treks","/treks"],["Expeditions","/expeditions"],["Custom trip","/custom-trip"]],
 Support:[["FAQs","/faqs"],["Terms & conditions","/terms"],["Privacy policy","/privacy"],["Disclaimer","/disclaimer"],["Sitemap","/sitemap"]],
 Portal:[["Customer login","/account/login"],["B2B login","/b2b/login"],["Agent registration","/b2b/register"],["Admin","/admin/login"]],
};
export default function Footer(){const s=getSiteSettings();return <footer className="bg-[#102f29] text-white/65"><div className="container-lg py-16 sm:py-20"><div className="grid gap-12 lg:grid-cols-[1.3fr_2fr]"><div><Link to="/" className="font-display text-3xl text-white">NaysTrip <span className="text-orange-400">& Treks</span></Link><p className="mt-5 max-w-sm text-sm leading-7">{s.footerText}</p><div className="mt-6 flex gap-3"><a className="grid h-10 w-10 place-items-center border border-white/15 hover:text-orange-300" href={s.social.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram"><Instagram size={17}/></a><a className="grid h-10 w-10 place-items-center border border-white/15 hover:text-orange-300" href={s.social.youtube} target="_blank" rel="noopener noreferrer" aria-label="YouTube"><Youtube size={17}/></a><a className="grid h-10 w-10 place-items-center border border-white/15 hover:text-orange-300" href={s.social.facebook} target="_blank" rel="noopener noreferrer" aria-label="Facebook"><Facebook size={17}/></a><a className="grid h-10 w-10 place-items-center border border-white/15 hover:text-orange-300" href={s.social.telegram} target="_blank" rel="noopener noreferrer" aria-label="Telegram"><Send size={17}/></a></div></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-4">{Object.entries(columns).map(([title,links])=><div key={title}><h2 className="text-xs font-extrabold uppercase tracking-[.16em] text-white">{title}</h2><ul className="mt-5 space-y-3 text-sm">{links.map(([label,to])=><li key={to}><Link to={to} className="hover:text-orange-300">{label}</Link></li>)}</ul></div>)}</div></div>
 <div className="mt-14 grid gap-6 border-t border-white/10 pt-8 text-sm md:grid-cols-3"><a href={`tel:${s.phone.replace(/\s/g,"")}`} className="flex gap-3"><Phone className="text-orange-400" size={18}/><span><small className="block text-white/40">Enquiries</small>{s.phone}</span></a><a href={`mailto:${s.email}`} className="flex gap-3"><Mail className="text-orange-400" size={18}/><span><small className="block text-white/40">Email</small>{s.email}</span></a><span className="flex gap-3"><MapPin className="shrink-0 text-orange-400" size={18}/><span><small className="block text-white/40">Office</small>{s.address}</span></span></div>
 <div className="mt-10 flex flex-col justify-between gap-3 border-t border-white/10 pt-6 text-xs text-white/35 sm:flex-row"><span>© {new Date().getFullYear()} NaysTrip & Treks. All rights reserved.</span><span>MI24 Securetech LLP · Navi Mumbai jurisdiction</span></div></div></footer>}
