import { useEffect, useMemo, useRef, useState } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import { ChevronDown, Instagram, Mail, Menu, Phone, X, Youtube } from "lucide-react";
import { getSiteSettings, loadSiteSettings } from "../../data/siteConfig";
import BrandLogo from "../branding/BrandLogo";
const dropdownLink="block min-h-10 px-3 py-2.5 text-sm font-bold hover:bg-orange-50 hover:text-orange-600";

function MenuLinks({items,onSelect=()=>{}}){return items.map(([label,to])=><Link key={`${label}-${to}`} onClick={onSelect} to={to} className={dropdownLink}>{label}</Link>)}
function DesktopMenu({name,label,active,setActive,wide=false,children}){const open=active===name;return <div className="relative"><button type="button" aria-expanded={open} onClick={()=>setActive(open?"":name)} className="flex min-h-11 items-center gap-1 px-2.5 py-3 text-[13px] font-bold text-slate-700 hover:text-orange-600">{label}<ChevronDown size={14} className={`transition ${open?"rotate-180":""}`}/></button>{open&&<div className={`absolute right-0 top-full max-h-[70vh] overflow-y-auto border border-slate-200 bg-white p-2 shadow-xl ${wide?"w-80":"w-72"}`}>{children}</div>}</div>}
function MobileGroup({label,children,open=false}){return <details open={open} className="border-b border-white/10"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between font-display text-2xl">{label}<ChevronDown size={19}/></summary><div className="grid pb-4 pl-2 text-sm text-white/75">{children}</div></details>}

export default function Header(){
 const [open,setOpen]=useState(false);const [dropdown,setDropdown]=useState("");const [s,setSettings]=useState(getSiteSettings());const desktopNav=useRef(null);const loc=useLocation();
 const groups=useMemo(()=>{const result={domestic:[],international:[],sahyadri:[],himalaya:[],weekends:[],services:[]};for(const item of s.headerMenuOptions||[]){if(item.published===false)continue;const key=item.section==="tours"?item.subgroup:item.section==="treks"?item.subgroup:item.section;const pair=[item.label,item.target||`/packages/${item.slug}`];if(result[key])result[key].push({...item,pair})}for(const key of Object.keys(result))result[key].sort((a,b)=>{const ao=Number(a.displayOrder),bo=Number(b.displayOrder);if(Number.isFinite(ao)&&Number.isFinite(bo)&&ao!==bo)return ao-bo;return a.label.localeCompare(b.label)});return Object.fromEntries(Object.entries(result).map(([key,value])=>[key,value.map(item=>item.pair)]))},[s.headerMenuOptions]);
 const closeDropdown=()=>setDropdown("");
 useEffect(()=>{setOpen(false);setDropdown("")},[loc.pathname,loc.search]);
 useEffect(()=>{loadSiteSettings().then(setSettings).catch(()=>{})},[]);
 useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);
 useEffect(()=>{const outside=(event)=>{if(!desktopNav.current?.contains(event.target))closeDropdown()};const key=(event)=>{if(event.key==="Escape")closeDropdown()};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",key);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",key)}},[]);
 const direct=[["Destinations","/destinations"],["Blog","/blog"],["Contact","/contact"]];
 return <header className="sticky top-0 z-50 bg-white">
  <div className="bg-orange-50 text-[#173c34]"><div className="container-lg flex min-h-10 flex-wrap items-center justify-center gap-x-5 gap-y-1 px-3 py-2 text-center text-sm font-bold sm:justify-end"><Link to="/b2b/register" className="hover:text-orange-700">Travel Agent? Join NaysTrip B2B · Become a B2B Partner →</Link><Link to="/b2b/login" className="hover:text-orange-700">B2B Partner Login</Link><Link to="/account/login" className="hover:text-orange-700">Customer Login</Link></div></div>
  <div className="hidden bg-[#173c34] text-white/75 lg:block"><div className="container-lg flex h-9 items-center justify-between text-[11px] font-semibold"><div className="flex gap-6"><a href={`tel:${s.phone.replace(/\s/g,"")}`} className="flex items-center gap-2 hover:text-white"><Phone size={13}/>{s.phone}</a><a href={`mailto:${s.email}`} className="flex items-center gap-2 hover:text-white"><Mail size={13}/>{s.email}</a></div><div className="flex items-center gap-5">{s.social?.instagram&&<a href={s.social.instagram} target="_blank" rel="noopener noreferrer" aria-label="NaysTrip on Instagram"><Instagram size={14}/></a>}{s.social?.youtube&&<a href={s.social.youtube} target="_blank" rel="noopener noreferrer" aria-label="NaysTrip on YouTube"><Youtube size={14}/></a>}<Link to="/b2b/login">B2B login</Link><Link to="/account/login">Customer login</Link></div></div></div>
  <div className="border-b border-slate-200"><div className="container-lg flex h-[82px] items-center justify-between gap-5 lg:h-[96px]"><Link to="/" aria-label="NaysTrip home" className="flex shrink-0 items-center"><BrandLogo eager animated className="h-[72px] w-auto lg:h-[88px]"/></Link><nav ref={desktopNav} aria-label="Main navigation" className="hidden items-center xl:flex">
   <DesktopMenu name="tours" label="Tours" active={dropdown} setActive={setDropdown}><div><p className="px-3 pb-1 pt-2 text-[10px] font-extrabold uppercase tracking-widest text-slate-400">Domestic Tours</p><MenuLinks items={groups.domestic} onSelect={closeDropdown}/></div><div className="border-t border-slate-100"><p className="px-3 pb-1 pt-3 text-[10px] font-extrabold uppercase tracking-widest text-slate-400">International Tours</p><MenuLinks items={groups.international} onSelect={closeDropdown}/></div></DesktopMenu>
   <DesktopMenu name="treks" label="Treks & Expeditions" active={dropdown} setActive={setDropdown} wide><div><p className="px-3 pb-1 pt-2 text-[10px] font-extrabold uppercase tracking-widest text-slate-400">Sahyadri</p><MenuLinks items={groups.sahyadri} onSelect={closeDropdown}/></div><div><p className="px-3 pb-1 pt-2 text-[10px] font-extrabold uppercase tracking-widest text-slate-400">Himalaya</p><MenuLinks items={groups.himalaya} onSelect={closeDropdown}/></div></DesktopMenu>
   <DesktopMenu name="weekends" label="Weekend Getaways" active={dropdown} setActive={setDropdown}><MenuLinks items={groups.weekends} onSelect={closeDropdown}/></DesktopMenu>
   <DesktopMenu name="services" label="Travel Services" active={dropdown} setActive={setDropdown}><MenuLinks items={groups.services} onSelect={closeDropdown}/></DesktopMenu>
   {direct.map(([label,to])=><NavLink key={to} to={to} className={({isActive})=>`min-h-11 px-2.5 py-3 text-[13px] font-bold ${isActive?"text-orange-600":"text-slate-700 hover:text-orange-600"}`}>{label}</NavLink>)}
  </nav><div className="flex items-center gap-3"><Link to="/custom-trip" className="hidden bg-orange-500 px-5 py-3 text-xs font-extrabold text-white hover:bg-orange-600 sm:inline-flex">Get My Free Quote</Link><button onClick={()=>setOpen(true)} className="grid h-11 w-11 place-items-center border border-slate-300 xl:hidden" aria-label="Open menu"><Menu/></button></div></div></div>
  {open&&<div className="fixed inset-0 z-50 overflow-y-auto bg-[#102f29] pb-28 text-white xl:hidden"><div className="flex h-[86px] items-center justify-between border-b border-white/15 px-5"><Link to="/" aria-label="NaysTrip home"><BrandLogo className="h-[70px] w-auto"/></Link><button onClick={()=>setOpen(false)} aria-label="Close menu" className="grid h-11 w-11 place-items-center border border-white/25"><X/></button></div><nav className="grid gap-px p-5">
   <MobileGroup label="Tours" open><p className="pt-2 text-[10px] font-extrabold uppercase tracking-widest text-orange-300">Domestic</p><MenuLinks items={groups.domestic}/><p className="pt-3 text-[10px] font-extrabold uppercase tracking-widest text-orange-300">International</p><MenuLinks items={groups.international}/></MobileGroup>
   <MobileGroup label="Treks & Expeditions"><p className="pt-2 text-[10px] font-extrabold uppercase tracking-widest text-orange-300">Sahyadri</p><MenuLinks items={groups.sahyadri}/><p className="pt-3 text-[10px] font-extrabold uppercase tracking-widest text-orange-300">Himalaya</p><MenuLinks items={groups.himalaya}/></MobileGroup>
   <MobileGroup label="Weekend Getaways"><MenuLinks items={groups.weekends}/></MobileGroup><MobileGroup label="Travel Services"><MenuLinks items={groups.services}/></MobileGroup>
   {direct.map(([label,to])=><Link key={to} to={to} className="flex min-h-14 items-center border-b border-white/10 font-display text-2xl">{label}</Link>)}<Link to="/b2b/login" className="flex min-h-14 items-center border-b border-white/10 font-display text-2xl">B2B Partner</Link>
  </nav><div className="fixed inset-x-5 bottom-7 grid grid-cols-2 gap-3"><a href={`tel:${s.phone.replace(/\s/g,"")}`} className="grid min-h-11 place-items-center border border-white/25 bg-[#102f29] p-3 text-center text-sm font-bold">Call us</a><Link to="/custom-trip" className="grid min-h-11 place-items-center bg-orange-500 p-3 text-center text-sm font-bold">Plan a trip</Link></div></div>}
 </header>
}
