import {json,supabaseRequest} from "./_shared.js";
import crypto from "node:crypto";
export default async function handler(req,res){
 if(req.method==="GET"){try{const response=await supabaseRequest("website_settings?id=eq.true&select=data&limit=1");const rows=await response.json();if(!response.ok)return json(res,502,{error:"Settings unavailable"});return json(res,200,{settings:rows[0]?.data||{}})}catch{return json(res,200,{settings:{}})}}
 if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});
 const token=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");
 if(!token||!process.env.SUPABASE_URL||!process.env.SUPABASE_ANON_KEY)return json(res,401,{error:"Authentication required"});
 const user=await fetch(`${process.env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:process.env.SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`}});const account=await user.json();
 if(!user.ok||!account.id)return json(res,401,{error:"Invalid session"});
 const role=await supabaseRequest(`admin_users?user_id=eq.${account.id}&status=eq.active&select=user_id&limit=1`);
 if(!role.ok||(await role.json()).length!==1)return json(res,403,{error:"Admin access required"});
 const clean=(value,max=1000)=>String(value??"").trim().replace(/[<>]/g,"").slice(0,max);
 const monthlyPicks=Array.isArray(req.body?.monthlyPicks)?req.body.monthlyPicks.slice(0,50).map((item,index)=>({id:clean(item.id,80)||crypto.randomUUID(),title:clean(item.title,200),type:item.type==="trek"?"trek":"trip",destination:clean(item.destination,160),duration:clean(item.duration,80),description:clean(item.description,500),image:clean(item.image,1000),packageSlug:clean(item.packageSlug||item.slug,150),displayOrder:Number.isFinite(Number(item.displayOrder))?Number(item.displayOrder):index,published:item.published!==false&&item.active!==false,recommended:Boolean(item.recommended),label:clean(item.label,100)})).filter(item=>item.title):[];
 const events=Array.isArray(req.body?.events)?req.body.events.slice(0,100).map((item,index)=>({id:clean(item.id,80)||crypto.randomUUID(),title:clean(item.title,200),shortDescription:clean(item.shortDescription,500),description:clean(item.description,10000),category:clean(item.category,100),location:clean(item.location,200),startDate:clean(item.startDate,10),endDate:clean(item.endDate,10),startTime:clean(item.startTime,8),image:clean(item.image,1000),ctaLabel:clean(item.ctaLabel,80),ctaTarget:clean(item.ctaTarget,1000),published:Boolean(item.published),featured:Boolean(item.featured),displayOrder:Number.isFinite(Number(item.displayOrder))?Number(item.displayOrder):index})).filter(item=>item.title&&/^\d{4}-\d{2}-\d{2}$/.test(item.startDate)):[];
 const headerMenuOptions=Array.isArray(req.body?.headerMenuOptions)?req.body.headerMenuOptions.slice(0,250).map((item,index)=>({id:clean(item.id,80)||crypto.randomUUID(),section:["tours","treks","weekends","services"].includes(item.section)?item.section:"tours",subgroup:clean(item.subgroup,40),label:clean(item.label,120),slug:clean(item.slug,120).toLowerCase().replace(/[^a-z0-9-]/g,""),target:clean(item.target,500),displayOrder:Number.isFinite(Number(item.displayOrder))?Number(item.displayOrder):index,published:item.published!==false})).filter(item=>item.label&&item.slug):[];
 const allowed={travellerPhotos:Array.isArray(req.body?.travellerPhotos)?req.body.travellerPhotos.slice(0,100):[],monthlyPicks,events,headerMenuOptions,brandName:req.body?.brandName,tagline:req.body?.tagline,phone:req.body?.phone,supportPhone:req.body?.supportPhone,whatsapp:req.body?.whatsapp,email:req.body?.email,website:req.body?.website,cancellationEmail:req.body?.cancellationEmail,address:req.body?.address,businessLegalName:req.body?.businessLegalName,gstNumber:req.body?.gstNumber,invoiceAddress:req.body?.invoiceAddress,businessHours:req.body?.businessHours,footerText:req.body?.footerText,social:req.body?.social,homepageCtaText:req.body?.homepageCtaText,topTripSlugs:Array.isArray(req.body?.topTripSlugs)?req.body.topTripSlugs.slice(0,12):[],topTrekSlugs:Array.isArray(req.body?.topTrekSlugs)?req.body.topTrekSlugs.slice(0,12):[],trustMetrics:req.body?.trustMetrics||{},team:Array.isArray(req.body?.team)?req.body.team.slice(0,20):[],socialInitiative:req.body?.socialInitiative||{},b2bDefaultMarkupPercent:Math.min(100,Math.max(0,Number(req.body?.b2bDefaultMarkupPercent??10)))};
 const saved=await supabaseRequest("website_settings?id=eq.true",{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({data:allowed,updated_at:new Date().toISOString()})});
 if(!saved.ok)return json(res,502,{error:"Settings update failed"});
 return json(res,200,{saved:true});
}
