import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FileText, Headphones, LogOut, MessageCircle, Plus, WalletCards } from "lucide-react";
import BrandLogo from "../components/branding/BrandLogo";
import { LoadError, PageLoader } from "../components/shared/Loading";
import { getToken, portalFetch, sessionKey } from "../utils/portal";

const emptyEnquiry={destination:"",travelDate:"",pax:2,adults:2,children:0,hotelCategory:"3-star",transportRequired:true,sightseeing:"",mealPlan:"Breakfast",flightRequired:false,specialRequirements:""};
const emptyQuote={enquiryId:"",rateId:"",customerName:"",customerEmail:"",customerPhone:"",title:"",markupPercent:10,validUntil:"",terms:""};
const decodePayload=(value)=>{if(!value)return{};if(typeof value==="object")return value;try{return JSON.parse(value)}catch{return{}}};

export default function B2BDashboard(){
 const navigate=useNavigate();const [data,setData]=useState(null);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [enquiry,setEnquiry]=useState(emptyEnquiry);const [quote,setQuote]=useState(emptyQuote);const [viewing,setViewing]=useState(null);
 const load=()=>portalFetch("/api/b2b/dashboard",{},"agent").then((result)=>{setData(result);setQuote((current)=>({...current,markupPercent:current.enquiryId?current.markupPercent:result.defaultMarkupPercent}))});
 useEffect(()=>{if(!getToken("agent"))navigate("/b2b/login?returnTo=/b2b/dashboard");else load().catch((err)=>setError(err.message))},[navigate]);
 const summaries=useMemo(()=>data?[["New Enquiries",data.enquiries.filter((item)=>item.status==="new").length],["Open Enquiries",data.enquiries.filter((item)=>!["converted","lost","closed"].includes(item.status)).length],["Quotations Pending",data.quotations.filter((item)=>["draft","sent"].includes(item.status)).length],["Confirmed Bookings",data.bookings.filter((item)=>["confirmed","fully_paid","completed"].includes(item.operational_status)).length]]:[],[data]);
 const act=async(body,success)=>{setBusy(true);setError("");setMessage("");try{const result=await portalFetch("/api/b2b/dashboard",{method:"POST",body:JSON.stringify(body)},"agent");setMessage(typeof success==="function"?success(result):success);await load();return result}catch(err){setError(err.message);return null}finally{setBusy(false)}};
 const createEnquiry=async(event)=>{event.preventDefault();const result=await act({action:"create_enquiry",...enquiry},(value)=>`Enquiry ${value.enquiry.id} created.`);if(result)setEnquiry(emptyEnquiry)};
 const createQuote=async(event)=>{event.preventDefault();const result=await act({action:"create_quotation",...quote},(value)=>`Quotation ${value.quotation.reference} created.`);if(result)setQuote({...emptyQuote,markupPercent:data.defaultMarkupPercent})};
 const quoteAction=async(id,operation)=>{const result=await act({action:"quotation_action",id,operation},operation==="share"?(value)=>`Customer link ready: ${value.url}`:`Quotation ${operation.replace("_"," ")} completed.`);if(result?.url){await navigator.clipboard?.writeText(result.url);window.open(result.url,"_blank","noopener,noreferrer")}};
 const downloadQuote=async(item)=>{setBusy(true);try{const response=await fetch(`/api/documents/quotation?id=${encodeURIComponent(item.id)}`,{headers:{Authorization:`Bearer ${getToken("agent")}`}});if(!response.ok)throw new Error((await response.json()).error||"Download failed");const url=URL.createObjectURL(await response.blob());const anchor=document.createElement("a");anchor.href=url;anchor.download=`${item.reference}.pdf`;anchor.click();URL.revokeObjectURL(url)}catch(err){setError(err.message)}finally{setBusy(false)}};
 const logout=()=>{sessionStorage.removeItem(sessionKey("agent"));navigate("/b2b/login")};
 if(!data)return error?<LoadError message={error} onRetry={()=>{setError("");load().catch((err)=>setError(err.message))}} loginTo="/b2b/login"/>:<PageLoader full label="Loading partner workspace…"/>;
 const supportPhone=String(data.support.phone||"").replace(/\D/g,"");const whatsapp=String(data.support.whatsapp||"").replace(/\D/g,"");
 return <main className="min-h-screen bg-[#f5f3ed] text-slate-800">
  <header className="sticky top-0 z-30 border-b bg-white"><div className="container-lg flex min-h-20 flex-wrap items-center justify-between gap-3 py-2"><Link to="/"><BrandLogo className="h-16"/></Link><nav className="hidden items-center gap-5 text-sm font-bold lg:flex"><a href="#dashboard">Dashboard</a><a href="#enquiries">Enquiries</a><a href="#bookings">Bookings</a><a href="#rates">Rates</a><a href="#documents">Documents</a><a href="#support">Support</a></nav><div className="flex items-center gap-2"><span className="hidden text-right text-xs sm:block"><strong className="block">{data.agent.business_name}</strong><span className="capitalize text-emerald-700">{data.agent.verification_status}</span></span><button onClick={logout} className="btn-secondary"><LogOut size={15}/>Logout</button></div></div></header>
  <div id="dashboard" className="container-lg py-8 sm:py-10"><p className="eyebrow">B2B PARTNER PORTAL</p><h1 className="mt-2 font-display text-3xl text-[#173c34] sm:text-5xl">Welcome, {data.agent.business_name}</h1><p className="mt-2 text-slate-500">Private partner rates and records are visible only to your approved account.</p>
   {error&&<p role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{message&&<p role="status" className="mt-5 break-words rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{message}</p>}
   <section className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{summaries.map(([label,value])=><article key={label} className="rounded-2xl bg-white p-5 shadow-sm"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</span><strong className="mt-3 block text-3xl text-[#173c34]">{value}</strong></article>)}</section>
   <div className="mt-6 flex flex-wrap gap-3"><a href="#new-enquiry" className="btn-primary"><Plus size={16}/>Create New Enquiry</a><a href="#rates" className="btn-secondary"><WalletCards size={16}/>View B2B Rates</a></div>

   <section id="enquiries" className="mt-10"><h2 className="font-display text-2xl text-[#173c34]">Recent Enquiries</h2><div className="mt-4 overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-400"><th className="p-4">Enquiry ID</th><th className="p-4">Destination</th><th className="p-4">Travel Date</th><th className="p-4">Pax</th><th className="p-4">Status</th></tr></thead><tbody>{data.enquiries.map((item)=>{const payload=decodePayload(item.payload);return <tr key={item.id} className="border-b"><td className="p-4 font-mono text-xs">{item.id}</td><td className="p-4 font-bold">{item.destination}</td><td className="p-4">{payload.travelDate||"—"}</td><td className="p-4">{payload.pax||"—"}</td><td className="p-4 capitalize">{item.status}</td></tr>})}{!data.enquiries.length&&<tr><td colSpan="5" className="p-8 text-center text-slate-400">No enquiries yet.</td></tr>}</tbody></table></div></section>

   <section id="new-enquiry" className="mt-10 rounded-2xl bg-white p-5 sm:p-7"><h2 className="font-display text-2xl text-[#173c34]">Create New Enquiry</h2><form onSubmit={createEnquiry} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["destination","Destination","text"],["travelDate","Travel Date","date"],["pax","No. of Pax","number"],["adults","Adults","number"],["children","Children","number"],["hotelCategory","Hotel Category","text"],["sightseeing","Sightseeing","text"],["mealPlan","Meal Plan","text"]].map(([key,label,type])=><label key={key}><span className="label-field">{label}</span><input required={["destination","travelDate","pax","adults"].includes(key)} min={type==="number"?0:undefined} type={type} value={enquiry[key]} onChange={(event)=>setEnquiry({...enquiry,[key]:event.target.value})} className="input-field"/></label>)}<label className="flex min-h-11 items-center gap-2 pt-6 text-sm font-bold"><input type="checkbox" checked={enquiry.transportRequired} onChange={(event)=>setEnquiry({...enquiry,transportRequired:event.target.checked})}/>Transport Required</label><label className="flex min-h-11 items-center gap-2 pt-6 text-sm font-bold"><input type="checkbox" checked={enquiry.flightRequired} onChange={(event)=>setEnquiry({...enquiry,flightRequired:event.target.checked})}/>Flight Required</label><label className="sm:col-span-2 lg:col-span-3"><span className="label-field">Special Requirements</span><textarea rows="3" value={enquiry.specialRequirements} onChange={(event)=>setEnquiry({...enquiry,specialRequirements:event.target.value})} className="input-field"/></label><button disabled={busy} className="btn-primary">{busy?"Saving…":"Submit Enquiry"}</button></form></section>

   <section id="rates" className="mt-10"><h2 className="font-display text-2xl text-[#173c34]">B2B Packages & Rates</h2><div className="mt-4 overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left"><th className="p-4">Package</th><th className="p-4">Destination</th><th className="p-4">Nights</th><th className="p-4">Agent Rate</th><th className="p-4">Validity</th></tr></thead><tbody>{data.rates.map((rate)=><tr key={rate.id} className="border-b"><td className="p-4 font-bold">{rate.package?.title}</td><td className="p-4">{rate.package?.destination_names?.join(", ")||"—"}</td><td className="p-4">{rate.package?.nights??"—"}</td><td className="p-4 font-bold text-emerald-700">INR {Number(rate.agent_price||0).toLocaleString("en-IN")}</td><td className="p-4">{rate.valid_from||"—"} to {rate.valid_until||"—"}</td></tr>)}{!data.rates.length&&<tr><td colSpan="5" className="p-8 text-center text-slate-400">No approved partner rates are currently configured.</td></tr>}</tbody></table></div></section>

   <section className="mt-10 rounded-2xl bg-white p-5 sm:p-7"><h2 className="font-display text-2xl text-[#173c34]">Create Customer Quotation</h2><p className="mt-2 text-sm text-slate-500">The customer total includes the selected markup; the secure customer link never exposes your agent cost.</p><form onSubmit={createQuote} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label><span className="label-field">Enquiry</span><select required value={quote.enquiryId} onChange={(event)=>setQuote({...quote,enquiryId:event.target.value})} className="input-field"><option value="">Select enquiry</option>{data.enquiries.map((item)=><option key={item.id} value={item.id}>{item.id} · {item.destination}</option>)}</select></label><label><span className="label-field">B2B Rate</span><select required value={quote.rateId} onChange={(event)=>setQuote({...quote,rateId:event.target.value})} className="input-field"><option value="">Select rate</option>{data.rates.map((rate)=><option key={rate.id} value={rate.id}>{rate.package?.title} · INR {Number(rate.agent_price||0).toLocaleString("en-IN")}</option>)}</select></label><label><span className="label-field">Customer Markup (%)</span><input required type="number" min="0" max="100" step="0.1" value={quote.markupPercent} onChange={(event)=>setQuote({...quote,markupPercent:event.target.value})} className="input-field"/></label>{[["customerName","Customer Name","text"],["customerEmail","Customer Email","email"],["customerPhone","Customer Phone","text"],["title","Quotation Title","text"],["validUntil","Valid Until","date"]].map(([key,label,type])=><label key={key}><span className="label-field">{label}</span><input required={key==="customerName"} type={type} value={quote[key]} onChange={(event)=>setQuote({...quote,[key]:event.target.value})} className="input-field"/></label>)}<label className="sm:col-span-2 lg:col-span-3"><span className="label-field">Terms</span><textarea rows="3" value={quote.terms} onChange={(event)=>setQuote({...quote,terms:event.target.value})} className="input-field"/></label><button disabled={busy} className="btn-primary">Create Quotation</button></form></section>

   <section id="documents" className="mt-10"><h2 className="font-display text-2xl text-[#173c34]">My Quotations</h2><div className="mt-4 grid gap-4">{data.quotations.map((item)=><article key={item.id} className="rounded-2xl bg-white p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><strong className="font-mono text-sm">{item.reference}</strong><h3 className="mt-2 font-display text-xl text-[#173c34]">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.customer_name} · {item.destination||"—"} · <span className="capitalize">{item.status}</span></p><p className="mt-2 text-sm">Total agent cost: <strong>INR {Number(item.agent_cost||0).toLocaleString("en-IN")}</strong> · Customer total: <strong>INR {Number(item.total||0).toLocaleString("en-IN")}</strong></p></div><div className="flex flex-wrap items-start gap-2"><button onClick={()=>setViewing(viewing===item.id?null:item.id)} className="btn-secondary">View Quotation</button><button disabled={busy} onClick={()=>downloadQuote(item)} className="btn-secondary"><FileText size={14}/>Download PDF</button><button disabled={busy} onClick={()=>quoteAction(item.id,"request_revision")} className="btn-secondary">Request Revision</button><button disabled={busy} onClick={()=>quoteAction(item.id,"confirm")} className="btn-secondary">Confirm</button><button disabled={busy} onClick={()=>quoteAction(item.id,"share")} className="btn-primary">Share with Customer</button></div></div>{viewing===item.id&&<div className="mt-5 border-t pt-4 text-sm"><p>Travel: {item.travel_start||"—"} · {item.traveller_count} pax · Markup {item.agent_markup_percent||0}%</p><ul className="mt-2 list-disc pl-5">{(item.lines||[]).map((line)=><li key={line.id||line.description}>{line.description} — INR {Number(line.unit_price).toLocaleString("en-IN")}</li>)}</ul></div>}</article>)}{!data.quotations.length&&<p className="rounded-2xl bg-white p-6 text-slate-400">No partner quotations yet.</p>}</div></section>

   <section id="bookings" className="mt-10"><h2 className="font-display text-2xl text-[#173c34]">My Bookings & Documents</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.bookings.map((booking)=><article key={booking.id} className="rounded-2xl bg-white p-5"><strong>{booking.package?.title}</strong><p className="mt-1 text-sm">{booking.reference} · {booking.operational_status}</p><p className="mt-2 text-xs text-slate-500">Documents: {(booking.documents||[]).map((document)=>document.document_type).join(", ")||"Not issued yet"}</p></article>)}{!data.bookings.length&&<p className="rounded-2xl bg-white p-6 text-slate-400">No partner bookings yet.</p>}</div></section>

   <section id="support" className="mt-10 rounded-2xl bg-[#173c34] p-6 text-white sm:p-8"><Headphones className="text-orange-300"/><h2 className="mt-4 font-display text-3xl">B2B Support</h2><div className="mt-5 flex flex-wrap gap-3"><a href={`https://wa.me/${whatsapp}?text=${encodeURIComponent("Hi NaysTrip, I need B2B support.")}`} target="_blank" rel="noreferrer" className="btn-primary"><MessageCircle size={16}/>WhatsApp</a><a href={`tel:+${supportPhone}`} className="border border-white/30 px-5 py-3 text-sm font-bold">Call B2B Support</a></div></section>
  </div>
 </main>
}
