import PartnerWallet from "../components/shared/PartnerWallet";
import PartnerProfile from "../components/shared/PartnerProfile";
import PartnerDeals from "../components/shared/PartnerDeals";
import EnquiryDetails from "../components/shared/EnquiryDetails";
import {downloadStoredDocument} from "../utils/portal";
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { BadgeCheck, FileText, Headphones, LogOut, Mail, MessageCircle, Plus, WalletCards } from "lucide-react";
import BrandLogo from "../components/branding/BrandLogo";
import { LoadError, PageLoader } from "../components/shared/Loading";
import { getToken, portalFetch, sessionKey } from "../utils/portal";

const requirementOptions=["Hotel","Meals","Transfer","Sightseeing","Adventure Activities","Flight"];
const blankEnquiry={packageId:"",customerName:"",customerPhone:"",customerEmail:"",destination:"",travelDate:"",adults:2,children:0,rooms:1,requirements:["Hotel","Transfer"],notes:""};
const blankQuote={enquiryId:"",packageId:"",customerName:"",customerEmail:"",customerPhone:"",title:"",markupType:"percentage",markupValue:10,validUntil:"",terms:""};
const blankSupport={subject:"",reference:"",message:""};
const decodePayload=(value)=>{if(!value)return{};if(typeof value==="object")return value;try{return JSON.parse(value)}catch{return{}}};
const inr=(value)=>value===null||value===undefined||!Number.isFinite(Number(value))?"On request":`INR ${Number(value).toLocaleString("en-IN")}`;

export default function B2BDashboard(){
 const navigate=useNavigate();const [data,setData]=useState(null);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [enquiry,setEnquiry]=useState(blankEnquiry);const [quote,setQuote]=useState(blankQuote);const [support,setSupport]=useState(blankSupport);
 const [shareUrl,setShareUrl]=useState("");
 const [selected,setSelected]=useState(null),[followUp,setFollowUp]=useState(false),[filters,setFilters]=useState({search:"",status:"",date:""}),[rateMarkup,setRateMarkup]=useState({type:"percentage",value:10});
 const loaded=Boolean(data);
 useEffect(()=>{const scroll=()=>{const id=window.location.hash.slice(1);if(id)document.getElementById(id)?.scrollIntoView()};if(loaded)scroll();window.addEventListener("hashchange",scroll);return()=>window.removeEventListener("hashchange",scroll)},[loaded]);
 const load=()=>portalFetch("/api/b2b/dashboard",{},"agent").then((result)=>{setData(result);setQuote((current)=>({...current,markupValue:current.markupValue??result.defaultMarkupPercent}))});
 useEffect(()=>{if(!getToken("agent"))navigate("/b2b/login?returnTo=/b2b/dashboard");else load().catch((err)=>setError(err.message))},[navigate]);
 const summaries=useMemo(()=>data?[["New Enquiries",data.enquiries.filter((item)=>item.status==="new").length],["Open Enquiries",data.enquiries.filter((item)=>!["converted","lost","closed"].includes(item.status)).length],["Quotations Pending",data.quotations.filter((item)=>["draft","sent"].includes(item.status)).length],["Confirmed Bookings",data.bookings.filter((item)=>["confirmed","fully_paid","completed"].includes(item.operational_status)).length],["Payment Due",data.bookings.filter((item)=>Number(item.balance_due)>0).length],["Upcoming Trips",data.bookings.filter((item)=>item.travel_date&&new Date(`${item.travel_date}T23:59:59`)>=new Date()&&!['cancelled','completed'].includes(item.operational_status)).length]]:[],[data]);
 const quoteByEnquiry=useMemo(()=>new Map([...(data?.quotations||[])].reverse().map((item)=>[item.inquiry_id,item])),[data]);
 const act=async(body,success)=>{setBusy(true);setError("");setMessage("");try{const result=await portalFetch("/api/b2b/dashboard",{method:"POST",body:JSON.stringify(body)},"agent");setMessage(typeof success==="function"?success(result):success);await load();return result}catch(err){setError(err.message);return null}finally{setBusy(false)}};
 const preparePackage=(pkg,quotation=false)=>{setQuote(current=>({...current,markupType:rateMarkup.type,markupValue:rateMarkup.value}));setEnquiry({...blankEnquiry,packageId:pkg.id,destination:(pkg.destination_names||[]).join(", ")});setMessage(quotation?"Package selected. Submit the linked enquiry, then generate its quotation.":"Package details have been added to the enquiry.");document.querySelector("#new-enquiry")?.scrollIntoView({behavior:"smooth"})};
 const createEnquiry=async(event)=>{event.preventDefault();const result=await act({action:"create_enquiry",...enquiry},(value)=>`Enquiry ${value.enquiry.id} created.`);if(result){setQuote((current)=>({...current,enquiryId:result.enquiry.id,packageId:enquiry.packageId,customerName:enquiry.customerName,customerEmail:enquiry.customerEmail,customerPhone:enquiry.customerPhone}));setEnquiry(blankEnquiry)}};
 const selectEnquiry=(id)=>{const item=data.enquiries.find((row)=>row.id===id),payload=decodePayload(item?.payload);setQuote((current)=>({...current,enquiryId:id,packageId:item?.package_id||"",customerName:item?.name||"",customerEmail:item?.email||"",customerPhone:item?.phone||"",title:item?.package?.title||`Quotation for ${item?.destination||""}`}));if(payload.rooms)setMessage(`Quotation will use ${payload.pax} travellers and ${payload.rooms} room(s) from ${id}.`)};
 const createQuote=async(event)=>{event.preventDefault();const result=await act({action:"create_quotation",...quote},(value)=>`Quotation ${value.quotation.reference} created.`);if(result)setQuote({...blankQuote,markupValue:data.defaultMarkupPercent})};
 const quoteAction=async(item,operation)=>{let notes="";if(operation==="request_revision"){notes=window.prompt("Describe the changes you need in this quotation:");if(!notes?.trim())return}if(operation==="confirm"&&!window.confirm("Confirm this quotation? A booking and payment will be arranged separately."))return;const result=await act({action:"quotation_action",id:item.id,operation,notes},operation==="share"||operation==="email"?(value)=>operation==="email"?"Quotation emailed securely.":`Secure customer link ready: ${value.url}`:`Quotation ${operation.replace("_"," ")} completed.`);if(operation==="share"&&result?.url){setShareUrl(result.url);try{await navigator.clipboard?.writeText(result.url)}catch{}}};
 const whatsappQuote=async(item)=>{const result=await act({action:"quotation_action",id:item.id,operation:"share"},"WhatsApp sharing link is ready. Open the customer sharing link to continue.");if(result?.url)setShareUrl(`https://wa.me/${String(item.customer_phone||"").replace(/\D/g,"")}?text=${encodeURIComponent(`NaysTrip quotation ${item.reference}: ${result.url}`)}`)};
 const downloadQuote=async(item,format="pdf",preview=false)=>{const previewWindow=preview?window.open("about:blank","_blank"):null;setBusy(true);try{const response=await fetch(`/api/documents/quotation?id=${encodeURIComponent(item.id)}&format=${format}`,{headers:{Authorization:`Bearer ${getToken("agent")}`}});if(!response.ok){previewWindow?.close();throw new Error((await response.json()).error||"Download failed")}const url=URL.createObjectURL(await response.blob()),anchor=document.createElement("a");if(preview){if(previewWindow){previewWindow.opener=null;previewWindow.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)}else{URL.revokeObjectURL(url);throw new Error("Allow pop-ups to view the quotation")};return}anchor.href=url;anchor.download=`${item.reference}.${format}`;anchor.click();URL.revokeObjectURL(url)}catch(err){setError(err.message)}finally{setBusy(false)}};
 const submitSupport=async(event)=>{event.preventDefault();const result=await act({action:"create_support",...support},(value)=>`Support request ${value.enquiry.id} submitted.`);if(result)setSupport(blankSupport)};
 const logout=()=>{sessionStorage.removeItem(sessionKey("agent"));navigate("/b2b/login")};
 if(!data)return error?<LoadError message={error} onRetry={()=>{setError("");load().catch((err)=>setError(err.message))}} loginTo="/b2b/login"/>:<PageLoader full label="Loading partner workspace…"/>;
 const filteredEnquiries=data.enquiries.filter(item=>(!filters.status||item.status===filters.status)&&(!filters.date||decodePayload(item.payload).travelDate===filters.date)&&(!filters.search||[item.id,item.name,item.destination,item.agent_id,decodePayload(item.payload).reference].join(" ").toLowerCase().includes(filters.search.toLowerCase())));
 const filteredBookings=data.bookings.filter(item=>(!filters.status||item.operational_status===filters.status)&&(!filters.date||item.travel_date===filters.date)&&(!filters.search||[item.reference,item.id,item.package?.title,data.agent.id].join(" ").toLowerCase().includes(filters.search.toLowerCase())));
 const selling=(pkg)=>{const v=Number(rateMarkup.value),net=Number(pkg.netRate);return pkg.netRate===null?null:!Number.isFinite(v)||v<0||(rateMarkup.type==="percentage"&&v>100)?null:Math.round((net+(rateMarkup.type==="fixed"?v:net*v/100))*100)/100};
 const supportPhone=String(data.support.phone||"").replace(/\D/g,""),whatsapp=String(data.support.whatsapp||"").replace(/\D/g,"");
 return <main className="min-h-screen bg-[#f5f3ed] text-slate-800 [&_section]:min-w-0 [&_section[id]]:scroll-mt-64 sm:[&_section[id]]:scroll-mt-44">
  <header className="sticky top-0 z-30 border-b bg-white"><div className="container-lg flex min-h-20 flex-wrap items-center justify-between gap-3 py-2"><Link to="/"><BrandLogo className="h-16"/></Link><nav className="flex max-w-full gap-4 overflow-x-auto text-sm font-bold"><a href="#dashboard">Dashboard</a><a href="#enquiries">Enquiries</a><a href="#bookings">Bookings</a><a href="#rates">Rates</a><a href="#booking-documents">Documents</a><a href="#payments">Payments</a><a href="#support">Support</a></nav><button onClick={logout} className="btn-secondary"><LogOut size={15}/>Logout</button></div></header>
  <div id="dashboard" className="container-lg pb-24 pt-8 sm:pt-10"><p className="eyebrow">B2B PARTNER PORTAL</p><div className="flex flex-wrap items-center gap-3"><h1 className="mt-2 font-display text-3xl text-[#173c34] sm:text-5xl">Welcome, {data.agent.business_name}</h1><span className="mt-2 inline-flex items-center gap-1 rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold capitalize text-emerald-800"><BadgeCheck size={14}/>{data.agent.verification_status} Partner</span></div>
   {error&&<p role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{message&&<p role="status" className="mt-5 break-words rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{message}</p>}
   {shareUrl&&<a className="btn-primary mt-3" href={shareUrl} target="_blank" rel="noopener noreferrer">Open customer sharing link</a>}
   <section className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-6">{summaries.map(([label,value])=><article key={label} className="rounded-2xl bg-white p-5 shadow-sm"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</span><strong className="mt-3 block text-3xl text-[#173c34]">{value}</strong></article>)}</section>
   <div className="mt-6 flex flex-wrap gap-3"><a href="#new-enquiry" className="btn-primary"><Plus size={16}/>Create New Enquiry</a><a href="#rates" className="btn-secondary"><WalletCards size={16}/>View B2B Rates</a><a href="#documents" className="btn-secondary">My Quotations</a><a href="#booking-documents" className="btn-secondary">Documents</a><a href="#profile" className="btn-secondary">My Profile</a><a href="#bookings" className="btn-secondary">My Bookings</a></div>

   <div className="mt-6 grid gap-3 sm:grid-cols-3"><label><span className="label-field">Search enquiries / bookings</span><input className="input-field" placeholder="Destination, Agent ID, Booking ID, client" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><label><span className="label-field">Status</span><select className="input-field" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{[...new Set([...data.enquiries.map(i=>i.status),...data.bookings.map(i=>i.operational_status)])].map(v=><option key={v}>{v}</option>)}</select></label><label><span className="label-field">Travel date</span><input className="input-field" type="date" value={filters.date} onChange={e=>setFilters({...filters,date:e.target.value})}/></label><button className="btn-secondary" onClick={()=>setFilters({search:"",status:"",date:""})}>Clear filters</button></div>
   <section id="enquiries" className="mt-10"><p className="mb-2 text-xs text-slate-500">Latest 100 enquiries and bookings. Filters apply to these records.</p><h2 className="font-display text-2xl text-[#173c34]">Recent Enquiries</h2><div className="mt-4 overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-400"><th className="p-4">Enquiry ID</th><th className="p-4">Client</th><th className="p-4">Destination</th><th className="p-4">Travel Date</th><th className="p-4">Pax</th><th className="p-4">Value</th><th className="p-4">Status</th><th className="p-4">Action</th><th className="p-4">View</th><th className="p-4">Follow Up</th></tr></thead><tbody>{filteredEnquiries.map((item)=>{const payload=decodePayload(item.payload),quotation=quoteByEnquiry.get(item.id);return <tr key={item.id} className="border-b"><td className="p-4 font-mono text-xs">{item.id}</td><td className="p-4 font-bold">{item.name}</td><td className="p-4">{item.destination}</td><td className="p-4">{payload.travelDate||"—"}</td><td className="p-4">{payload.pax||"—"}</td><td className="p-4">{quotation?inr(quotation.total):"—"}</td><td className="p-4 capitalize">{item.status}</td><td className="p-4"><button onClick={()=>{selectEnquiry(item.id);document.querySelector('#create-quotation')?.scrollIntoView({behavior:'smooth'})}} className="text-xs font-bold text-orange-600">{quotation?"View / new quotation":"Create quotation"}</button></td><td className="p-4"><button className="btn-secondary" onClick={()=>{setSelected(item.id);setFollowUp(false)}}>View</button></td><td className="p-4"><button className="btn-secondary" onClick={()=>{setSelected(item.id);setFollowUp(true)}}>Follow Up</button></td></tr>})}{!filteredEnquiries.length&&<tr><td colSpan="10" className="p-8 text-center text-slate-400">No enquiries yet.</td></tr>}</tbody></table></div></section>

   {selected&&data.enquiries.find(i=>i.id===selected)&&<EnquiryDetails key={selected+followUp} item={data.enquiries.find(i=>i.id===selected)} agent={data.agent} quotation={quoteByEnquiry.get(selected)} busy={busy} followUp={followUp} onClose={()=>setSelected(null)} onSave={body=>act({action:"follow_up",...body},"Follow-up saved.")}/>}
   <section id="new-enquiry" className="mt-10 rounded-2xl bg-white p-5 sm:p-7"><h2 className="font-display text-2xl text-[#173c34]">+ Create New Enquiry</h2>{enquiry.packageId&&<p className="mt-3 rounded-xl bg-orange-50 p-3 text-sm">Linked package: <strong>{data.rates.find((item)=>item.id===enquiry.packageId)?.title}</strong></p>}<form onSubmit={createEnquiry} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["customerName","Customer Name","text"],["customerPhone","Mobile","tel"],["customerEmail","Email","email"],["destination","Destination","text"],["travelDate","Travel Date","date"],["adults","Adults","number"],["children","Children","number"],["rooms","Rooms","number"]].map(([key,label,type])=><label key={key}><span className="label-field">{label}</span><input required={["customerName","customerPhone","destination","travelDate","adults","rooms"].includes(key)} min={type==="number"?0:undefined} type={type} value={enquiry[key]} onChange={(event)=>setEnquiry({...enquiry,[key]:event.target.value})} className="input-field"/></label>)}<fieldset className="sm:col-span-2 lg:col-span-3"><legend className="label-field">Requirements</legend><div className="flex flex-wrap gap-4">{requirementOptions.map((item)=><label key={item} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enquiry.requirements.includes(item)} onChange={(event)=>setEnquiry({...enquiry,requirements:event.target.checked?[...enquiry.requirements,item]:enquiry.requirements.filter((value)=>value!==item)})}/>{item}</label>)}</div></fieldset><label className="sm:col-span-2 lg:col-span-3"><span className="label-field">Notes / special requirements</span><textarea rows="3" value={enquiry.notes} onChange={(event)=>setEnquiry({...enquiry,notes:event.target.value})} className="input-field"/></label><button disabled={busy} className="btn-primary">{busy?"Saving…":"Submit Enquiry"}</button></form></section>

   <section id="rates" className="mt-10"><div className="mb-4 flex flex-wrap items-end gap-3"><label><span className="label-field">Rate markup type</span><select className="input-field" value={rateMarkup.type} onChange={e=>setRateMarkup({...rateMarkup,type:e.target.value})}><option value="percentage">Percentage</option><option value="fixed">Fixed INR</option></select></label><label><span className="label-field">Rate markup value</span><input className="input-field" type="number" min="0" max={rateMarkup.type==="percentage"?100:undefined} step="0.01" value={rateMarkup.value} onChange={e=>setRateMarkup({...rateMarkup,value:e.target.value})}/></label><button className="btn-secondary" onClick={()=>setRateMarkup({type:"percentage",value:10})}>Apply 10%</button></div><div><p className="eyebrow">B2B Packages & Rates</p><h2 className="mt-2 font-display text-3xl text-[#173c34]">Published packages for approved partners</h2></div><div className="mt-4 overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[1180px] text-sm"><thead><tr className="border-b text-left"><th className="p-4">Package</th><th className="p-4">Destination</th><th className="p-4">Duration</th><th className="p-4">B2C Price</th><th className="p-4">B2B Net Rate</th><th className="p-4">Agent Markup</th><th className="p-4">Selling Price</th><th className="p-4">Validity</th><th className="p-4">Action</th></tr></thead><tbody>{data.rates.map((pkg)=><tr key={pkg.id} className="border-b align-top"><td className="p-4 font-bold">{pkg.title}<span className="mt-1 block text-[10px] font-normal uppercase text-slate-400">{pkg.rateSource==="configured_b2b"?"Configured B2B rate":"Public-price fallback"}</span></td><td className="p-4">{pkg.destination_names?.join(", ")||"—"}</td><td className="p-4">{pkg.nights}N/{pkg.days}D</td><td className="p-4">{inr(pkg.publicPrice)}</td><td className="p-4 font-bold text-emerald-700">{inr(pkg.netRate)}</td><td className="p-4">{rateMarkup.type==="percentage"?rateMarkup.value+"%":inr(rateMarkup.value)}</td><td className="p-4">{inr(selling(pkg))}</td><td className="p-4">{pkg.validFrom||pkg.validUntil?`${pkg.validFrom||"Open"} to ${pkg.validUntil||"Open"}`:"Not restricted"}</td><td className="p-4"><div className="flex flex-wrap gap-2"><Link to={`/tours/${pkg.slug}`} className="btn-secondary px-3 py-2">View</Link><button onClick={()=>preparePackage(pkg)} className="btn-secondary px-3 py-2">Enquire</button><button disabled={pkg.netRate===null} onClick={()=>preparePackage(pkg,true)} className="btn-primary px-3 py-2">Quotation</button><a href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(`Please share B2B details for ${pkg.title}.`)}`} target="_blank" rel="noreferrer" className="btn-secondary px-3 py-2">WhatsApp</a></div></td></tr>)}{!data.rates.length&&<tr><td colSpan="9" className="p-8 text-center text-slate-400">No published packages are currently available.</td></tr>}</tbody></table></div></section>

   <section id="create-quotation" className="mt-10 rounded-2xl bg-white p-5 sm:p-7"><h2 className="font-display text-2xl text-[#173c34]">Create Customer Quotation</h2><p className="mt-2 text-sm text-slate-500">Customer documents never expose the private agent cost.</p><form onSubmit={createQuote} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label><span className="label-field">Enquiry</span><select required value={quote.enquiryId} onChange={(event)=>selectEnquiry(event.target.value)} className="input-field"><option value="">Select enquiry</option>{data.enquiries.filter((item)=>item.enquiry_source!=="support").map((item)=><option key={item.id} value={item.id}>{item.id} · {item.name} · {item.destination}</option>)}</select></label><label><span className="label-field">Package / Rate</span><select required value={quote.packageId} onChange={(event)=>setQuote({...quote,packageId:event.target.value})} className="input-field"><option value="">Select package</option>{data.rates.filter((pkg)=>pkg.netRate!==null).map((pkg)=><option key={pkg.id} value={pkg.id}>{pkg.title} · {inr(pkg.netRate)}</option>)}</select></label><label><span className="label-field">Markup type</span><select value={quote.markupType} onChange={(event)=>setQuote({...quote,markupType:event.target.value})} className="input-field"><option value="percentage">Percentage (%)</option><option value="fixed">Fixed amount (INR)</option></select></label><label><span className="label-field">Markup value</span><input required type="number" min="0" step="0.1" value={quote.markupValue} onChange={(event)=>setQuote({...quote,markupValue:event.target.value})} className="input-field"/></label>{[["couponCode","Coupon code (optional)","text"],["customerName","Customer Name","text"],["customerEmail","Customer Email","email"],["customerPhone","Customer Mobile","tel"],["title","Quotation Title","text"],["validUntil","Valid Until","date"]].map(([key,label,type])=><label key={key}><span className="label-field">{label}</span><input required={key==="customerName"} type={type} value={quote[key]||""} onChange={(event)=>setQuote({...quote,[key]:event.target.value})} className="input-field"/></label>)}<label className="sm:col-span-2 lg:col-span-3"><span className="label-field">Terms</span><textarea rows="3" value={quote.terms} onChange={(event)=>setQuote({...quote,terms:event.target.value})} className="input-field"/></label><button disabled={busy} className="btn-primary">Submit & Generate Quotation</button></form></section>

   <section id="documents" className="mt-10"><h2 className="font-display text-2xl text-[#173c34]">My Quotations</h2><div className="mt-4 grid gap-4">{data.quotations.map((item)=><article key={item.id} className="rounded-2xl bg-white p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><strong className="font-mono text-sm">{item.reference}</strong><h3 className="mt-2 font-display text-xl text-[#173c34]">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.customer_name} · {item.destination||"—"} · {item.travel_start||"—"} · <span className="capitalize">{item.status}</span> · {new Date(item.created_at).toLocaleDateString("en-IN")}</p><p className="mt-2 text-sm">Total Agent Cost: <strong>{inr(item.agent_cost)}</strong> · Selling price: <strong>{inr(item.total)}</strong></p></div><div className="flex flex-wrap items-start gap-2"><button disabled={busy} onClick={()=>downloadQuote(item,"pdf",true)} className="btn-secondary">View Quotation</button><button disabled={busy} onClick={()=>downloadQuote(item)} className="btn-secondary"><FileText size={14}/>PDF</button><button disabled={busy} onClick={()=>downloadQuote(item,"docx")} className="btn-secondary"><FileText size={14}/>Word</button><button disabled={busy} onClick={()=>quoteAction(item,"request_revision")} className="btn-secondary">Request Revision</button><button disabled={busy} onClick={()=>quoteAction(item,"confirm")} className="btn-secondary">Confirm</button><button disabled={busy} onClick={()=>quoteAction(item,"email")} className="btn-secondary"><Mail size={14}/>Email</button><button disabled={busy||!item.customer_phone} onClick={()=>whatsappQuote(item)} className="btn-secondary"><MessageCircle size={14}/>WhatsApp</button><button disabled={busy} onClick={()=>quoteAction(item,"share")} className="btn-primary">Share with Customer</button></div></div></article>)}{!data.quotations.length&&<p className="rounded-2xl bg-white p-6 text-slate-400">No partner quotations yet.</p>}</div></section>

   <section id="bookings" className="mt-10"><h2 className="font-display text-2xl text-[#173c34]">My Bookings & Documents</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{filteredBookings.map((booking)=><article key={booking.id} className="rounded-2xl bg-white p-5"><strong>{booking.package?.title}</strong><p className="mt-1 text-sm">{booking.reference} · {booking.operational_status}</p><p className="mt-2 text-xs text-slate-500">Documents: {(booking.documents||[]).map((document)=>document.document_type).join(", ")||"Not issued yet"}</p></article>)}{!filteredBookings.length&&<p className="rounded-2xl bg-white p-6 text-slate-400">No partner bookings yet.</p>}</div></section>
   <section id="booking-documents" className="mt-10 rounded-2xl bg-white p-5"><h2 className="font-display text-2xl">Documents</h2>{data.bookings.flatMap(b=>(b.documents||[]).map(d=><button key={d.id} className="btn-secondary m-2" onClick={()=>downloadStoredDocument(d.id,b.reference+"-"+d.document_type+".pdf","agent").catch(e=>setError(e.message))}>{b.reference} · {d.document_type}</button>))}{!data.bookings.some(b=>b.documents?.length)&&<p className="mt-3 text-slate-500">No issued documents yet.</p>}</section>
   <section id="payments" className="mt-10 rounded-2xl bg-white p-5 sm:p-7"><h2 className="font-display text-2xl text-[#173c34]">Payments</h2><PartnerWallet/><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">Booking</th><th className="p-3">Total</th><th className="p-3">Paid</th><th className="p-3">Due</th><th className="p-3">State</th></tr></thead><tbody>{data.bookings.map((item)=><tr key={item.id} className="border-b"><td className="p-3">{item.reference}</td><td className="p-3">{inr(item.total)}</td><td className="p-3">{inr(item.amount_paid)}</td><td className="p-3">{inr(item.balance_due)}</td><td className="p-3 capitalize">{item.payment_state}</td></tr>)}{!data.bookings.length&&<tr><td colSpan="5" className="p-6 text-center text-slate-400">No payment history.</td></tr>}</tbody></table></div></section>
   <PartnerDeals/>
   <section className="mt-10 grid gap-5 lg:grid-cols-2"><PartnerProfile agent={data.agent} onSaved={load}/>
   <article id="support" className="rounded-2xl bg-[#173c34] p-6 text-white"><Headphones className="text-orange-300"/><h2 className="mt-3 font-display text-2xl">B2B Assistance</h2><form onSubmit={submitSupport} className="mt-4 grid gap-3"><input aria-label="Assistance subject" required value={support.subject} onChange={(e)=>setSupport({...support,subject:e.target.value})} placeholder="Subject / category" className="input-field text-slate-900"/><input aria-label="Booking or enquiry reference" value={support.reference} onChange={(e)=>setSupport({...support,reference:e.target.value})} placeholder="Booking / enquiry reference (optional)" className="input-field text-slate-900"/><textarea aria-label="Assistance message" required rows="4" value={support.message} onChange={(e)=>setSupport({...support,message:e.target.value})} placeholder="How can we help?" className="input-field text-slate-900"/><button disabled={busy} className="btn-primary">Submit Assistance Request</button></form><div className="mt-4 flex gap-3"><a href={`https://wa.me/${whatsapp}?text=${encodeURIComponent("Hi NaysTrip, I need B2B support.")}`} target="_blank" rel="noreferrer" className="text-sm font-bold text-orange-300">WhatsApp</a><a href={`tel:+${supportPhone}`} className="text-sm font-bold">Call support</a></div></article></section>
  </div>
 </main>
}
