import {googleBusinessUrl} from "../data/googleReviews";
import MonthlyPicks from "../components/home/MonthlyPicks";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Building2, CalendarDays, Car, Check, ChevronDown, Compass, Headphones, Mail, MapPin, Mountain, Phone, Plane, Search, ShieldCheck, SlidersHorizontal, Sparkles } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import Seo from "../components/shared/Seo";
import PackageCard from "../components/tours/PackageCard";
import SmartImage from "../components/shared/SmartImage";
import { blogs } from "../data/content";
import { destinations } from "../data/destinations";
import { tours } from "../data/tours";
import { treks } from "../data/treksExpeditions";
import usePublicPackages from "../hooks/usePublicPackages";
import { imageFallbackFor } from "../data/imageFallbacks";
import { savePackageLead, saveQuickLead } from "../utils/storage";
import { getPublicStories } from "../utils/storage";
import { StarRating } from "../components/shared/Bits";
import { getSiteSettings, loadSiteSettings } from "../data/siteConfig";
import {ReviewsSection} from "./Reviews";

const heroSlides = [
  { key:"india", image:treks[0].image, kicker:"Tailor-made India", title:"Trips Designed Around You.", copy:"Custom tours designed around you.", cta:"Plan My Trip", to:"/custom-trip", position:"center 48%" },
  { key:"konkan", image:tours[7].image, kicker:"Coastal Maharashtra", title:"Discover the Konkan Coast", copy:"Beaches • Forts • Food • Experiences", cta:"Explore Konkan", to:"/tours/mumbai-konkan-5-days", position:"center 58%" },
  { key:"himalayas", image:treks[0].image, kicker:"Leisure to adventure", title:"Into the Himalayas", copy:"Treks & expeditions for every level.", cta:"Explore Treks", to:"/treks", position:"center 42%" },
  { key:"groups", image:tours[1].image, kicker:"Groups & MICE", title:"Planning a Group or Corporate Trip?", copy:"Tell us the dates, group size and purpose. We will coordinate the route, stays and transport.", cta:"Get My Free Quote", to:"/custom-trip?tripType=Corporate", position:"center 50%" },
];

const services = [
  [Plane, "Leisure Holidays", "Family • Honeymoon • Weekend • Luxury", "/holidays"],
  [Mountain, "Adventure", "Trekking • Expeditions • Camping • Mountaineering", "/treks"],
  [Building2, "Corporate", "Corporate Tours • MICE • Team Outings", "/corporate-travel"],
  [Compass, "Groups", "Educational • Institutional • Group Tours", "/custom-trip?tripType=School%20or%20college"],
  [ShieldCheck, "B2B DMC", "Hotels • Transfers • Packages • Ground Handling", "/b2b/login"],
];

const faqs = [
  ["Can I customise a published package?", "Yes. Dates, pace, stay category, pickup point and optional services can be adjusted before you approve the final quotation."],
  ["Why do some packages say Price on request?", "It means an online price has not been approved for that route. We first confirm dates, occupancy and live supplier availability, then send a written quote."],
  ["When is online booking available?", "Only when the package is published, has approved pricing and meets its availability rules. The Book now button appears automatically when those checks pass."],
  ["How are cancellations handled?", "The applicable schedule and any disclosed supplier-specific terms are shown before confirmation. You can also review our public Cancellation and Refund policies."],
];


export default function Home() {
  const navigate = useNavigate();
  const { bySlug,packages } = usePublicPackages();
  const [slide, setSlide] = useState(0);
  const [query, setQuery] = useState("");
  const [kind, setKind] = useState("tours");
  const [departures, setDepartures] = useState([]);
  const [quick,setQuick]=useState({destination:"",travelDate:"",guests:"2",phone:""});
  const [quickState,setQuickState]=useState({status:"idle",message:""});
  const [travellerStories,setTravellerStories]=useState([]);
  const [newsletterEmail,setNewsletterEmail]=useState("");
  const [newsletterState,setNewsletterState]=useState({status:"idle",message:""});
  const [settings,setSettings]=useState(getSiteSettings());
  const [plan,setPlan]=useState({name:"",phone:"",email:"",slug:""});
  const [planState,setPlanState]=useState({status:"idle",message:"",pdf:""});
  useEffect(() => {
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduced) return undefined;
    const timer = window.setInterval(() => setSlide((value) => (value + 1) % heroSlides.length), 6500);
    return () => window.clearInterval(timer);
  }, []);
  useEffect(()=>{getPublicStories().then(setTravellerStories).catch(()=>{})},[]);
  useEffect(()=>{loadSiteSettings().then(setSettings).catch(()=>{})},[]);
  useEffect(() => {
    fetch("/api/departures").then((response) => response.ok ? response.json() : { departures: [] }).then((data) => setDepartures((data.departures || []).filter((item) => item.status !== "sold_out").slice(0, 3))).catch(() => setDepartures([]));
  }, []);
  const featured = useMemo(() => [...tours].sort((a, b) => Number(Boolean(bySlug.get(b.slug)?.featured)) - Number(Boolean(bySlug.get(a.slug)?.featured))).slice(0, 6), [bySlug]);
  const submitSearch = (event) => { event.preventDefault(); navigate(`/${kind}?q=${encodeURIComponent(query.trim())}`); };
  const submitQuick=async(event)=>{event.preventDefault();setQuickState({status:"loading",message:""});try{const entry=await saveQuickLead({...quick,source:"Homepage quick quote"});setQuickState({status:"success",message:`Request received · Reference ID: ${entry.id}`});setQuick({destination:"",travelDate:"",guests:"2",phone:""})}catch(error){setQuickState({status:"error",message:error.message})}};
  const submitNewsletter=async(event)=>{event.preventDefault();setNewsletterState({status:"loading",message:""});try{const response=await fetch("/api/newsletter",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:newsletterEmail})});const data=await response.json();if(!response.ok)throw new Error(data.error);setNewsletterEmail("");setNewsletterState({status:"success",message:"You’re subscribed."})}catch(error){setNewsletterState({status:"error",message:error.message})}};
  const submitPlan=async(event)=>{event.preventDefault();const tour=tours.find((item)=>item.slug===plan.slug);if(!tour)return;setPlanState({status:"loading",message:"",pdf:""});try{const entry=await savePackageLead({name:plan.name,phone:plan.phone,email:plan.email,destination:tour.destinations.join(", "),packageTitle:tour.title,packageSlug:tour.slug,source:"Homepage sample itinerary"});setPlanState({status:"success",message:`Saved · Reference ID: ${entry.id}`,pdf:`/api/documents/itinerary?slug=${encodeURIComponent(tour.slug)}&reference=${encodeURIComponent(entry.id)}`});setPlan({name:"",phone:"",email:"",slug:""})}catch(error){setPlanState({status:"error",message:error.message,pdf:""})}};
  const verifiedTrust=[settings.trustMetrics?.packageCount&&[`${settings.trustMetrics.packageCount} Tour Packages`,"Verified catalogue count"],settings.trustMetrics?.googleRating&&[`Google rating ${settings.trustMetrics.googleRating}`,settings.trustMetrics.googleReviewCount?`${settings.trustMetrics.googleReviewCount} reviews`:"Verified Google rating",settings.trustMetrics.googleReviewUrl],settings.trustMetrics?.happyTravellers&&[`${settings.trustMetrics.happyTravellers} Happy Travellers`,"Owner-verified traveller count"],settings.trustMetrics?.support24x7&&["24/7 Support","Owner-confirmed availability"],settings.trustMetrics?.msmeRegistration&&["MSME Registered",settings.trustMetrics.msmeRegistration],settings.trustMetrics?.nidhiRegistration&&["NIDHI Registered",settings.trustMetrics.nidhiRegistration]].filter(Boolean);
  const active = heroSlides[slide];
  return <>
    <Seo title="NaysTrip & Treks | Tailor-made Tours, Treks & Holidays" description="Plan Maharashtra tours, treks, expeditions, corporate travel and tailor-made holidays with a Navi Mumbai-based travel team." />
    <section className="home-hero relative overflow-hidden bg-[#102f29] text-white">
      {heroSlides.map((item, index) => <SmartImage key={item.key} src={item.image} context={item.kicker} alt={index === slide ? `${item.kicker} travel experience` : ""} wrapperClassName={`absolute inset-0 transition duration-1000 ${index === slide ? "scale-100 opacity-100" : "scale-105 opacity-0"}`} className="object-cover" style={{ objectPosition: item.position }} fetchPriority={index === 0 ? "high" : "auto"} loading={index === 0 ? "eager" : "lazy"}/>) }
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,31,26,.70)_0%,rgba(8,31,26,.36)_50%,rgba(8,31,26,.08)_100%)]" />
      <div className="home-hero__content container-lg relative flex items-center">
        <div className="max-w-4xl">
          <p className="eyebrow !text-orange-300">{active.kicker} · Leisure to Adventure</p>
          <h1 className="home-hero__title mt-4 max-w-4xl font-display">{active.title}</h1>
          <p className="mt-5 max-w-2xl text-base leading-7 text-white/78 sm:mt-7 sm:text-lg">{active.copy}</p>
          <div className="mt-6 flex flex-col gap-3 sm:mt-9 sm:flex-row"><Link to={active.to} className="btn-primary">{active.cta} <ArrowRight size={17}/></Link></div>
          <div className="mt-10 hidden items-center gap-3 sm:flex"><button onClick={() => setSlide((slide - 1 + heroSlides.length) % heroSlides.length)} aria-label="Previous hero slide" className="grid h-11 w-11 place-items-center rounded-full border border-white/30 hover:bg-white/10"><ArrowLeft size={18}/></button><div className="flex gap-2" aria-label={`Slide ${slide+1} of ${heroSlides.length}`}>{heroSlides.map((item,index)=><button type="button" key={item.key} onClick={()=>setSlide(index)} aria-label={`Show slide ${index+1}`} className={`h-2 rounded-full transition-all ${index===slide?"w-6 bg-orange-400":"w-2 bg-white/45"}`}/>)}</div><button onClick={() => setSlide((slide + 1) % heroSlides.length)} aria-label="Next hero slide" className="grid h-11 w-11 place-items-center rounded-full border border-white/30 hover:bg-white/10"><ArrowRight size={18}/></button></div>
        </div>
      </div>
      <form onSubmit={submitSearch} className="absolute inset-x-0 bottom-0 border-t border-white/15 bg-[#102f29]/92 backdrop-blur"><div className="container-lg grid gap-px bg-white/15 sm:grid-cols-[1fr_220px_auto]"><label className="flex items-center gap-3 bg-[#102f29] px-5 py-4"><Search size={21} strokeWidth={2.5} className="shrink-0 text-white"/><span className="sr-only">Search destination</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Where would you like to go?" className="w-full bg-transparent text-sm text-white outline-none placeholder:text-white/50"/></label><label className="relative flex items-center bg-[#102f29] px-5"><Compass size={18} className="mr-3 text-orange-300"/><span className="sr-only">Travel type</span><select value={kind} onChange={(event) => setKind(event.target.value)} className="h-14 w-full appearance-none bg-transparent text-sm font-bold text-white outline-none"><option className="text-slate-900" value="tours">Tour packages</option><option className="text-slate-900" value="treks">Treks</option><option className="text-slate-900" value="expeditions">Expeditions</option></select><ChevronDown size={16}/></label><button className="bg-orange-500 px-8 py-4 text-sm font-extrabold hover:bg-orange-600">Find a journey</button></div></form>
    </section>

    <section className="border-b border-slate-200 bg-[#fffaf2]"><div className="container-lg py-8"><div className="flex flex-wrap items-end justify-between gap-3"><p className="eyebrow">Why Travellers Choose Us</p><Link to="/b2b/login" className="text-sm font-bold text-orange-600">B2B Friendly · Partner registration →</Link></div><div className="mt-5 grid grid-cols-2 gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-3 lg:grid-cols-6">{[[MapPin,"Local Maharashtra experts","Routes planned by a Navi Mumbai-based team"],[SlidersHorizontal,"Custom itineraries","Built around your dates and preferences"],[Headphones,"Dedicated support","Human help throughout your trip"],[ShieldCheck,"Clear terms","Pricing and policies before payment"],[Car,"Verified travel partners","Hotels and transport coordinated with verified partners"],[Building2,"Corporate travel","Group logistics and corporate journeys"]].map(([Icon,title,copy])=><div key={title} className="bg-[#fffaf2] p-5 sm:p-6"><Icon size={20} className="text-orange-600"/><strong className="mt-3 block text-sm text-[#173c34]">{title}</strong><span className="mt-1 block text-xs leading-5 text-slate-500">{copy}</span></div>)}</div></div></section>
    {verifiedTrust.length>0&&<section className="border-b bg-white"><div className="container-lg flex gap-8 overflow-x-auto py-5">{verifiedTrust.map(([title,copy,url])=>{const content=<><strong className="text-sm text-[#173c34]">{title}</strong><span className="mt-1 block text-xs text-slate-500">{copy}</span></>;return url?<a key={title} href={url} target="_blank" rel="noreferrer" className="min-w-[180px] hover:text-orange-600">{content}</a>:<div key={title} className="min-w-[180px]">{content}</div>})}</div></section>}

<section className="bg-[#173c34] py-8 text-white"><div className="container-lg grid grid-cols-2 gap-3 lg:grid-cols-5">{[["10+","Years Experience"],["1000+","Travellers"],["25+","Destinations"],["500+","B2B Partners"]].map(([value,label])=><article key={label} className="rounded-xl border border-white/15 bg-white/5 p-5"><ShieldCheck size={18} className="mb-3 text-orange-300"/><strong className="block text-3xl">{value}</strong><span className="text-sm text-white/80">{label}</span></article>)}<article className="col-span-2 rounded-xl bg-white p-5 text-center text-[#173c34] lg:col-span-1"><div className="text-2xl tracking-widest text-amber-500" aria-label="Five stars">★★★★★</div><strong className="mt-2 block">Google Rating</strong>{(settings.trustMetrics?.googleReviewUrl||googleBusinessUrl)&&<a href={settings.trustMetrics?.googleReviewUrl||googleBusinessUrl} target="_blank" rel="noreferrer" className="mt-2 block text-sm underline">View on Google</a>}</article></div></section>
    <section className="bg-white py-10"><form onSubmit={submitQuick} className="container-lg"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft sm:p-7"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="eyebrow">Quick quote</p><h2 className="mt-2 font-display text-2xl text-[#173c34]">Share the essentials.</h2></div>{quickState.message&&<p role="status" className={`text-sm ${quickState.status==="error"?"text-rose-600":"text-emerald-700"}`}>{quickState.message}</p>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-[1.3fr_1fr_.7fr_1fr_auto]"><label><span className="sr-only">Destination</span><input required value={quick.destination} onChange={(e)=>setQuick({...quick,destination:e.target.value})} placeholder="Destination" className="input-field"/></label><label><span className="sr-only">Travel date</span><input required type="date" value={quick.travelDate} onChange={(e)=>setQuick({...quick,travelDate:e.target.value})} className="input-field"/></label><label><span className="sr-only">Number of guests</span><input required type="number" min="1" max="99" value={quick.guests} onChange={(e)=>setQuick({...quick,guests:e.target.value})} className="input-field"/></label><label className="relative"><Phone size={15} className="absolute left-3 top-3.5 text-slate-400"/><span className="sr-only">Phone number</span><input required pattern="[+0-9][0-9 ()-]{7,20}" value={quick.phone} onChange={(e)=>setQuick({...quick,phone:e.target.value})} placeholder="Phone number" className="input-field pl-9"/></label><button disabled={quickState.status==="loading"} className="btn-primary whitespace-nowrap">{quickState.status==="loading"?"Sending…":"Get Quote in 30 Minutes"}</button></div></div></form></section>

    <section className="py-14 sm:py-20"><div className="container-lg grid gap-5 lg:grid-cols-2"><Link to="/tours/domestic" className="group relative min-h-[340px] overflow-hidden rounded-2xl"><SmartImage src={tours[5].image} context="Domestic India tours" alt="Domestic tours in India" wrapperClassName="absolute inset-0" className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/25 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 text-white sm:p-9"><p className="eyebrow !text-orange-300">Domestic tours</p><h2 className="mt-3 font-display text-4xl">India, one clear route at a time.</h2><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Explore domestic packages <ArrowRight size={16}/></span></div></Link><Link to="/tours/international" className="group relative min-h-[340px] overflow-hidden rounded-2xl"><SmartImage src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?fm=webp&fit=crop&w=1400&q=82" context="International Nepal travel" alt="Forested mountain valley beneath snow-capped peaks" wrapperClassName="absolute inset-0" className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/25 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 text-white sm:p-9"><p className="eyebrow !text-orange-300">International tours</p><h2 className="mt-3 font-display text-4xl">Overseas journeys, quoted honestly.</h2><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Explore supported destinations <ArrowRight size={16}/></span></div></Link></div></section>

    <section className="py-20 sm:py-28"><div className="container-lg flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Real routes</p><h2 className="section-title mt-4">Explore Our Journeys</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Published itineraries from the current NaysTrip catalogue, with Admin-featured packages shown first.</p></div><Link to="/tours" className="inline-flex items-center gap-2 font-bold text-[#173c34]">View all packages <ArrowRight size={17}/></Link></div><div className="container-lg mt-11 grid gap-7 sm:grid-cols-2 xl:grid-cols-3">{featured.map((tour, index) => <PackageCard key={tour.slug} tour={tour} commercial={bySlug.get(tour.slug)} priority={index < 3}/>)}</div></section>

    <MonthlyPicks settings={settings} packages={packages}/>

    <section className="overflow-hidden bg-[#173c34] py-16 text-white sm:py-24"><div className="container-lg"><div className="max-w-3xl"><p className="eyebrow !text-orange-300">Choose your landscape</p><h2 className="mt-4 font-display text-4xl leading-tight sm:text-5xl">Places worth slowing down for.</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{destinations.slice(0, 4).map((destination) => <Link key={destination.slug} to={`/destinations/${destination.slug}`} className="group relative h-[360px] overflow-hidden rounded-2xl sm:h-[390px] lg:h-[380px]"><SmartImage src={imageFallbackFor(destination.name)} context={destination.name} alt={destination.name} wrapperClassName="absolute inset-0" className="object-cover transition duration-700 group-hover:scale-105" loading="lazy"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/5 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-orange-300">{destination.bestTime}</p><h3 className="mt-2 font-display text-3xl">{destination.name}</h3><p className="mt-2 text-sm text-white/70">{destination.tagline}</p></div></Link>)}</div></div></section>

    {departures.length > 0 && <section className="bg-[#fffaf2] py-20 sm:py-24"><div className="container-lg"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">Live availability</p><h2 className="section-title mt-4">Upcoming group departures.</h2></div><Link to="/fixed-departures" className="font-bold text-[#173c34]">See all</Link></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{departures.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-6"><CalendarDays className="text-orange-600"/><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-slate-400">{new Date(`${item.start_date}T00:00:00`).toLocaleDateString("en-IN", { day:"numeric", month:"long", year:"numeric" })}</p><h3 className="mt-2 font-display text-2xl text-[#173c34]">{item.package?.title}</h3><p className="mt-3 text-sm text-slate-500">{item.available_seats} seats available · {item.package?.days} days</p><Link to={`/tours/${item.package?.slug}`} className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-orange-600">View departure <ArrowRight size={15}/></Link></article>)}</div></div></section>}

    <section className="py-20 sm:py-28"><div className="container-lg"><div className="max-w-3xl"><p className="eyebrow">Our Travel Solutions</p><h2 className="section-title mt-4">Travel, Your Way</h2><p className="mt-5 leading-7 text-slate-600">Choose the type of support your journey needs, from a custom holiday to end-to-end group logistics.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-5">{services.map(([Icon,title,copy,to]) => <Link to={to} key={title} className="group bg-white p-6"><Icon className="text-orange-600"/><h3 className="mt-7 font-display text-2xl text-[#173c34]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#173c34]">Explore <ArrowRight size={15} className="transition group-hover:translate-x-1"/></span></Link>)}</div></div></section>

    <section className="bg-[#fff3df] py-20 sm:py-24"><div className="container-lg grid gap-10 lg:grid-cols-2 lg:items-center"><div><Sparkles className="text-orange-600"/><p className="eyebrow mt-5">Made for your people</p><h2 className="section-title mt-4">A trip should fit the travellers, not the template.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Share your dates, starting city, interests, pace and budget. We’ll turn it into a practical route and a clear written quote.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Dates and pace that work", "Stay category you choose", "Clear inclusions and exclusions", "Support before and during travel"].map((item) => <span key={item} className="flex items-center gap-2 text-sm font-semibold text-[#173c34]"><Check size={17} className="text-orange-600"/>{item}</span>)}</div></div><div className="rounded-[2rem] bg-[#173c34] p-8 text-white sm:p-12"><h3 className="font-display text-4xl">Start with the journey in your head.</h3><p className="mt-4 leading-7 text-white/70">No payment, no invented price—just enough information for our team to build the right option.</p><Link to="/custom-trip" className="mt-8 inline-flex items-center gap-2 rounded-full bg-orange-500 px-6 py-4 text-sm font-extrabold">Build my trip <ArrowRight size={16}/></Link></div></div></section>

<section className="py-16"><div className="container-lg"><p className="eyebrow">Traveller Photos</p><h2 className="section-title mt-3">Recent Trips / Experiences</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[...(settings.travellerPhotos||[]).filter(p=>p.active!==false&&p.image),...travellerStories.filter(p=>p.image).map(p=>({...p,caption:[p.name,p.destination].filter(Boolean).join(" · ")}))].map(p=><figure key={p.id} className="overflow-hidden rounded-2xl border bg-white"><img src={p.image} alt={p.caption||"NaysTrip traveller experience"} loading="lazy" className="aspect-[4/3] w-full object-cover"/>{p.caption&&<figcaption className="p-4 text-sm font-medium">{p.caption}</figcaption>}</figure>)}</div>{!(settings.travellerPhotos||[]).some(p=>p.active!==false&&p.image)&&!travellerStories.some(p=>p.image)&&<p className="mt-4 text-slate-500">Traveller experiences will appear here as our team shares them.</p>}</div></section>
    {travellerStories.length > 0 && <section className="py-20"><div className="container-lg"><p className="eyebrow">Traveller stories</p><h2 className="section-title mt-4">Journeys told by the people who took them.</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{travellerStories.slice(0,6).map((story)=><article key={story.id} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3">{story.image&&<img src={story.image} alt="" className="h-11 w-11 rounded-full object-cover" loading="lazy"/>}<div><strong className="block text-sm text-[#173c34]">{story.name}</strong><span className="text-xs text-slate-500">{story.destination}</span></div></div><div className="mt-4"><StarRating rating={Number(story.rating)} size={13} showValue={false}/></div><p className="mt-3 text-sm leading-6 text-slate-600">{story.testimonial}</p></article>)}</div></div></section>}

    <section className="py-20 sm:py-24"><div className="container-lg grid gap-14 lg:grid-cols-2"><div><p className="eyebrow">Travel notes</p><h2 className="section-title mt-4">Useful before you set out.</h2><div className="mt-8 space-y-6">{blogs.slice(0, 3).map((blog) => <Link key={blog.slug} to={`/blog/${blog.slug}`} className="group grid grid-cols-[110px_1fr] gap-5 border-b border-slate-200 pb-6"><img src={blog.image} alt="" className="h-24 w-full rounded-xl object-cover" loading="lazy"/><div><p className="text-xs font-bold uppercase tracking-[.12em] text-orange-600">{blog.category}</p><h3 className="mt-2 font-display text-xl leading-tight text-[#173c34] group-hover:text-orange-600">{blog.title}</h3></div></Link>)}</div></div><div><p className="eyebrow">Good to know</p><h2 className="section-title mt-4">Questions before you book.</h2><div className="mt-8 divide-y divide-slate-200 border-y border-slate-200">{faqs.map(([question,answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-[#173c34]">{question}<ChevronDown size={18} className="transition group-open:rotate-180"/></summary><p className="mt-3 max-w-xl text-sm leading-6 text-slate-600">{answer}</p></details>)}</div><div className="mt-6 flex gap-5 text-sm font-bold"><Link to="/faqs" className="text-orange-600">All FAQs</Link><Link to="/cancellation-policy" className="text-orange-600">Cancellation policy</Link></div></div></div></section>

    <section className="relative overflow-hidden bg-[#102f29] py-20 text-white sm:py-28"><img src={tours[11].image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-20" loading="lazy"/><div className="container-lg relative text-center"><p className="eyebrow !text-orange-300">Ready when you are</p><h2 className="mx-auto mt-4 max-w-4xl font-display text-4xl sm:text-6xl">Your next story needs a starting point.</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-white/70">Browse a ready itinerary or tell us what you want to build from scratch.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/tours" className="btn-primary">Explore packages <ArrowRight size={16}/></Link><Link to="/contact" className="inline-flex items-center justify-center border border-white/35 px-6 py-3.5 text-sm font-bold hover:bg-white hover:text-[#173c34]">Speak to NaysTrip</Link></div></div></section>
    <section className="bg-[#fff3df] py-14 sm:py-20"><div className="container-lg grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">Free planning help</p><h2 className="mt-3 font-display text-3xl text-[#173c34] sm:text-4xl">Download a real sample itinerary.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Choose an existing trip and receive its current NaysTrip itinerary PDF after your request is saved.</p></div><form onSubmit={submitPlan} className="grid gap-3 sm:grid-cols-2"><input required placeholder="Name" value={plan.name} onChange={(event)=>setPlan({...plan,name:event.target.value})} className="input-field"/><input required placeholder="Phone" value={plan.phone} onChange={(event)=>setPlan({...plan,phone:event.target.value})} className="input-field"/><input required type="email" placeholder="Email" value={plan.email} onChange={(event)=>setPlan({...plan,email:event.target.value})} className="input-field"/><select required value={plan.slug} onChange={(event)=>setPlan({...plan,slug:event.target.value})} className="input-field"><option value="">Destination / trip</option>{tours.map((tour)=><option key={tour.slug} value={tour.slug}>{tour.title}</option>)}</select><button disabled={planState.status==="loading"} className="btn-primary">{planState.status==="loading"?"Saving…":"Get Free Trip Plan"}</button>{planState.pdf&&<a href={planState.pdf} className="btn-secondary" target="_blank" rel="noreferrer">Download itinerary PDF</a>}{planState.message&&<p role="status" className={`text-sm sm:col-span-2 ${planState.status==="error"?"text-rose-600":"text-emerald-700"}`}>{planState.message}</p>}</form></div></section>

    <section className="bg-[#173c34] py-14 text-white"><div className="container-lg grid gap-6 lg:grid-cols-[1fr_520px] lg:items-center"><div><Mail className="text-orange-300"/><h2 className="mt-4 font-display text-3xl">Travel notes, when there is something useful to share.</h2><p className="mt-2 text-sm text-white/65">Subscribe with your email. Signups are stored securely and visible to Admin.</p></div><form onSubmit={submitNewsletter} className="flex flex-col gap-3 sm:flex-row"><label className="flex-1"><span className="sr-only">Newsletter email</span><input required type="email" value={newsletterEmail} onChange={(event)=>setNewsletterEmail(event.target.value)} placeholder="Email address" className="h-12 w-full bg-white px-4 text-sm text-slate-900 outline-none"/></label><button disabled={newsletterState.status==="loading"} className="h-12 bg-orange-500 px-6 text-sm font-extrabold hover:bg-orange-600 disabled:opacity-60">{newsletterState.status==="loading"?"Saving…":"Subscribe"}</button></form>{newsletterState.message&&<p role="status" className={`text-sm lg:col-start-2 ${newsletterState.status==="error"?"text-orange-200":"text-emerald-200"}`}>{newsletterState.message}</p>}</div></section>
    <ReviewsSection/>
  </>;
}
