import {Link} from "react-router-dom";
import {ExternalLink} from "lucide-react";
import Seo from "../components/shared/Seo";
import {StarRating} from "../components/shared/Bits";
import {featuredGoogleReviews,googleBusinessUrl,googleReviews} from "../data/googleReviews";

function ReviewCard({review}){return <article className="flex h-full flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#173c34] text-sm font-extrabold text-white">{review.name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}</div><span className="text-xs font-bold text-[#4285f4]">Google Review</span></div><h3 className="mt-4 font-bold text-[#173c34]">{review.name}</h3><div className="mt-2"><StarRating rating={review.rating} size={14} showValue={false}/></div><p className="mt-4 flex-1 whitespace-pre-line text-sm leading-6 text-slate-600">{review.text}</p><p className="mt-5 text-xs text-slate-400">{review.date}</p></article>}

export function ReviewsSection(){return <section className="bg-[#fffaf2] py-20 sm:py-24"><div className="container-lg"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Google Reviews</p><h2 className="section-title mt-3">What Our Travellers Say</h2><p className="mt-4 max-w-2xl text-slate-600">Written feedback shared by NaysTrip travellers on Google.</p></div><Link to="/reviews" className="btn-secondary">View All Reviews</Link></div><div className="mt-9 flex snap-x gap-5 overflow-x-auto pb-4">{featuredGoogleReviews.map(review=><div key={review.id} className="w-[300px] shrink-0 snap-start sm:w-[360px]"><ReviewCard review={review}/></div>)}</div></div></section>}

export default function Reviews(){return <><Seo title="NaysTrip Google Reviews" description="Written Google reviews supplied by NaysTrip travellers."/><main className="bg-[#fffaf2] py-16 sm:py-24"><div className="container-lg"><p className="eyebrow">Google Reviews</p><h1 className="mt-3 font-display text-4xl text-[#173c34] sm:text-6xl">What Our Travellers Say</h1><p className="mt-5 max-w-2xl text-slate-600">All written Google Business Profile reviews supplied by the owner, shown without rewriting.</p><div className="mt-8 flex flex-wrap gap-3"><a href={googleBusinessUrl} target="_blank" rel="noopener noreferrer" className="btn-primary">View All Reviews on Google <ExternalLink size={15}/></a><a href={googleBusinessUrl} target="_blank" rel="noopener noreferrer" className="btn-secondary">Write a Review</a></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{googleReviews.map(review=><ReviewCard key={review.id} review={review}/>)}</div></div></main></>}
