import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, FileCheck2 } from "lucide-react";
import { Link, Navigate, useParams } from "react-router-dom";
import Seo from "../components/shared/Seo";
import SmartImage from "../components/shared/SmartImage";
import { PageLoader } from "../components/shared/Loading";
import { loadSiteSettings } from "../data/siteConfig";

export default function ServiceDetails(){
  const {slug}=useParams();
  const [pkg,setPkg]=useState(null),[loading,setLoading]=useState(true),[missing,setMissing]=useState(false),[category,setCategory]=useState("Travel Service");
  useEffect(()=>{let active=true;Promise.all([fetch(`/api/packages?slug=${encodeURIComponent(slug)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);return data.package}),loadSiteSettings().catch(()=>null)]).then(([service,settings])=>{if(!active)return;if(service.package_type!=="service"){setMissing(true);return}setPkg(service);const categoryId=service.policies?.menuCategoryIds?.[0];setCategory(settings?.headerMenuOptions?.find(item=>item.id===categoryId)?.label||"Travel Service")}).catch(()=>active&&setMissing(true)).finally(()=>active&&setLoading(false));return()=>{active=false}},[slug]);
  const items=useMemo(()=>pkg?.items||[],[pkg]);
  if(loading)return <PageLoader/>;
  if(missing||!pkg)return <Navigate to="/tours" replace/>;
  const benefits=pkg.highlights||[],requirements=items.filter(item=>item.item_type==="inclusion"),process=items.filter(item=>item.item_type==="note"),faqs=items.filter(item=>item.item_type==="faq");
  return <>
    <Seo title={`${pkg.title} | NaysTrip`} description={pkg.short_description||pkg.overview}/>
    <section className="relative min-h-[520px] overflow-hidden bg-[#173c34] text-white"><SmartImage src={pkg.hero_image} context={pkg.title} alt={pkg.seo?.hero_alt||pkg.title} wrapperClassName="absolute inset-0" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/55 to-black/15"/><div className="container-lg relative flex min-h-[520px] items-end py-16"><div className="max-w-3xl"><Link to="/" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16}/>Home</Link><p className="eyebrow mt-8 !text-orange-300">{category}</p><h1 className="mt-4 font-display text-5xl leading-tight sm:text-6xl">{pkg.title}</h1>{pkg.short_description&&<p className="mt-5 max-w-2xl text-lg text-white/85">{pkg.short_description}</p>}<Link to={`/custom-trip?service=${encodeURIComponent(pkg.slug)}`} className="btn-primary mt-8">Enquire now <ArrowRight size={16}/></Link></div></div></section>
    <section className="bg-[#fffdf8] py-14 sm:py-20"><div className="container-lg grid gap-10 lg:grid-cols-[1.4fr_.8fr]"><div><p className="eyebrow">Service details</p><div className="mt-5 whitespace-pre-line text-base leading-8 text-slate-600">{pkg.overview||pkg.short_description}</div>{benefits.length>0&&<section className="mt-10"><h2 className="font-display text-3xl text-[#173c34]">Key benefits</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{benefits.map(value=><p key={value} className="flex gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm"><Check className="shrink-0 text-emerald-600" size={18}/>{value}</p>)}</div></section>}{process.length>0&&<section className="mt-10"><h2 className="font-display text-3xl text-[#173c34]">How it works</h2><ol className="mt-5 space-y-3">{process.map((item,index)=><li key={item.id||item.body} className="flex gap-4 rounded-xl bg-white p-4"><strong className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-orange-500 text-white">{index+1}</strong><span className="pt-1 text-slate-600">{item.body}</span></li>)}</ol></section>}</div><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><FileCheck2 className="text-orange-600"/><h2 className="mt-4 font-display text-2xl text-[#173c34]">Requirements</h2>{requirements.length?<ul className="mt-4 space-y-3 text-sm text-slate-600">{requirements.map(item=><li key={item.id||item.body} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-emerald-600"/>{item.body}</li>)}</ul>:<p className="mt-3 text-sm text-slate-500">Our team will confirm the requirements for your request.</p>}{pkg.price_from!=null&&<p className="mt-6 border-t pt-5"><span className="block text-xs font-bold uppercase tracking-wide text-slate-400">Starting price</span><strong className="text-2xl text-[#173c34]">₹{Number(pkg.price_from).toLocaleString("en-IN")}</strong></p>}<Link to={`/custom-trip?service=${encodeURIComponent(pkg.slug)}`} className="btn-primary mt-6 w-full justify-center">Request a quote</Link></aside></div>{pkg.gallery?.length>0&&<div className="container-lg mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{pkg.gallery.map((image,index)=><SmartImage key={image} src={image} context={`${pkg.title} ${index+1}`} alt={`${pkg.title} service`} wrapperClassName="aspect-[4/3] overflow-hidden rounded-2xl" className="object-cover"/>)}</div>}{faqs.length>0&&<div className="container-lg mt-14 max-w-4xl"><h2 className="font-display text-3xl text-[#173c34]">Frequently asked questions</h2><div className="mt-5 space-y-3">{faqs.map(item=><details key={item.id||item.body} className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-bold text-[#173c34]">{item.body}</summary></details>)}</div></div>}</section>
  </>;
}
