import { useMemo, useState } from "react";
import { ArrowRight, Search, SlidersHorizontal } from "lucide-react";
import { Link } from "react-router-dom";
import Seo from "../components/shared/Seo";
import { tours } from "../data/tours";

export default function ToursListing(){
  const [query,setQuery]=useState(""); const [days,setDays]=useState("All");
  const filtered=useMemo(()=>tours.filter(t=>(!query||`${t.title} ${t.destinations.join(" ")}`.toLowerCase().includes(query.toLowerCase()))&&(days==="All"||String(t.days)===days)),[query,days]);
  return <><Seo title="Maharashtra Tour Packages | NaysTrip & Treks" description="Browse structured Maharashtra itineraries across Mumbai, Mahabaleshwar, Konkan, Nashik, Shirdi, Ajanta, Ellora and more."/>
    <section className="bg-[#173c34] pb-14 pt-20 text-white"><div className="container-lg"><p className="eyebrow !text-orange-300">Domestic · Maharashtra</p><h1 className="mt-4 max-w-4xl font-display text-5xl sm:text-7xl">Routes with a reason for every stop.</h1><p className="mt-5 max-w-2xl text-white/65">Original day sequences preserved from the supplied NaysTrip package document. Pricing is confirmed against dates, group size and availability.</p></div></section>
    <section className="sticky top-[72px] z-30 border-b border-slate-200 bg-white/95 py-4 backdrop-blur"><div className="container-lg flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-3.5 text-slate-400" size={18}/><span className="sr-only">Search packages</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Mumbai, Konkan, Shirdi…" className="h-12 w-full border border-slate-300 pl-11 pr-4 focus:border-orange-500 focus:outline-none"/></label><label className="relative"><SlidersHorizontal className="absolute left-4 top-3.5 text-slate-400" size={18}/><span className="sr-only">Filter by duration</span><select value={days} onChange={e=>setDays(e.target.value)} className="h-12 min-w-52 appearance-none border border-slate-300 bg-white pl-11 pr-8 focus:border-orange-500 focus:outline-none"><option>All</option>{[3,4,5,6].map(v=><option key={v} value={v}>{v} days</option>)}</select></label></div></section>
    <section className="py-16"><div className="container-lg"><p className="mb-7 text-sm font-semibold text-slate-500">{filtered.length} verified itineraries</p><div className="grid gap-x-6 gap-y-10 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(t=><article key={t.slug} className="group"><Link to={`/tours/${t.slug}`} className="block aspect-[4/3] overflow-hidden bg-slate-100"><img src={t.image} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" loading="lazy"/></Link><div className="border-b border-slate-200 py-5"><div className="flex items-center justify-between gap-4 text-xs font-bold uppercase tracking-[.13em] text-orange-600"><span>{t.duration}</span><span>Price on request</span></div><h2 className="mt-3 font-display text-3xl leading-tight text-[#173c34]"><Link to={`/tours/${t.slug}`}>{t.title}</Link></h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-600">{t.destinations.join(" · ")}</p><Link to={`/tours/${t.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-[#173c34]">View itinerary <ArrowRight size={16}/></Link></div></article>)}</div></div></section>
  </>;
}
