import {destinations} from "../../data/destinations";
import { Link } from "react-router-dom";
import { Mountain } from "lucide-react";
import { tours } from "../../data/tours";
import { treks,expeditions } from "../../data/treksExpeditions";
export default function MonthlyPicks({settings,packages}) {
 const picks=[...(settings.monthlyPicks||[])].filter(p=>p.published!==false&&p.active!==false).sort((a,b)=>Number(a.displayOrder||0)-Number(b.displayOrder||0)),phone=String(settings.whatsapp||settings.phone||"").replace(/\D/g,"");
 const catalogue=[...packages.map(p=>({...p,image:p.hero_image,duration:p.days?`${p.nights}N/${p.days}D`:"",route:`/tours/${p.slug}`})),...tours.map(p=>({...p,route:`/tours/${p.slug}`})),...treks.map(p=>({...p,title:p.name,route:`/treks/${p.slug}`})),...expeditions.map(p=>({...p,title:p.name,route:`/expeditions/${p.slug}`}))];
 if(!picks.length)return null;
 const groups=[["trip","Top Trips This Month"],["trek","Top Treks This Month"]];
 return <section className="bg-[#fffaf2] py-16"><div className="container-lg"><p className="eyebrow">{picks.find(p=>p.label)?.label||"This month"}</p><h2 className="section-title mt-3">Our most recommended adventures and getaways this month</h2><p className="mt-4 text-slate-600">Handpicked by the NaysTrip team</p>{groups.map(([type,title])=>{const items=picks.filter(p=>(p.type||"trip")===type);return items.length?<div key={type} className="mt-10"><h3 className="mb-6 font-display text-3xl text-[#173c34]">{title}</h3><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{items.map(p=>{
 const slug=p.packageSlug||p.slug;const match=catalogue.find(c=>slug?c.slug===slug:c.title?.toLowerCase()===p.title.toLowerCase()),image=p.image||match?.image||destinations.find(d=>d.name.toLowerCase()===p.destination?.toLowerCase())?.image,commercial=packages.find(c=>c.slug===match?.slug),price=commercial?.price_from;
 return <article key={p.id} className={`flex min-w-0 flex-col overflow-hidden rounded-2xl bg-white shadow-sm ${p.recommended?"border-2 border-orange-400":"border border-slate-200"}`}>{image?<img src={image} alt={p.title} loading="lazy" className="aspect-[4/3] w-full object-cover"/>:<div className="grid aspect-[4/3] place-items-center bg-gradient-to-br from-[#e8eee7] to-[#faf0de] text-[#173c34]" aria-hidden="true"><Mountain size={44} strokeWidth={1}/></div>}<div className="flex flex-1 flex-col p-5">{p.recommended&&<span className="mb-3 w-fit rounded-full bg-orange-50 px-3 py-1 text-[11px] font-extrabold text-orange-700">Recommended by NaysTrip</span>}<h5 className="font-display text-2xl text-[#173c34]">{p.title}</h5>{p.destination&&<p className="mt-1 text-sm text-slate-600">{p.destination}</p>}{(p.duration||match?.duration)&&<p className="mt-2 text-sm text-slate-500">{p.duration||match.duration}</p>}{p.description&&<p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{p.description}</p>}{price!==null&&price!==undefined&&Number.isFinite(Number(price))&&Number(price)>0&&<p className="mt-3 font-bold">From ₹{Number(price).toLocaleString("en-IN")}</p>}<div className="mt-auto grid gap-2 pt-5"><Link className="btn-secondary text-center" to={match?.route||`/custom-trip?destination=${encodeURIComponent(p.destination||p.title)}`}>{match?"View Detailed Itinerary":"Request Detailed Itinerary"}</Link>{phone&&<a className="text-center text-sm font-bold text-emerald-800" target="_blank" rel="noreferrer" href={`https://wa.me/${phone}?text=${encodeURIComponent(`Please share more information about ${p.title} ${p.duration||""}.`)}`}>WhatsApp for more information</a>}</div></div></article>
 })}</div></div>:null})}</div></section>
}
