import {destinations} from "../../data/destinations";
import { Link } from "react-router-dom";
import { Mountain } from "lucide-react";
import { monthlyPicks,pickGroups } from "../../data/monthlyPicks";
import { tours } from "../../data/tours";
import { treks,expeditions } from "../../data/treksExpeditions";
export default function MonthlyPicks({settings,packages}) {
 const picks=[...(settings.monthlyPicks||monthlyPicks)],phone=String(settings.whatsapp||settings.phone||"").replace(/\D/g,"");
 const catalogue=[...packages.map(p=>({...p,image:p.hero_image,duration:p.days?`${p.nights}N/${p.days}D`:"",route:`/tours/${p.slug}`})),...tours.map(p=>({...p,route:`/tours/${p.slug}`})),...treks.map(p=>({...p,title:p.name,route:`/treks/${p.slug}`})),...expeditions.map(p=>({...p,title:p.name,route:`/expeditions/${p.slug}`}))];
 for(const [slugs,group] of [[settings.topTripSlugs||[],0],[settings.topTrekSlugs||[],3]])for(const slug of slugs){const item=catalogue.find(p=>p.slug===slug);if(item&&!picks.some(p=>p.slug===slug))picks.push({id:`featured-${slug}`,slug,group,title:item.title,duration:item.duration,active:true})}
 return <section className="bg-[#fffaf2] py-16"><div className="container-lg"><p className="eyebrow">September 2026 Picks</p><h2 className="section-title mt-3">Our most recommended adventures and getaways this month</h2><p className="mt-4 text-slate-600">Handpicked by the NaysTrip team</p>{pickGroups.map((group,index)=><div key={group} className="mt-10">{(index===0||index===2)&&<h3 className="mb-6 font-display text-3xl text-[#173c34]">{index===0?"Top Trips This Month":"Top Treks This Month"}</h3>}<h4 className="mb-4 text-sm font-bold uppercase tracking-wide text-orange-700">{group}</h4><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{picks.filter(p=>p.active!==false&&p.group===index).map(p=>{
 const match=catalogue.find(c=>p.slug?c.slug===p.slug:c.title?.toLowerCase()===p.title.toLowerCase()),image=p.image||match?.image||destinations.find(d=>d.name.toLowerCase()===p.title.toLowerCase())?.image,commercial=packages.find(c=>c.slug===match?.slug),price=commercial?.price_from;
 return <article key={p.id} className="flex min-w-0 flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{image?<img src={image} alt={p.title} loading="lazy" className="aspect-[4/3] w-full object-cover"/>:<div className="grid aspect-[4/3] place-items-center bg-gradient-to-br from-[#e8eee7] to-[#faf0de] text-[#173c34]" aria-hidden="true"><Mountain size={44} strokeWidth={1}/></div>}<div className="flex flex-1 flex-col p-5"><h5 className="font-display text-2xl text-[#173c34]">{p.title}</h5>{(p.duration||match?.duration)&&<p className="mt-2 text-sm text-slate-500">{p.duration||match.duration}</p>}{price!==null&&price!==undefined&&Number.isFinite(Number(price))&&Number(price)>0&&<p className="mt-3 font-bold">From ₹{Number(price).toLocaleString("en-IN")}</p>}<div className="mt-auto grid gap-2 pt-5"><Link className="btn-secondary text-center" to={match?.route||`/custom-trip?destination=${encodeURIComponent(p.title)}`}>{match?"View Detailed Itinerary":"Request Detailed Itinerary"}</Link>{phone&&<a className="text-center text-sm font-bold text-emerald-800" target="_blank" rel="noreferrer" href={`https://wa.me/${phone}?text=${encodeURIComponent(`Please share more information about ${p.title} ${p.duration}.`)}`}>WhatsApp for more information</a>}</div></div></article>
 })}</div>{!picks.some(p=>p.active!==false&&p.group===index)&&<p className="text-sm text-slate-500">Our team is updating this selection.</p>}</div>)}</div></section>
}
