export const sessionKey=(portal)=>`naystrip_${portal}_session`;
export const getToken=(portal="customer")=>{try{return sessionStorage.getItem(sessionKey(portal))||""}catch{return ""}};
export const portalFetch=async(path,options={},portal="customer")=>{const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${getToken(portal)}`,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||"Request failed");error.status=response.status;throw error}return data};
const filenameFrom=(response,fallback)=>{const header=response.headers.get("content-disposition")||"";return header.match(/filename="?([^";]+)"?/i)?.[1]||fallback};
async function openDocument(path,{portal=null,preview=false,fallback="NAYSTRIP-Document"}={}){const sessionPortal=portal||(window.location.pathname.startsWith("/admin")?"admin":"customer");const response=await fetch(path,{headers:{Authorization:`Bearer ${getToken(sessionPortal)}`}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"Document request failed")}const blob=await response.blob();const url=URL.createObjectURL(blob);if(preview){window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000);return}const anchor=document.createElement("a");anchor.href=url;anchor.download=filenameFrom(response,fallback);anchor.click();URL.revokeObjectURL(url)}
export async function downloadProtectedDocument(reference,type,format="pdf",portal=null){return openDocument(`/api/documents/booking?reference=${encodeURIComponent(reference)}&type=${encodeURIComponent(type)}&format=${encodeURIComponent(format)}`,{portal,fallback:`${reference}-${type}.${format}`})}
export async function previewProtectedDocument(reference,type,format="pdf",portal=null){return openDocument(`/api/documents/booking?reference=${encodeURIComponent(reference)}&type=${encodeURIComponent(type)}&format=${encodeURIComponent(format)}&disposition=inline`,{portal,preview:true,fallback:`${reference}-${type}.${format}`})}
export async function downloadInvoiceDocument(invoiceId,format="pdf",preview=false){return openDocument(`/api/documents/booking?invoiceId=${encodeURIComponent(invoiceId)}&type=invoice&format=${encodeURIComponent(format)}${preview?"&disposition=inline":""}`,{portal:"admin",preview,fallback:`NAYSTRIP-Invoice.${format}`})}
export async function downloadStoredDocument(documentId,name="NAYSTRIP-Travel-Document.pdf",portal=null,preview=false){return openDocument(`/api/documents/booking?documentId=${encodeURIComponent(documentId)}${preview?"&disposition=inline":""}`,{portal,preview,fallback:name})}
export async function openCashfree(reference,purpose="advance",onStatus=()=>{}){onStatus("Preparing secure payment…");const order=await portalFetch("/api/payments/create-order",{method:"POST",body:JSON.stringify({bookingReference:reference,purpose})});await checkoutCashfreeOrder(order,onStatus);onStatus("Verifying payment…");return portalFetch("/api/payments/verify",{method:"POST",body:JSON.stringify({order_id:order.order_id})})}

export async function checkoutCashfreeOrder(order,onStatus=()=>{}){if(!window.Cashfree){await new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://sdk.cashfree.com/js/v3/cashfree.js";script.onload=resolve;script.onerror=()=>reject(new Error("Payment window could not be loaded"));document.head.appendChild(script)})}onStatus("Opening Cashfree…");const cashfree=window.Cashfree({mode:order.mode||"sandbox"});const result=await cashfree.checkout({paymentSessionId:order.payment_session_id,redirectTarget:"_modal"});if(result?.error)throw new Error(result.error.message||"Payment was cancelled or could not be completed");}
