create extension if not exists pgcrypto;
create type public.publish_status as enum ('draft','published','archived');
create type public.booking_status as enum ('pending','confirmed','cancelled','completed');
create type public.payment_status as enum ('created','pending','successful','failed','refunded');

create table if not exists public.roles(id uuid primary key default gen_random_uuid(),name text unique not null,created_at timestamptz not null default now());
create table if not exists public.permissions(id uuid primary key default gen_random_uuid(),key text unique not null,description text,created_at timestamptz not null default now());
create table if not exists public.role_permissions(role_id uuid references public.roles on delete cascade,permission_id uuid references public.permissions on delete cascade,primary key(role_id,permission_id));
create table if not exists public.admin_users(user_id uuid primary key references auth.users on delete cascade,role_id uuid references public.roles,display_name text,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.customers(user_id uuid primary key references auth.users on delete cascade,first_name text,last_name text,phone text,whatsapp text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.b2b_agents(id uuid primary key default gen_random_uuid(),user_id uuid unique references auth.users on delete set null,business_name text not null,contact_person text not null,email text not null,phone text not null,gst_number text,pan text,address text,website text,business_type text,verification_status text not null default 'pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.agent_documents(id uuid primary key default gen_random_uuid(),agent_id uuid not null references public.b2b_agents on delete cascade,document_type text not null,object_path text not null,mime_type text not null,verified_at timestamptz,created_at timestamptz not null default now());

create table if not exists public.destinations(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,region text,country text not null default 'India',overview text,seo jsonb not null default '{}',status public.publish_status not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.tour_categories(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,created_at timestamptz not null default now());
create table if not exists public.holiday_types(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,created_at timestamptz not null default now());
create table if not exists public.packages(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,package_type text not null default 'tour',destination_names text[] not null default '{}',nights integer not null check(nights>=0),days integer not null check(days>0),overview text,hero_image text,price_from numeric(12,2),tax_percent numeric(5,2),source text,status public.publish_status not null default 'draft',featured boolean not null default false,seo jsonb not null default '{}',deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists packages_status_idx on public.packages(status) where deleted_at is null;
create index if not exists packages_destination_names_idx on public.packages using gin(destination_names);
create table if not exists public.package_itinerary_days(id uuid primary key default gen_random_uuid(),package_id uuid not null references public.packages on delete cascade,day_number integer not null,title text not null,description text not null,meals text,stay text,transfers text,activities text[],sort_order integer not null,unique(package_id,day_number));
create table if not exists public.package_items(id uuid primary key default gen_random_uuid(),package_id uuid not null references public.packages on delete cascade,item_type text not null check(item_type in ('inclusion','exclusion','document','note','faq')),title text,body text not null,sort_order integer not null default 0);
create table if not exists public.package_departures(id uuid primary key default gen_random_uuid(),package_id uuid not null references public.packages on delete cascade,start_date date not null,end_date date not null,capacity integer not null check(capacity>0),booked_seats integer not null default 0 check(booked_seats>=0),price_override numeric(12,2),status text not null default 'open',meeting_point text,leader_name text,internal_notes text,unique(package_id,start_date));
create index if not exists departures_start_date_idx on public.package_departures(start_date,status);

create table if not exists public.inquiries(id text primary key,kind text not null check(kind in ('contact','custom_trip','corporate','school')),name text not null,phone text not null,email text,destination text,payload jsonb not null default '{}',source text,status text not null default 'new',priority text not null default 'normal',assignee uuid references public.admin_users(user_id),follow_up_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists inquiries_queue_idx on public.inquiries(status,created_at desc);
create table if not exists public.lead_activities(id uuid primary key default gen_random_uuid(),inquiry_id text not null references public.inquiries on delete cascade,actor uuid references public.admin_users(user_id),activity_type text not null,notes text,created_at timestamptz not null default now());

create table if not exists public.bookings(id uuid primary key default gen_random_uuid(),reference text unique not null,customer_id uuid references public.customers(user_id),agent_id uuid references public.b2b_agents,package_id uuid references public.packages,departure_id uuid references public.package_departures,traveller_count integer not null check(traveller_count>0),subtotal numeric(12,2) not null,tax numeric(12,2) not null,total numeric(12,2) not null,currency text not null default 'INR',status public.booking_status not null default 'pending',billing jsonb not null default '{}',gst_details jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.booking_travellers(id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings on delete cascade,first_name text not null,last_name text,traveller_type text not null,id_type text not null,id_number_encrypted text not null,medical_declaration jsonb,emergency_contact jsonb,created_at timestamptz not null default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings on delete restrict,gateway text not null,gateway_order_id text unique,gateway_payment_id text unique,gateway_transaction_id text,amount numeric(12,2) not null,currency text not null default 'INR',status public.payment_status not null default 'created',raw_status jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.refunds(id uuid primary key default gen_random_uuid(),payment_id uuid not null references public.payments on delete restrict,gateway_refund_id text unique,amount numeric(12,2) not null,status text not null,created_at timestamptz not null default now());
create table if not exists public.coupons(id uuid primary key default gen_random_uuid(),code text unique not null,discount_type text not null,value numeric(12,2) not null,starts_at timestamptz,ends_at timestamptz,usage_limit integer,active boolean not null default true,created_at timestamptz not null default now());

create table if not exists public.blog_categories(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null);
create table if not exists public.blogs(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,excerpt text,body jsonb not null default '{}',cover_image text,category_id uuid references public.blog_categories,author_name text,related_package_ids uuid[] not null default '{}',status public.publish_status not null default 'draft',published_at timestamptz,seo jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.media(id uuid primary key default gen_random_uuid(),object_path text unique not null,mime_type text not null,size_bytes bigint not null,alt_text text,tags text[] not null default '{}',in_use boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.website_settings(id boolean primary key default true check(id),data jsonb not null,updated_at timestamptz not null default now());
create table if not exists public.audit_logs(id bigint generated always as identity primary key,actor uuid references public.admin_users(user_id),action text not null,entity_type text not null,entity_id text,metadata jsonb not null default '{}',created_at timestamptz not null default now());

alter table public.packages enable row level security;alter table public.package_itinerary_days enable row level security;alter table public.package_items enable row level security;alter table public.inquiries enable row level security;alter table public.bookings enable row level security;alter table public.payments enable row level security;alter table public.customers enable row level security;alter table public.b2b_agents enable row level security;
create policy "published packages are public" on public.packages for select using(status='published' and deleted_at is null);
create policy "published itinerary is public" on public.package_itinerary_days for select using(exists(select 1 from public.packages p where p.id=package_id and p.status='published' and p.deleted_at is null));
create policy "published package items are public" on public.package_items for select using(exists(select 1 from public.packages p where p.id=package_id and p.status='published' and p.deleted_at is null));
create policy "customers read own profile" on public.customers for select using(auth.uid()=user_id);
create policy "customers update own profile" on public.customers for update using(auth.uid()=user_id);
create policy "customers read own bookings" on public.bookings for select using(customer_id=auth.uid());
create policy "customers read own payments" on public.payments for select using(exists(select 1 from public.bookings b where b.id=booking_id and b.customer_id=auth.uid()));
create policy "agents read own profile" on public.b2b_agents for select using(user_id=auth.uid());

insert into public.roles(name) values ('Super Admin'),('Content Manager'),('Sales'),('Operations'),('Accounts'),('B2B Manager'),('Support') on conflict(name) do nothing;
insert into public.website_settings(id,data) values(true,'{"brandName":"NaysTrip & Treks","phone":"+91 8097132424","whatsapp":"+91 7710991126","email":"hello@naystrip.com","cancellationEmail":"cancellation@naystrip.com","address":"EL146, Mahape, Navi Mumbai, Maharashtra, India"}'::jsonb) on conflict(id) do update set data=excluded.data,updated_at=now();
