import {useEffect,useState} from "react";
import {Download,Eye,Mail,MessageCircle} from "lucide-react";
const common={customer:"",reference:"",voucherNumber:"",contact:"",status:"Confirmed",notes:"",inclusions:"",amount:"",specialRequests:"",cancellationPolicy:""};
const initial={hotel:{...common,hotel:"",hotelContact:"",location:"",category:"",checkIn:"",checkInTime:"",checkOut:"",checkOutTime:"",duration:"",accommodation:"",rooms:"",adults:"",children:"",roomType:"",occupancy:"",guestNames:"",mealPlan:"",baseAmount:"",taxes:"",fees:"",checkInInstructions:"",hotelPolicy:"",policyNotes:""},taxi:{...common,travelDate:"",pickup:"",drop:"",pickupTime:"",dropDate:"",dropTime:"",vehicle:"",vehicleCount:"",vehicleNumber:"",driverName:"",driverPhone:"",passengers:"",duration:"",kilometres:"",extraCharges:"",tolls:"",room:"",sightseeing:"",route:"",itinerary:"",exclusions:""}};
const labels={customer:"Customer / lead traveller",reference:"Confirmed booking reference",voucherNumber:"Voucher number",contact:"Customer email / phone",status:"Confirmation status",notes:"Important information",inclusions:"Inclusions",amount:"Total amount",specialRequests:"Special requests / instructions",cancellationPolicy:"Cancellation policy",hotel:"Hotel name",hotelContact:"Hotel contact",location:"Hotel address / location",category:"Category",checkIn:"Check-in date",checkInTime:"Check-in time",checkOut:"Check-out date",checkOutTime:"Check-out time",duration:"Duration",accommodation:"Accommodation",rooms:"Rooms",adults:"Adults",children:"Children",roomType:"Room type",occupancy:"Occupancy",guestNames:"Room-wise guest names",mealPlan:"Meal plan",baseAmount:"Base amount",taxes:"Taxes",fees:"Other fees",checkInInstructions:"Check-in instructions",hotelPolicy:"Hotel booking policy",policyNotes:"No-show / amendments / refunds",travelDate:"Pickup date",pickup:"Pickup location",drop:"Drop location",pickupTime:"Pickup time",dropDate:"Drop date",dropTime:"Drop time",vehicle:"Vehicle type",vehicleCount:"Number of vehicles",vehicleNumber:"Vehicle number",driverName:"Driver name",driverPhone:"Driver phone",passengers:"Passengers",kilometres:"Included kilometres",extraCharges:"Extra kilometre / hour charges",tolls:"Toll / parking / state tax",room:"Driver room / night arrangement",sightseeing:"Sightseeing",route:"Route",itinerary:"Detailed itinerary",exclusions:"Exclusions"};
const multiline=new Set(["notes","inclusions","specialRequests","cancellationPolicy","policyNotes","guestNames","checkInInstructions","hotelPolicy","sightseeing","route","itinerary","exclusions","extraCharges","tolls"]);const dates=new Set(["checkIn","checkOut","travelDate","dropDate"]),times=new Set(["checkInTime","checkOutTime","pickupTime","dropTime"]);const session=()=>sessionStorage.getItem("naystrip_admin_session");
export default function AdminVouchers(){
 const [type,setType]=useState("hotel"),[forms,setForms]=useState(initial),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[pdf,setPdf]=useState(""),[documentId,setDocumentId]=useState(""),[bookings,setBookings]=useState([]);const form=forms[type];
 useEffect(()=>{fetch("/api/admin/bookings",{headers:{Authorization:`Bearer ${session()}`}}).then(r=>r.ok?r.json():{bookings:[]}).then(data=>setBookings(data.bookings||[])).catch(()=>{})},[]);
 useEffect(()=>()=>{if(pdf)URL.revokeObjectURL(pdf)},[pdf]);
 const change=(key,value)=>setForms(current=>({...current,[type]:{...current[type],[key]:value}}));
 const generateFormat=async(format="pdf")=>{if(busy)return null;setBusy(true);setMessage("Generating…");try{const response=await fetch("/api/documents/service-voucher",{method:"POST",headers:{Authorization:`Bearer ${session()}`,"Content-Type":"application/json"},body:JSON.stringify({type,format,fields:form})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"Voucher could not be generated")}const blob=await response.blob(),id=response.headers.get("x-document-id")||"";if(format==="pdf"){if(pdf)URL.revokeObjectURL(pdf);setPdf(URL.createObjectURL(blob));setDocumentId(id)}else{const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`NAYSTRIP-${type==="hotel"?"Hotel":"Transport"}-Voucher-${form.voucherNumber||form.reference}.docx`;a.click();URL.revokeObjectURL(url)}setMessage(`${format.toUpperCase()} voucher generated and saved securely.`);return id}catch(error){setMessage(error.message);return null}finally{setBusy(false)}};
 const generate=event=>{event.preventDefault();generateFormat("pdf")};const filename=`NAYSTRIP-${type==="hotel"?"Hotel":"Transport"}-Voucher-${form.voucherNumber||form.reference}.pdf`;const download=()=>{const a=document.createElement("a");a.href=pdf;a.download=filename;a.click()};
 const deliver=async(action)=>{const booking=bookings.find(item=>item.reference===form.reference);if(!booking)return setMessage("Use an exact confirmed booking reference before delivery.");let id=documentId;if(!id)id=await generateFormat("pdf");if(!id)return;setBusy(true);try{const response=await fetch("/api/admin/document-delivery",{method:"POST",headers:{Authorization:`Bearer ${session()}`,"Content-Type":"application/json"},body:JSON.stringify({action,bookingId:booking.id,documentId:id,documentType:type==="hotel"?"hotel_voucher":"transport_voucher",recipient:String(form.contact).includes("@")?form.contact:booking.billing?.email,phone:String(form.contact).includes("@")?booking.billing?.phone:form.contact})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Delivery failed");if(action==="whatsapp")window.open(data.url,"_blank","noopener,noreferrer");else setMessage(`Voucher emailed to ${data.recipient}`)}catch(error){setMessage(error.message)}finally{setBusy(false)}};
  return <div><h1 className="font-display text-2xl">Service Voucher Generator</h1><p className="mt-1 text-sm text-navy-500">Create and save booking-linked hotel and taxi / transport vouchers. Blank policy fields are omitted.</p><div className="mt-6 flex gap-2">{["hotel","taxi"].map(item=><button type="button" key={item} onClick={()=>{setType(item);setPdf("");setDocumentId("");setMessage("")}} className={type===item?"btn-primary capitalize":"btn-secondary capitalize"}>{item==="taxi"?"Taxi / transport":item} voucher</button>)}</div><form onSubmit={generate} className="mt-5 rounded-2xl border bg-white p-6"><div className="grid gap-4 sm:grid-cols-2">{Object.keys(form).map(key=><label key={key} className={multiline.has(key)?"sm:col-span-2":""}><span className="label-field">{labels[key]}</span>{multiline.has(key)?<textarea rows={key==="itinerary"?6:3} value={form[key]} onChange={event=>change(key,event.target.value)} className="input-field"/>:<input required={["customer","reference"].includes(key)} type={dates.has(key)?"date":times.has(key)?"time":"text"} value={form[key]} onChange={event=>change(key,event.target.value)} className="input-field"/>}</label>)}</div><div className="mt-6 flex flex-wrap gap-2"><button disabled={busy} className="btn-primary">{busy?"Generating…":"Generate & save PDF"}</button><button type="button" disabled={busy} onClick={()=>generateFormat("docx")} className="btn-secondary"><Download size={14}/>Generate Word</button>{pdf&&<><button type="button" onClick={()=>window.open(pdf,"_blank","noopener,noreferrer")} className="btn-secondary"><Eye size={14}/>Preview</button><button type="button" onClick={download} className="btn-secondary"><Download size={14}/>Download PDF</button><button type="button" disabled={busy} onClick={()=>deliver("email")} className="btn-secondary"><Mail size={14}/>Email</button><button type="button" disabled={busy} onClick={()=>deliver("whatsapp")} className="btn-secondary"><MessageCircle size={14}/>WhatsApp</button></>}</div>{message&&<p role="status" className="mt-4 text-sm text-navy-600">{message}</p>}</form></div>;
}
