import {useEffect,useMemo,useState} from "react";
import {Download,Eye,Mail,MessageCircle,RefreshCw,Search,Send,Upload,X} from "lucide-react";
import {downloadProtectedDocument,downloadStoredDocument} from "../../utils/portal";
const token=()=>sessionStorage.getItem("naystrip_admin_session");
const request=async(path,options={})=>{const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data};
const statuses=["draft","pending_payment","payment_verification","confirmed","partially_paid","fully_paid","on_hold","completed","cancelled","refund_pending","refunded"];
export default function AdminBookings(){
 const [bookings,setBookings]=useState([]),[viewing,setViewing]=useState(null),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[payment,setPayment]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 const [manual,setManual]=useState({amount:"",method:"bank_transfer",reference:""});const [upload,setUpload]=useState({file:null,type:"ticket",name:""});
 const load=async()=>{setBusy(true);try{setBookings((await request("/api/admin/bookings")).bookings)}catch(err){setError(err.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const details=async(id)=>{setBusy(true);try{setViewing((await request(`/api/admin/bookings?id=${id}`)).booking)}catch(err){setError(err.message)}finally{setBusy(false)}};
 const action=async(body)=>{setBusy(true);setError("");try{const data=await request("/api/admin/bookings",{method:"PATCH",body:JSON.stringify({id:viewing.id,...body})});if(data.notification?.status==="failed")throw new Error(data.notification.error||"Message delivery failed");await details(viewing.id);await load()}catch(err){setError(err.message)}finally{setBusy(false)}};
 const uploadDocument=async()=>{if(!upload.file)return setError("Choose a PDF to upload");setBusy(true);setError("");try{const response=await fetch("/api/admin/booking-documents",{method:"POST",headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/pdf","x-booking-id":viewing.id,"x-document-type":upload.type,"x-display-name":upload.name||upload.file.name.replace(/\.pdf$/i,""),"x-original-filename":upload.file.name},body:upload.file});const data=await response.json();if(!response.ok)throw new Error(data.error||"Upload failed");setUpload({file:null,type:"ticket",name:""});await details(viewing.id)}catch(err){setError(err.message)}finally{setBusy(false)}};
 const prepare=async(type)=>{const response=await fetch(`/api/documents/booking?reference=${encodeURIComponent(viewing.reference)}&type=${type}`,{headers:{Authorization:`Bearer ${token()}`}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"Document preparation failed")}return response.blob()};
 const preview=async(type)=>{setError("");try{const url=URL.createObjectURL(await prepare(type));window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(err){setError(err.message)}};
 const previewStored=async(item)=>{setError("");try{const response=await fetch(`/api/documents/booking?documentId=${encodeURIComponent(item.id)}`,{headers:{Authorization:`Bearer ${token()}`}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"Preview failed")}const url=URL.createObjectURL(await response.blob());window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(err){setError(err.message)}};
 const notifyDocument=async(type,label)=>{setBusy(true);setError("");try{if(["voucher","itinerary","invoice","receipt"].includes(type))await prepare(type);await action({action:"send_document",documentName:label,documentType:type})}catch(err){setError(err.message);setBusy(false)}};
 const whatsappDocument=async(type,label)=>{setBusy(true);setError("");try{if(type)await prepare(type);const phone=String(viewing.billing?.phone||"").replace(/\D/g,"");if(!phone)throw new Error("Customer phone is unavailable");const text=`Your NaysTrip ${label} for ${viewing.reference} is ready. Sign in securely: ${location.origin}/account/dashboard`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer")}catch(err){setError(err.message)}finally{setBusy(false)}};
 const filtered=useMemo(()=>bookings.filter(item=>(!status||item.operational_status===status)&&(!payment||item.payment_state===payment)&&(!search||`${item.reference} ${item.billing?.name} ${item.package?.title}`.toLowerCase().includes(search.toLowerCase()))),[bookings,search,status,payment]);
 return <div><div className="flex flex-wrap justify-between gap-4"><div><h1 className="font-display text-2xl">Booking Management</h1><p className="text-sm text-navy-500">Customers, payments, secure documents and operations.</p></div><button onClick={load} className="btn-secondary"><RefreshCw size={15}/>Refresh</button></div>
 {error&&<p role="alert" className="mt-4 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
 <div className="my-5 grid gap-3 md:grid-cols-3"><label className="relative"><Search size={15} className="absolute left-3 top-3.5"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search reference or customer" className="input-field pl-9"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="input-field"><option value="">All booking statuses</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><select value={payment} onChange={e=>setPayment(e.target.value)} className="input-field"><option value="">All payment statuses</option>{["pending","failed","partially_paid","fully_paid","refunded"].map(item=><option key={item}>{item}</option>)}</select></div>
 <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left">{["Reference","Customer","Package","Travel","Payment","Status","View"].map(item=><th key={item} className="p-4">{item}</th>)}</tr></thead><tbody>{filtered.map(item=><tr key={item.id} className="border-b"><td className="p-4 font-mono text-xs">{item.reference}</td><td className="p-4">{item.billing?.name}</td><td className="p-4">{item.package?.title}</td><td className="p-4">{item.travel_date}</td><td className="p-4">INR {Number(item.amount_paid).toLocaleString("en-IN")} / {Number(item.total).toLocaleString("en-IN")}<span className="block text-xs">{item.payment_state}</span></td><td className="p-4">{item.operational_status}</td><td className="p-4"><button onClick={()=>details(item.id)} className="grid h-9 w-9 place-items-center bg-navy-50" aria-label={`View ${item.reference}`}><Eye size={15}/></button></td></tr>)}</tbody></table></div>
 {viewing&&<div className="fixed inset-0 z-50 grid place-items-center p-4"><button className="absolute inset-0 bg-navy-950/70" onClick={()=>setViewing(null)} aria-label="Close"/><section className="relative max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6 sm:p-8"><button onClick={()=>setViewing(null)} className="absolute right-5 top-5"><X/></button><p className="font-mono text-xs text-navy-400">{viewing.reference}</p><h2 className="mt-2 font-display text-3xl">{viewing.package?.title}</h2>
 <div className="mt-6 grid gap-4 sm:grid-cols-3">{Object.entries({Customer:viewing.billing?.name,Travel:viewing.travel_date,Travellers:viewing.traveller_count,Total:`INR ${Number(viewing.total).toLocaleString("en-IN")}`,Paid:`INR ${Number(viewing.amount_paid).toLocaleString("en-IN")}`,Balance:`INR ${Number(viewing.balance_due).toLocaleString("en-IN")}`}).map(([key,value])=><div className="bg-navy-50 p-4" key={key}><small>{key}</small><strong className="mt-1 block">{value}</strong></div>)}</div>
 <div className="mt-7 grid gap-5 lg:grid-cols-2"><div><h3 className="font-bold">Operational status</h3><select value={viewing.operational_status} disabled={busy} onChange={e=>action({action:"status",status:e.target.value})} className="input-field mt-2">{statuses.map(item=><option key={item}>{item}</option>)}</select><h3 className="mt-6 font-bold">Internal note</h3><textarea value={note} onChange={e=>setNote(e.target.value)} className="input-field mt-2" rows="3"/><button disabled={busy} onClick={()=>action({action:"note",note})} className="btn-secondary mt-2">Save note</button></div>
 <div><h3 className="font-bold">Record offline payment</h3><div className="mt-2 grid gap-2 sm:grid-cols-3"><input type="number" placeholder="Amount" value={manual.amount} onChange={e=>setManual({...manual,amount:e.target.value})} className="input-field"/><select value={manual.method} onChange={e=>setManual({...manual,method:e.target.value})} className="input-field"><option>bank_transfer</option><option>upi</option><option>cash</option><option>card_terminal</option></select><input placeholder="Reference" value={manual.reference} onChange={e=>setManual({...manual,reference:e.target.value})} className="input-field"/></div><button disabled={busy} onClick={()=>action({action:"manual_payment",...manual})} className="btn-primary mt-2">Record with audit trail</button></div></div>
 <h3 className="mt-7 font-bold">Generated documents</h3><div className="mt-2 grid gap-2">{["voucher","itinerary","invoice","receipt"].map(type=><div key={type} className="flex flex-wrap items-center gap-1"><span className="w-20 text-sm font-semibold capitalize">{type}</span><button onClick={()=>preview(type)} className="btn-secondary" aria-label={`Preview ${type}`}><Eye size={14}/>Preview</button><button onClick={()=>downloadProtectedDocument(viewing.reference,type)} className="btn-secondary"><Download size={14}/>Download</button><button disabled={busy} onClick={()=>notifyDocument(type,type)} className="btn-secondary"><Mail size={14}/>Email</button><button disabled={busy} onClick={()=>whatsappDocument(type,type)} className="btn-secondary"><MessageCircle size={14}/>WhatsApp</button></div>)}<button disabled={busy} onClick={()=>action({action:"resend",event:"booking_confirmed"})} className="btn-secondary justify-self-start"><Send size={14}/>Resend confirmation</button></div>
 <h3 className="mt-7 font-bold">Uploaded tickets and supplier vouchers</h3><div className="mt-2 grid gap-2">{(viewing.documents||[]).filter(item=>["hotel_voucher","transport_voucher","ticket","other"].includes(item.document_type)).map(item=>{const label=item.display_name||item.document_type.replaceAll("_"," ");return <div key={item.id} className="flex flex-wrap items-center gap-1"><span className="w-32 text-sm font-semibold">{label}</span><button onClick={()=>previewStored(item)} className="btn-secondary"><Eye size={14}/>Preview</button><button onClick={()=>downloadStoredDocument(item.id,item.original_filename||label,"admin")} className="btn-secondary"><Download size={14}/>Download</button><button disabled={busy} onClick={()=>notifyDocument(item.document_type,label)} className="btn-secondary"><Mail size={14}/>Email</button><button disabled={busy} onClick={()=>whatsappDocument(null,label)} className="btn-secondary"><MessageCircle size={14}/>WhatsApp</button></div>})}</div>
 <div className="mt-4 grid gap-2 sm:grid-cols-4"><select value={upload.type} onChange={e=>setUpload({...upload,type:e.target.value})} className="input-field"><option value="ticket">Ticket</option><option value="hotel_voucher">Hotel voucher</option><option value="transport_voucher">Transport voucher</option><option value="other">Other</option></select><input value={upload.name} onChange={e=>setUpload({...upload,name:e.target.value})} placeholder="Document name" className="input-field"/><input type="file" accept="application/pdf,.pdf" onChange={e=>setUpload({...upload,file:e.target.files?.[0]||null})} className="input-field sm:col-span-1"/><button disabled={busy||!upload.file} onClick={uploadDocument} className="btn-primary"><Upload size={14}/>Upload PDF</button></div>
 <h3 className="mt-8 font-bold">Travellers</h3><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><tbody>{viewing.travellers?.map(item=><tr key={item.id} className="border-b"><td className="p-3">{item.full_name}</td><td className="p-3">{item.traveller_type}</td><td className="p-3">{item.nationality}</td><td className="p-3">{item.special_requirements||"—"}</td></tr>)}</tbody></table></div></section></div>}
 </div>;
}
