import {useEffect,useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {ArrowRight,CheckCircle2,Clock3,Users} from "lucide-react";

const token=()=>sessionStorage.getItem("naystrip_admin_session");
const kinds={custom_trip:["Custom Trip Leads","/admin/leads"],contact:["Contact Leads","/admin/contact-leads"],package_quote:["Package / Quote Leads","/admin/package-leads"],quick_quote:["Quick Quote Requests","/admin/quick-quotes"],b2b_enquiry:["B2B Enquiries","/admin/b2b-enquiries"],corporate:["Corporate Leads","/admin/leads?kind=corporate"],school:["School / College Leads","/admin/leads?kind=school"]};
const contactedStatuses=new Set(["contacted","qualified","quotation_sent","follow-up","converted","lost","closed"]);

export default function AdminDashboard(){
 const [state,setState]=useState({leads:[],loading:true,error:""});
 useEffect(()=>{fetch("/api/admin/leads?summary=1",{headers:{Authorization:`Bearer ${token()}`}}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setState({leads:data.leads||[],loading:false,error:""})}).catch(error=>setState({leads:[],loading:false,error:error.message}))},[]);
 const data=useMemo(()=>{const totals={};for(const lead of state.leads){const entry=totals[lead.kind]||{total:0,contacted:0,pending:0};entry.total++;if(contactedStatuses.has(lead.status))entry.contacted++;else entry.pending++;totals[lead.kind]=entry}return totals},[state.leads]);
 const contacted=state.leads.filter(lead=>contactedStatuses.has(lead.status)).length,pending=state.leads.length-contacted;
 const summary=[{label:"Total leads",value:state.leads.length,icon:Users,to:"/admin/leads"},{label:"Contacted",value:contacted,icon:CheckCircle2,to:"/admin/leads?status=contacted"},{label:"Pending / not contacted",value:pending,icon:Clock3,to:"/admin/leads?status=new"}];
 return <div><div className="mb-8"><h1 className="font-display text-2xl font-semibold text-navy-900">Lead Dashboard</h1><p className="mt-1 text-sm text-navy-500">Live counts from stored enquiries; no sample metrics.</p></div>{state.loading&&<p role="status" className="mb-5 rounded-xl bg-white p-4 text-sm">Loading live lead counts…</p>}{state.error&&<p role="alert" className="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{state.error}</p>}<div className="grid gap-4 sm:grid-cols-3">{summary.map(item=><Link key={item.label} to={item.to} className="rounded-2xl border bg-white p-5 shadow-soft hover:border-orange-300"><item.icon size={18} className="text-orange-600"/><strong className="mt-3 block font-display text-3xl">{item.value}</strong><span className="text-sm text-slate-500">{item.label}</span></Link>)}</div><section className="mt-8 rounded-2xl border bg-white p-5"><h2 className="font-display text-xl">Leads by type</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">Lead type</th><th className="p-3 text-right">Total</th><th className="p-3 text-right">Contacted</th><th className="p-3 text-right">Pending</th><th className="p-3 text-right">Open</th></tr></thead><tbody>{Object.entries(kinds).filter(([kind])=>data[kind]?.total).map(([kind,[label,to]])=><tr key={kind} className="border-b"><td className="p-3 font-semibold">{label}</td><td className="p-3 text-right">{data[kind].total}</td><td className="p-3 text-right">{data[kind].contacted}</td><td className="p-3 text-right">{data[kind].pending}</td><td className="p-3 text-right"><Link to={to} className="inline-flex items-center gap-1 font-bold text-orange-700">View <ArrowRight size={13}/></Link></td></tr>)}</tbody></table>{!state.loading&&!state.leads.length&&<p className="p-8 text-center text-slate-400">No stored leads.</p>}</div></section></div>;
}
