import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Save, Trash2, X } from "lucide-react";
import MediaUploader from "../../components/admin/MediaUploader";
import { loadSiteSettings, saveSiteSettings } from "../../data/siteConfig";
import { TableSkeleton } from "../../components/shared/Loading";

const blank={title:"",shortDescription:"",description:"",category:"",location:"",startDate:"",endDate:"",startTime:"",image:"",ctaLabel:"",ctaTarget:"",published:false,featured:false,displayOrder:0};
export default function AdminEvents(){
 const [settings,setSettings]=useState(null),[form,setForm]=useState(blank),[editing,setEditing]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{setBusy(true);loadSiteSettings().then(setSettings).catch((error)=>setMessage(error.message)).finally(()=>setBusy(false))},[]);
 const items=useMemo(()=>[...(settings?.events||[])].sort((a,b)=>Number(a.displayOrder||0)-Number(b.displayOrder||0)||String(a.startDate).localeCompare(String(b.startDate))),[settings]);
 const start=(item=null)=>{setEditing(item?.id||"");setForm(item?{...blank,...item}:blank);setOpen(true)};
 const persist=async(events,notice)=>{const next={...settings,events};await saveSiteSettings(next);setSettings(next);setMessage(notice)};
 const save=async(event)=>{event.preventDefault();if(busy)return;setBusy(true);try{const id=editing||crypto.randomUUID();const item={...form,id,displayOrder:Number(form.displayOrder||0)};let events=editing?items.map((value)=>value.id===editing?item:value):[...items,item];if(item.featured)events=events.map((value)=>({...value,featured:value.id===id}));await persist(events,"Event saved.");setOpen(false)}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 const remove=async(id)=>{if(!confirm("Delete this event?"))return;setBusy(true);try{await persist(items.filter((item)=>item.id!==id),"Event deleted.")}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 const toggle=async(item)=>{setBusy(true);try{await persist(items.map((value)=>value.id===item.id?{...value,published:!value.published}:value),"Event status updated.")}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 if(!settings&&busy)return <TableSkeleton/>;
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-2xl">Events</h1><p className="mt-1 text-sm text-slate-500">Manage upcoming events and the lightweight homepage alert.</p></div><button onClick={()=>start()} className="btn-primary"><Plus size={15}/>Add event</button></div>{message&&<p role="status" className="mt-4 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}<div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b bg-slate-50 text-left"><th className="p-4">Event</th><th className="p-4">Category</th><th className="p-4">Date</th><th className="p-4">Location</th><th className="p-4">Featured</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map((item)=><tr key={item.id} className="border-b"><td className="p-4"><strong>{item.title}</strong><span className="block max-w-xs truncate text-xs text-slate-500">{item.shortDescription}</span></td><td className="p-4">{item.category||"—"}</td><td className="p-4">{item.startDate}{item.endDate?` – ${item.endDate}`:""}</td><td className="p-4">{item.location||"—"}</td><td className="p-4">{item.featured?"Yes":"No"}</td><td className="p-4"><button disabled={busy} onClick={()=>toggle(item)} className="btn-secondary px-3 py-2">{item.published?"Published":"Draft"}</button></td><td className="p-4"><div className="flex gap-2"><button onClick={()=>start(item)} className="btn-secondary px-3"><Pencil size={14}/>Edit</button><button onClick={()=>remove(item.id)} className="btn-secondary px-3 text-rose-600"><Trash2 size={14}/>Delete</button></div></td></tr>)}{!items.length&&<tr><td colSpan="7" className="p-10 text-center text-slate-400">No events configured. Nothing will be shown publicly.</td></tr>}</tbody></table></div>
 {open&&<div className="fixed inset-0 z-50 grid place-items-center p-4"><button className="absolute inset-0 bg-slate-950/60" aria-label="Close" onClick={()=>setOpen(false)}/><section className="relative max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 sm:p-8"><button className="absolute right-5 top-5" onClick={()=>setOpen(false)}><X/></button><h2 className="font-display text-2xl">{editing?"Edit":"Add"} event</h2><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2">{[["Event title","title","text",true],["Category","category","text",false],["Location","location","text",false],["Start date","startDate","date",true],["End date","endDate","date",false],["Start time","startTime","time",false],["CTA label","ctaLabel","text",false],["CTA target / link","ctaTarget","text",false]].map(([label,key,type,required])=><label key={key}><span className="label-field">{label}</span><input required={required} type={type} value={form[key]} onChange={(event)=>setForm({...form,[key]:event.target.value})} className="input-field" placeholder={key==="ctaTarget"?"/custom-trip or https://…":undefined}/></label>)}<label><span className="label-field">Display order</span><input type="number" value={form.displayOrder} onChange={(event)=>setForm({...form,displayOrder:event.target.value})} className="input-field"/></label><label className="sm:col-span-2"><span className="label-field">Short description</span><textarea required rows="2" value={form.shortDescription} onChange={(event)=>setForm({...form,shortDescription:event.target.value})} className="input-field"/></label><label className="sm:col-span-2"><span className="label-field">Full description / details</span><textarea rows="5" value={form.description} onChange={(event)=>setForm({...form,description:event.target.value})} className="input-field"/></label><div className="sm:col-span-2"><MediaUploader label="Event banner" value={form.image} onChange={(image)=>setForm({...form,image})} scope={`events/${editing||"draft"}`} context={form.title}/></div><div className="flex flex-wrap gap-5 sm:col-span-2"><label className="flex gap-2"><input type="checkbox" checked={form.published} onChange={(event)=>setForm({...form,published:event.target.checked})}/>Published</label><label className="flex gap-2"><input type="checkbox" checked={form.featured} onChange={(event)=>setForm({...form,featured:event.target.checked})}/>Featured homepage alert</label></div><button disabled={busy} className="btn-primary sm:col-span-2"><Save size={15}/>{busy?"Saving…":"Save event"}</button></form></section></div>}
 </div>;
}
