import { useEffect, useMemo, useState } from "react";
import { Download, Eye, Mail, MessageCircle, Plus, Save, Send, Trash2 } from "lucide-react";
import { downloadInvoiceDocument } from "../../utils/portal";

const token=()=>sessionStorage.getItem("naystrip_admin_session");
const api=async(path,options={})=>{const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Request failed");return data};
const blankLine=()=>({description:"",travellerDetails:"",quantity:"",rate:"",amount:""});
const blank=()=>({invoiceDate:new Date().toISOString().slice(0,10),bookingReference:"",billing:{name:"",companyName:"",address:"",city:"",state:"",postalCode:"",email:"",phone:"",gstNumber:""},lineItems:[blankLine()],charges:{convenienceFee:0,serviceFee:0,managementFee:0,discount:0,tax:0,tds:0,adjustments:0},paid:0,netAmount:null,notes:""});
const money=value=>Number(value||0).toLocaleString("en-IN",{maximumFractionDigits:2});

export default function AdminInvoices(){
 const [bookings,setBookings]=useState([]),[invoices,setInvoices]=useState([]),[invoice,setInvoice]=useState(null),[data,setData]=useState(blank()),[bookingId,setBookingId]=useState(new URLSearchParams(location.search).get("booking")||""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);try{const [bookingData,invoiceData]=await Promise.all([api("/api/admin/bookings"),api("/api/admin/invoices")]);setBookings(bookingData.bookings||[]);setInvoices(invoiceData.invoices||[])}catch(err){setError(err.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const total=useMemo(()=>{const subtotal=data.lineItems.reduce((sum,item)=>sum+Number(item.amount||0),0),charges=data.charges||{};return data.netAmount==null||data.netAmount===""?subtotal+Number(charges.convenienceFee||0)+Number(charges.serviceFee||0)+Number(charges.managementFee||0)+Number(charges.tax||0)+Number(charges.tds||0)+Number(charges.adjustments||0)-Number(charges.discount||0):Number(data.netAmount)},[data]);
 const choose=record=>{setInvoice(record);setBookingId(record.booking_id||"");setData({...blank(),...(record.invoice_data||{}),invoiceDate:record.invoice_date||record.invoice_data?.invoiceDate,charges:{...blank().charges,...(record.invoice_data?.charges||{})},billing:{...blank().billing,...(record.invoice_data?.billing||{})}});setError("");setMessage("")};
 const create=async()=>{setBusy(true);setError("");try{const result=await api("/api/admin/invoices",{method:"POST",body:JSON.stringify({bookingId:bookingId||null,invoiceData:bookingId?{}:data})});choose(result.invoice);setInvoices(items=>[result.invoice,...items]);setMessage("Invoice draft created") }catch(err){setError(err.message)}finally{setBusy(false)}};
 const save=async(finalize=false)=>{if(!invoice)return setError("Create an invoice draft first");setBusy(true);setError("");try{const result=await api("/api/admin/invoices",{method:"PATCH",body:JSON.stringify({id:invoice.id,action:finalize?"finalize":"save",invoiceData:{...data,netAmount:data.netAmount==null?total:data.netAmount}})});choose(result.invoice);await load();setMessage(finalize?"Invoice finalized and ready for delivery":"Invoice draft saved")}catch(err){setError(err.message)}finally{setBusy(false)}};
 const updateLine=(index,field,value)=>setData(current=>({...current,lineItems:current.lineItems.map((item,itemIndex)=>itemIndex===index?{...item,[field]:value,...(["quantity","rate"].includes(field)?{amount:Number(field==="quantity"?value:item.quantity||0)*Number(field==="rate"?value:item.rate||0)}:{})}:item)}));
 const deliver=async(action)=>{if(!invoice||invoice.status!=="finalized")return setError("Finalize the invoice before delivery");setBusy(true);setError("");try{const result=await api("/api/admin/document-delivery",{method:"POST",body:JSON.stringify({action,invoiceId:invoice.id,documentType:"invoice",recipient:data.billing?.email,phone:data.billing?.phone})});if(action==="whatsapp")window.open(result.url,"_blank","noopener,noreferrer");else setMessage(`Invoice emailed to ${result.recipient}`)}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="font-display text-3xl">Invoices</h1><p className="text-sm text-slate-500">Create editable booking-linked or manual invoices, then finalize and deliver.</p></div><button onClick={()=>{setInvoice(null);setBookingId("");setData(blank());setMessage("")}} className="btn-primary"><Plus size={15}/>CREATE INVOICE</button></div>
 {error&&<p role="alert" className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{message&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}
 <div className="mt-6 grid gap-6 xl:grid-cols-[300px_1fr]"><aside className="rounded-2xl border bg-white p-4"><label className="text-xs font-bold">Link booking (optional)<select value={bookingId} onChange={event=>setBookingId(event.target.value)} disabled={Boolean(invoice)} className="input-field mt-2"><option value="">Manual invoice</option>{bookings.map(item=><option key={item.id} value={item.id}>{item.reference} - {item.billing?.name}</option>)}</select></label>{!invoice&&<button disabled={busy} onClick={create} className="btn-primary mt-3 w-full">Create draft</button>}<h2 className="mt-6 text-xs font-bold uppercase tracking-wide text-slate-500">Recent invoices</h2><div className="mt-2 grid gap-2">{invoices.map(item=><button key={item.id} onClick={()=>choose(item)} className={`rounded-xl border p-3 text-left ${invoice?.id===item.id?"border-orange-400 bg-orange-50":""}`}><strong className="block text-sm">{item.invoice_number}</strong><span className="text-xs text-slate-500">{item.booking?.reference||"Manual"} - {item.status}</span></button>)}</div></aside>
 <main className="rounded-2xl border bg-white p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs text-slate-400">{invoice?.invoice_number||"NEW INVOICE"}</p><h2 className="font-display text-2xl">Invoice Builder</h2></div>{invoice&&<span className={`rounded-full px-3 py-1 text-xs font-bold uppercase ${invoice.status==="finalized"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{invoice.status}</span>}</div>
 <div className="mt-5 grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold">Invoice date<input type="date" value={data.invoiceDate||""} onChange={event=>setData({...data,invoiceDate:event.target.value})} className="input-field mt-1"/></label><label className="text-xs font-bold sm:col-span-2">Booking reference<input value={data.bookingReference||""} onChange={event=>setData({...data,bookingReference:event.target.value})} className="input-field mt-1"/></label></div>
 <h3 className="mt-7 font-bold">Billing information</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{[["name","Customer name"],["companyName","Company name"],["email","Email"],["phone","Phone"],["address","Address"],["city","City"],["state","State"],["postalCode","Postal code"],["gstNumber","GSTIN (only if supplied)"]].map(([field,label])=><label key={field} className="text-xs font-semibold">{label}<input value={data.billing?.[field]||""} onChange={event=>setData({...data,billing:{...data.billing,[field]:event.target.value}})} className="input-field mt-1"/></label>)}</div>
 <div className="mt-7 flex items-center justify-between"><h3 className="font-bold">Service details / line items</h3><button onClick={()=>setData({...data,lineItems:[...data.lineItems,blankLine()]})} className="btn-secondary"><Plus size={14}/>Add line item</button></div><div className="mt-2 grid gap-3">{data.lineItems.map((item,index)=><div key={index} className="grid gap-2 rounded-xl bg-navy-50 p-3 sm:grid-cols-12"><input value={item.description} onChange={event=>updateLine(index,"description",event.target.value)} placeholder="Description / hotel / package / service" className="input-field sm:col-span-4"/><input value={item.travellerDetails||""} onChange={event=>updateLine(index,"travellerDetails",event.target.value)} placeholder="Traveller / guest details" className="input-field sm:col-span-3"/><input type="number" min="0" value={item.quantity} onChange={event=>updateLine(index,"quantity",event.target.value)} placeholder="1" className="input-field sm:col-span-1"/><input type="number" min="0" value={item.rate} onChange={event=>updateLine(index,"rate",event.target.value)} placeholder="Rate" className="input-field sm:col-span-2"/><input type="number" min="0" value={item.amount} onChange={event=>updateLine(index,"amount",event.target.value)} placeholder="10000" className="input-field sm:col-span-1"/><button aria-label="Remove line item" disabled={data.lineItems.length===1} onClick={()=>setData({...data,lineItems:data.lineItems.filter((_,itemIndex)=>itemIndex!==index)})} className="grid place-items-center text-rose-600"><Trash2 size={16}/></button></div>)}</div>
 <h3 className="mt-7 font-bold">Charges and totals</h3><div className="mt-2 grid gap-2 sm:grid-cols-3">{[["convenienceFee","Convenience fee"],["serviceFee","Service fee"],["managementFee","Management fee"],["discount","Discount"],["tax","Tax / GST (configured only)"],["tds","TDS (when applicable)"],["adjustments","Adjustments"]].map(([field,label])=><label key={field} className="text-xs font-semibold">{label}<input type="number" value={data.charges?.[field]||0} onChange={event=>setData({...data,charges:{...data.charges,[field]:event.target.value}})} className="input-field mt-1"/></label>)}<label className="text-xs font-semibold">Paid<input type="number" min="0" value={data.paid||0} onChange={event=>setData({...data,paid:event.target.value})} className="input-field mt-1"/></label><label className="text-xs font-semibold">Net amount override<input type="number" min="0" value={data.netAmount??""} onChange={event=>setData({...data,netAmount:event.target.value})} placeholder={String(total)} className="input-field mt-1"/></label></div><div className="mt-4 rounded-xl bg-[#173c34] p-4 text-white"><span className="text-xs uppercase text-white/60">Net amount</span><strong className="block text-2xl">INR {money(total)}</strong><span className="text-xs">Paid INR {money(data.paid)} - Balance INR {money(Math.max(0,total-Number(data.paid||0)))}</span></div><label className="mt-4 block text-xs font-semibold">Notes<textarea value={data.notes||""} onChange={event=>setData({...data,notes:event.target.value})} rows="3" className="input-field mt-1"/></label>
 <div className="mt-6 flex flex-wrap gap-2"><button disabled={busy||!invoice} onClick={()=>save(false)} className="btn-secondary"><Save size={14}/>Save Draft</button><button disabled={busy||!invoice} onClick={()=>save(true)} className="btn-primary"><Send size={14}/>Generate / Finalize</button><button disabled={!invoice} onClick={()=>downloadInvoiceDocument(invoice.id,"pdf",true)} className="btn-secondary"><Eye size={14}/>Preview</button><button disabled={!invoice} onClick={()=>downloadInvoiceDocument(invoice.id,"pdf")} className="btn-secondary"><Download size={14}/>PDF</button><button disabled={!invoice} onClick={()=>downloadInvoiceDocument(invoice.id,"docx")} className="btn-secondary"><Download size={14}/>Word</button><button disabled={busy||invoice?.status!=="finalized"} onClick={()=>deliver("email")} className="btn-secondary"><Mail size={14}/>Email</button><button disabled={busy||invoice?.status!=="finalized"} onClick={()=>deliver("whatsapp")} className="btn-secondary"><MessageCircle size={14}/>WhatsApp</button></div></main></div></div>;
}
