import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Save, Trash2, X } from "lucide-react";
import MediaUploader from "../../components/admin/MediaUploader";
import { loadSiteSettings, saveSiteSettings } from "../../data/siteConfig";
import { TableSkeleton } from "../../components/shared/Loading";

const blank={title:"",type:"trip",destination:"",duration:"",description:"",image:"",packageSlug:"",displayOrder:0,published:false,recommended:false,label:""};
export default function AdminMonthlyPicks(){
 const [settings,setSettings]=useState(null),[packages,setPackages]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{setBusy(true);try{const [site,response]=await Promise.all([loadSiteSettings(),fetch("/api/admin/packages",{headers:{Authorization:`Bearer ${sessionStorage.getItem("naystrip_admin_session")}`}})]);const data=await response.json();if(!response.ok)throw new Error(data.error);setSettings(site);setPackages(data.packages||[])}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const items=useMemo(()=>[...(settings?.monthlyPicks||[])].sort((a,b)=>Number(a.displayOrder||0)-Number(b.displayOrder||0)),[settings]);
 const start=(item=null)=>{setEditing(item?.id||"");setForm(item?{...blank,...item}:blank);setOpen(true)};
 const save=async(event)=>{event.preventDefault();if(busy)return;setBusy(true);try{const id=editing||crypto.randomUUID();const item={...form,id,displayOrder:Number(form.displayOrder||0)};const monthlyPicks=editing?items.map((value)=>value.id===editing?item:value):[...items,item];const next={...settings,monthlyPicks};await saveSiteSettings(next);setSettings(next);setOpen(false);setMessage("Monthly pick saved.")}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 const remove=async(id)=>{if(!confirm("Delete this monthly pick? The linked package will not be deleted."))return;setBusy(true);try{const next={...settings,monthlyPicks:items.filter((item)=>item.id!==id)};await saveSiteSettings(next);setSettings(next);setMessage("Monthly pick deleted.")}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 const toggle=async(item)=>{setBusy(true);try{const next={...settings,monthlyPicks:items.map((value)=>value.id===item.id?{...value,published:!value.published}:value)};await saveSiteSettings(next);setSettings(next)}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 if(!settings&&busy)return <TableSkeleton/>;
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-2xl">Top Trips & Treks</h1><p className="mt-1 text-sm text-slate-500">Manage this month’s homepage picks without duplicating package records.</p></div><button onClick={()=>start()} className="btn-primary"><Plus size={15}/>Add pick</button></div>{message&&<p role="status" className="mt-4 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}<div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b bg-slate-50 text-left"><th className="p-4">Order</th><th className="p-4">Title</th><th className="p-4">Type</th><th className="p-4">Linked package</th><th className="p-4">Recommended</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map((item)=><tr key={item.id} className="border-b"><td className="p-4">{item.displayOrder}</td><td className="p-4"><strong>{item.title}</strong><span className="block text-xs text-slate-500">{item.destination} {item.duration&&`· ${item.duration}`}</span></td><td className="p-4 capitalize">{item.type}</td><td className="p-4">{packages.find((pkg)=>pkg.slug===item.packageSlug)?.title||item.packageSlug||"Custom enquiry"}</td><td className="p-4">{item.recommended?"Yes":"No"}</td><td className="p-4"><button disabled={busy} onClick={()=>toggle(item)} className="btn-secondary px-3 py-2">{item.published?"Published":"Draft"}</button></td><td className="p-4"><div className="flex gap-2"><button onClick={()=>start(item)} className="btn-secondary px-3"><Pencil size={14}/>Edit</button><button onClick={()=>remove(item.id)} className="btn-secondary px-3 text-rose-600"><Trash2 size={14}/>Delete</button></div></td></tr>)}{!items.length&&<tr><td colSpan="7" className="p-10 text-center text-slate-400">No monthly picks configured. The homepage section stays hidden.</td></tr>}</tbody></table></div>
 {open&&<div className="fixed inset-0 z-50 grid place-items-center p-4"><button className="absolute inset-0 bg-slate-950/60" aria-label="Close" onClick={()=>setOpen(false)}/><section className="relative max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 sm:p-8"><button className="absolute right-5 top-5" onClick={()=>setOpen(false)}><X/></button><h2 className="font-display text-2xl">{editing?"Edit":"Add"} monthly pick</h2><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="label-field">Linked package</span><select value={form.packageSlug} onChange={(event)=>{const pkg=packages.find((value)=>value.slug===event.target.value);setForm({...form,packageSlug:event.target.value,...(pkg?{title:pkg.title,destination:(pkg.destination_names||[]).join(", "),duration:`${pkg.nights}N/${pkg.days}D`,image:pkg.hero_image||form.image,type:["trek","expedition"].includes(pkg.package_type)?"trek":"trip"}:{})})}} className="input-field"><option value="">No linked package</option>{packages.map((pkg)=><option key={pkg.id} value={pkg.slug}>{pkg.title}</option>)}</select></label><label><span className="label-field">Type</span><select value={form.type} onChange={(event)=>setForm({...form,type:event.target.value})} className="input-field"><option value="trip">Trip</option><option value="trek">Trek</option></select></label>{[["Title","title"],["Destination","destination"],["Duration","duration"],["Optional month label","label"]].map(([label,key])=><label key={key}><span className="label-field">{label}</span><input required={key==="title"} value={form[key]} onChange={(event)=>setForm({...form,[key]:event.target.value})} className="input-field"/></label>)}<label><span className="label-field">Display order</span><input type="number" value={form.displayOrder} onChange={(event)=>setForm({...form,displayOrder:event.target.value})} className="input-field"/></label><label className="sm:col-span-2"><span className="label-field">Short description</span><textarea rows="3" value={form.description} onChange={(event)=>setForm({...form,description:event.target.value})} className="input-field"/></label><div className="sm:col-span-2"><MediaUploader label="Image" value={form.image} onChange={(image)=>setForm({...form,image})} scope={`monthly-picks/${editing||"draft"}`} context={form.title}/></div><div className="flex flex-wrap gap-5 sm:col-span-2"><label className="flex gap-2"><input type="checkbox" checked={form.published} onChange={(event)=>setForm({...form,published:event.target.checked})}/>Published</label><label className="flex gap-2"><input type="checkbox" checked={form.recommended} onChange={(event)=>setForm({...form,recommended:event.target.checked})}/>Recommended by NaysTrip</label></div><button disabled={busy} className="btn-primary sm:col-span-2"><Save size={15}/>{busy?"Saving…":"Save pick"}</button></form></section></div>}
 </div>;
}
