import {useState} from "react";

const common={customer:"",reference:"",contact:"",status:"Confirmed",notes:"",inclusions:"",amount:""};
const initial={
 hotel:{...common,hotel:"",location:"",category:"",checkIn:"",checkInTime:"",checkOut:"",checkOutTime:"",duration:"",accommodation:"",rooms:"",guests:"",roomType:"",occupancy:"",guestNames:"",mealPlan:"",baseAmount:"",taxes:"",fees:"",policyNotes:""},
 taxi:{...common,travelDate:"",pickup:"",drop:"",pickupTime:"",vehicle:"",driver:"",passengers:"",duration:"",kilometres:"",room:"",sightseeing:"",route:"",itinerary:""},
};
const labels={customer:"Customer / lead traveller",reference:"Booking reference",contact:"Customer contact",status:"Confirmation status",notes:"Important notes",inclusions:"Inclusions",amount:"Total amount",hotel:"Hotel name",location:"Hotel location",category:"Category",checkIn:"Check-in date",checkInTime:"Check-in time",checkOut:"Check-out date",checkOutTime:"Check-out time",duration:"Duration",accommodation:"Accommodation",rooms:"Rooms",guests:"Guests",roomType:"Room type",occupancy:"Occupancy",guestNames:"Guest names",mealPlan:"Meal plan",baseAmount:"Base amount",taxes:"Taxes",fees:"Other fees",policyNotes:"Approved policy / cancellation notes",travelDate:"Travel date",pickup:"Pickup",drop:"Drop",pickupTime:"Pickup time",vehicle:"Vehicle",driver:"Driver and contact",passengers:"Passengers",kilometres:"Kilometres",room:"Driver room / night arrangement",sightseeing:"Sightseeing",route:"Route",itinerary:"Detailed itinerary"};
const multiline=new Set(["notes","inclusions","policyNotes","guestNames","sightseeing","route","itinerary"]);
const dateFields=new Set(["checkIn","checkOut","travelDate"]);const timeFields=new Set(["checkInTime","checkOutTime","pickupTime"]);

export default function AdminVouchers(){
 const [type,setType]=useState("hotel");const [forms,setForms]=useState(initial);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const form=forms[type];
 const change=(key,value)=>setForms(current=>({...current,[type]:{...current[type],[key]:value}}));
 const submit=async(event)=>{event.preventDefault();if(busy)return;setBusy(true);setMessage("Generating…");try{const response=await fetch("/api/documents/service-voucher",{method:"POST",headers:{Authorization:`Bearer ${sessionStorage.getItem("naystrip_admin_session")}`,"Content-Type":"application/json"},body:JSON.stringify({type,fields:form})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"Voucher could not be generated")};const url=URL.createObjectURL(await response.blob());const anchor=document.createElement("a");anchor.href=url;anchor.download=`${form.reference}-${type}-voucher.pdf`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("Voucher generated and downloaded.")}catch(error){setMessage(error.message)}finally{setBusy(false)}};
 return <div><h1 className="font-display text-2xl">Service Voucher Generator</h1><p className="mt-1 text-sm text-navy-500">Create branded hotel and taxi / transport vouchers from confirmed reservation details.</p><div className="mt-6 flex gap-2">{["hotel","taxi"].map(item=><button type="button" key={item} onClick={()=>setType(item)} className={type===item?"btn-primary capitalize":"btn-secondary capitalize"}>{item==="taxi"?"Taxi / transport":item} voucher</button>)}</div><form onSubmit={submit} className="mt-5 rounded-2xl border bg-white p-6"><div className="grid gap-4 sm:grid-cols-2">{Object.keys(form).map(key=><label key={key} className={multiline.has(key)?"sm:col-span-2":""}><span className="label-field">{labels[key]}</span>{multiline.has(key)?<textarea rows={key==="itinerary"?6:3} value={form[key]} onChange={event=>change(key,event.target.value)} className="input-field"/>:<input required={["customer","reference"].includes(key)} type={dateFields.has(key)?"date":timeFields.has(key)?"time":"text"} value={form[key]} onChange={event=>change(key,event.target.value)} className="input-field"/>}</label>)}</div><button disabled={busy} className="btn-primary mt-6">{busy?"Generating…":"Generate branded PDF"}</button>{message&&<p role="status" className="mt-4 text-sm text-navy-600">{message}</p>}</form></div>;
}
