import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Eye, RefreshCw, Search, X } from "lucide-react";
import { getContactLeads, getCustomLeads, updateCustomLeadStatus } from "../../utils/storage";

const statuses=["new","contacted","follow-up","converted","closed"];
const label=(value)=>value?value.charAt(0).toUpperCase()+value.slice(1):"—";
const payload=(lead)=>{const raw=lead.payload||{};return Object.fromEntries(Object.entries(raw).map(([key,value])=>{if(typeof value==="string"&&(value.startsWith("{")||value.startsWith("[")))try{return [key,JSON.parse(value)]}catch{return [key,value]}return [key,value]}))};
const csvCell=(value)=>`"${String(value??"").replaceAll('"','""')}"`;

export default function AdminLeads({kind="custom_trip"}){
 const [leads,setLeads]=useState([]);const [viewing,setViewing]=useState(null);const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [source,setSource]=useState("");const [fromDate,setFromDate]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [note,setNote]=useState("");const [followUpAt,setFollowUpAt]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setLeads(await (kind==="contact"?getContactLeads():getCustomLeads()))}catch(err){setError(err.message)}finally{setLoading(false)}},[kind]);useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>leads.filter((lead)=>{const p=payload(lead);if(status&&lead.status!==status)return false;if(source&&!lead.source?.toLowerCase().includes(source.toLowerCase()))return false;if(fromDate&&new Date(lead.created_at)<new Date(fromDate))return false;return !search||`${lead.id} ${lead.name} ${lead.phone} ${lead.email} ${lead.destination} ${p.from} ${p.to}`.toLowerCase().includes(search.toLowerCase())}),[leads,search,status,source,fromDate]);
 const update=async(lead,nextStatus)=>{try{await updateCustomLeadStatus(lead.id,nextStatus,note,followUpAt||null);setNote("");setFollowUpAt("");await load();setViewing((current)=>current?{...current,status:nextStatus}:null)}catch(err){setError(err.message)}};
 const exportCsv=()=>{const rows=[["ID","Name","Phone","Email","Destination","Source","Status","Created"],...filtered.map((lead)=>[lead.id,lead.name,lead.phone,lead.email,lead.destination,lead.source,lead.status,lead.created_at])];const blob=new Blob([rows.map((row)=>row.map(csvCell).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`naystrip-leads-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)};
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-2xl font-semibold text-navy-900">Custom Trip Leads</h1><p className="mt-1 text-sm text-navy-500">Database-backed enquiries, attribution and follow-up.</p></div><div className="flex gap-2"><button onClick={load} className="btn-secondary"><RefreshCw size={15}/>Refresh</button><button onClick={exportCsv} disabled={!filtered.length} className="btn-primary"><Download size={15}/>Export CSV</button></div></div>
 {error&&<p role="alert" className="mt-4 bg-terracotta-50 p-3 text-sm text-terracotta-700">{error}</p>}
 <div className="my-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="relative"><Search size={15} className="absolute left-3.5 top-3 text-navy-400"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search name, phone, destination…" className="input-field pl-9"/></label><select value={status} onChange={(e)=>setStatus(e.target.value)} className="input-field"><option value="">All statuses</option>{statuses.map((item)=><option value={item} key={item}>{label(item)}</option>)}</select><input value={source} onChange={(e)=>setSource(e.target.value)} placeholder="Filter source / UTM" className="input-field"/><label><span className="sr-only">Created from</span><input type="date" value={fromDate} onChange={(e)=>setFromDate(e.target.value)} className="input-field"/></label></div>
 <div className="overflow-x-auto rounded-2xl border border-navy-100 bg-white shadow-soft"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b bg-navy-50/40 text-left text-xs text-navy-400"><th className="p-4">Reference</th><th className="p-4">Customer</th><th className="p-4">Destination</th><th className="p-4">Source</th><th className="p-4">Received</th><th className="p-4">Status</th><th className="p-4 text-right">View</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="p-10 text-center">Loading leads…</td></tr>:filtered.length?filtered.map((lead)=><tr key={lead.id} className="border-b border-navy-50"><td className="p-4 font-mono text-xs">{lead.id}</td><td className="p-4"><strong className="block">{lead.name}</strong><a href={`tel:${lead.phone}`} className="text-navy-500">{lead.phone}</a></td><td className="p-4">{lead.destination||"—"}</td><td className="p-4 text-xs">{lead.source||"Website"}</td><td className="p-4">{new Date(lead.created_at).toLocaleString("en-IN")}</td><td className="p-4"><select value={lead.status} onChange={(e)=>update(lead,e.target.value)} className="input-field py-2">{statuses.map((item)=><option key={item} value={item}>{label(item)}</option>)}</select></td><td className="p-4 text-right"><button onClick={()=>{setViewing(lead);setNote("");setFollowUpAt(lead.follow_up_at?.slice(0,16)||"")}} className="grid h-9 w-9 place-items-center rounded-lg bg-navy-50"><Eye size={15}/></button></td></tr>):<tr><td colSpan="7" className="p-10 text-center text-navy-400">No matching leads.</td></tr>}</tbody></table></div>
 {viewing&&<div className="fixed inset-0 z-50 grid place-items-center p-4"><button className="absolute inset-0 bg-navy-950/65" onClick={()=>setViewing(null)} aria-label="Close lead details"/><section role="dialog" aria-modal="true" className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 sm:p-8"><button onClick={()=>setViewing(null)} className="absolute right-5 top-5"><X/></button><h2 className="font-display text-2xl">{viewing.name}</h2><p className="mt-1 font-mono text-xs text-navy-400">{viewing.id}</p><dl className="mt-6 grid gap-3 text-sm sm:grid-cols-2">{Object.entries({Phone:viewing.phone,Email:viewing.email,Destination:viewing.destination,Source:viewing.source,Status:label(viewing.status),...payload(viewing)}).map(([key,value])=><div key={key} className="border-b border-navy-100 pb-2"><dt className="text-xs uppercase text-navy-400">{key}</dt><dd className="mt-1 break-words font-medium">{typeof value==="object"?JSON.stringify(value):value||"—"}</dd></div>)}</dl><div className="mt-7 grid gap-4 sm:grid-cols-2"><label><span className="label-field">Follow-up</span><input type="datetime-local" value={followUpAt} onChange={(e)=>setFollowUpAt(e.target.value)} className="input-field"/></label><label className="sm:col-span-2"><span className="label-field">Internal note</span><textarea rows="3" value={note} onChange={(e)=>setNote(e.target.value)} className="input-field" placeholder="Call outcome, preferences, quotation notes…"/></label><button onClick={()=>update(viewing,viewing.status)} className="btn-primary sm:col-span-2">Save follow-up note</button></div></section></div>}
 </div>;
}
