import {useEffect,useMemo,useState} from "react";
import {Download,Eye,Mail,MessageCircle,RefreshCw,Search,Send,Upload,X} from "lucide-react";
import {downloadProtectedDocument,downloadStoredDocument,previewProtectedDocument} from "../../utils/portal";
const token=()=>sessionStorage.getItem("naystrip_admin_session");
const request=async(path,options={})=>{const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data};
const statuses=["draft","pending_payment","payment_verification","confirmed","partially_paid","fully_paid","on_hold","completed","cancelled","refund_pending","refunded"];
export default function AdminBookings(){
 const [bookings,setBookings]=useState([]),[viewing,setViewing]=useState(null),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[payment,setPayment]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 const [manual,setManual]=useState({amount:"",method:"bank_transfer",reference:""});const [upload,setUpload]=useState({file:null,type:"ticket",name:""});const [recipient,setRecipient]=useState("");const [docDetails,setDocDetails]=useState({hotel_voucher:{},transport_voucher:{}});
 const load=async()=>{setBusy(true);try{setBookings((await request("/api/admin/bookings")).bookings)}catch(err){setError(err.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const details=async(id)=>{setBusy(true);try{const booking=(await request(`/api/admin/bookings?id=${id}`)).booking;setViewing(booking);setRecipient(booking.billing?.email||"");setDocDetails({hotel_voucher:booking.document_details?.hotel_voucher||{},transport_voucher:booking.document_details?.transport_voucher||{}})}catch(err){setError(err.message)}finally{setBusy(false)}};
 const action=async(body)=>{setBusy(true);setError("");try{const data=await request("/api/admin/bookings",{method:"PATCH",body:JSON.stringify({id:viewing.id,...body})});if(data.notification?.status==="failed")throw new Error(data.notification.error||"Message delivery failed");await details(viewing.id);await load()}catch(err){setError(err.message)}finally{setBusy(false)}};
 const uploadDocument=async()=>{if(!upload.file)return setError("Choose a PDF to upload");setBusy(true);setError("");try{const response=await fetch("/api/admin/booking-documents",{method:"POST",headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/pdf","x-booking-id":viewing.id,"x-document-type":upload.type,"x-display-name":upload.name||upload.file.name.replace(/\.pdf$/i,""),"x-original-filename":upload.file.name},body:upload.file});const data=await response.json();if(!response.ok)throw new Error(data.error||"Upload failed");setUpload({file:null,type:"ticket",name:""});await details(viewing.id)}catch(err){setError(err.message)}finally{setBusy(false)}};
 const preview=async(type)=>{setError("");try{await previewProtectedDocument(viewing.reference,type,"pdf","admin")}catch(err){setError(err.message)}};
 const previewStored=async(item)=>{setError("");try{await downloadStoredDocument(item.id,item.original_filename||item.display_name,"admin",true)}catch(err){setError(err.message)}};
 const deliver=async(actionName,type,documentId=null)=>{setBusy(true);setError("");setMessage("");try{const data=await request("/api/admin/document-delivery",{method:"POST",body:JSON.stringify({action:actionName,bookingId:viewing.id,documentId,documentType:type,recipient,phone:viewing.billing?.phone})});if(actionName==="whatsapp")window.open(data.url,"_blank","noopener,noreferrer");else setMessage(`Email sent to ${data.recipient}`)}catch(err){setError(err.message)}finally{setBusy(false)}};
 const saveDocumentDetails=async()=>action({action:"save_document_details",documentDetails:docDetails});
 const filtered=useMemo(()=>bookings.filter(item=>(!status||item.operational_status===status)&&(!payment||item.payment_state===payment)&&(!search||`${item.reference} ${item.billing?.name} ${item.package?.title}`.toLowerCase().includes(search.toLowerCase()))),[bookings,search,status,payment]);
 return <div><div className="flex flex-wrap justify-between gap-4"><div><h1 className="font-display text-2xl">Booking Management</h1><p className="text-sm text-navy-500">Customers, payments, secure documents and operations.</p></div><button onClick={load} className="btn-secondary"><RefreshCw size={15}/>Refresh</button></div>
 {error&&<p role="alert" className="mt-4 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
 {message&&<p role="status" className="mt-4 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}
 <div className="my-5 grid gap-3 md:grid-cols-3"><label className="relative"><Search size={15} className="absolute left-3 top-3.5"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search reference or customer" className="input-field pl-9"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="input-field"><option value="">All booking statuses</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><select value={payment} onChange={e=>setPayment(e.target.value)} className="input-field"><option value="">All payment statuses</option>{["pending","failed","partially_paid","fully_paid","refunded"].map(item=><option key={item}>{item}</option>)}</select></div>
 <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left">{["Reference","Customer","Package","Travel","Payment","Status","View"].map(item=><th key={item} className="p-4">{item}</th>)}</tr></thead><tbody>{filtered.map(item=><tr key={item.id} className="border-b"><td className="p-4 font-mono text-xs">{item.reference}</td><td className="p-4">{item.billing?.name}</td><td className="p-4">{item.package?.title}</td><td className="p-4">{item.travel_date}</td><td className="p-4">INR {Number(item.amount_paid).toLocaleString("en-IN")} / {Number(item.total).toLocaleString("en-IN")}<span className="block text-xs">{item.payment_state}</span></td><td className="p-4">{item.operational_status}</td><td className="p-4"><button onClick={()=>details(item.id)} className="grid h-9 w-9 place-items-center bg-navy-50" aria-label={`View ${item.reference}`}><Eye size={15}/></button></td></tr>)}</tbody></table></div>
 {viewing&&<div className="fixed inset-0 z-50 grid place-items-center p-4"><button className="absolute inset-0 bg-navy-950/70" onClick={()=>setViewing(null)} aria-label="Close"/><section className="relative max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6 sm:p-8"><button onClick={()=>setViewing(null)} className="absolute right-5 top-5"><X/></button><p className="font-mono text-xs text-navy-400">{viewing.reference}</p><h2 className="mt-2 font-display text-3xl">{viewing.package?.title}</h2>
 <div className="mt-6 grid gap-4 sm:grid-cols-3">{Object.entries({Customer:viewing.billing?.name,Travel:viewing.travel_date,Travellers:viewing.traveller_count,Total:`INR ${Number(viewing.total).toLocaleString("en-IN")}`,Paid:`INR ${Number(viewing.amount_paid).toLocaleString("en-IN")}`,Balance:`INR ${Number(viewing.balance_due).toLocaleString("en-IN")}`}).map(([key,value])=><div className="bg-navy-50 p-4" key={key}><small>{key}</small><strong className="mt-1 block">{value}</strong></div>)}</div>
 <div className="mt-7 grid gap-5 lg:grid-cols-2"><div><h3 className="font-bold">Operational status</h3><select value={viewing.operational_status} disabled={busy} onChange={e=>action({action:"status",status:e.target.value})} className="input-field mt-2">{statuses.map(item=><option key={item}>{item}</option>)}</select><h3 className="mt-6 font-bold">Internal note</h3><textarea value={note} onChange={e=>setNote(e.target.value)} className="input-field mt-2" rows="3"/><button disabled={busy} onClick={()=>action({action:"note",note})} className="btn-secondary mt-2">Save note</button></div>
 <div><h3 className="font-bold">Record offline payment</h3><div className="mt-2 grid gap-2 sm:grid-cols-3"><input type="number" placeholder="Amount" value={manual.amount} onChange={e=>setManual({...manual,amount:e.target.value})} className="input-field"/><select value={manual.method} onChange={e=>setManual({...manual,method:e.target.value})} className="input-field"><option>bank_transfer</option><option>upi</option><option>cash</option><option>card_terminal</option></select><input placeholder="Reference" value={manual.reference} onChange={e=>setManual({...manual,reference:e.target.value})} className="input-field"/></div><button disabled={busy} onClick={()=>action({action:"manual_payment",...manual})} className="btn-primary mt-2">Record with audit trail</button></div></div>
 <section className="mt-8 rounded-2xl border p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-bold">DOCUMENTS</h3><p className="text-xs text-slate-500">Private, versioned PDF and editable Word documents.</p></div><label className="min-w-64 text-xs font-semibold">Customer email<input value={recipient} onChange={event=>setRecipient(event.target.value)} className="input-field mt-1" type="email"/></label></div>
 <div className="mt-4 grid gap-3">{[["hotel_voucher","Hotel Voucher"],["transport_voucher","Transport Voucher"],["itinerary","Itinerary"]].map(([type,label])=><div key={type} className="rounded-xl bg-navy-50 p-3"><div className="flex flex-wrap items-center gap-2"><strong className="mr-auto text-sm">{label}</strong>{type!=="itinerary"&&<details><summary className="btn-secondary cursor-pointer list-none">Generate / Edit</summary><div className="mt-3 grid gap-2 rounded-xl bg-white p-3 sm:grid-cols-2">{(type==="hotel_voucher"?[["hotelName","Hotel name"],["hotelAddress","Hotel address"],["roomType","Room type"],["checkInTime","Check-in time"],["checkOutTime","Check-out time"],["inclusions","Inclusions / policy"],["cancellationPolicy","Cancellation policy"],["checkInInstructions","Check-in instructions"]]:[["route","Route"],["vehicleType","Vehicle type"],["pickup","Pickup"],["drop","Drop"],["totalKm","Total KM"],["sightseeing","Sightseeing / add-ons"],["inclusions","Inclusions"],["exclusions","Exclusions"],["rules","Toll / parking / driver rules"]]).map(([field,placeholder])=><textarea key={field} rows="2" value={docDetails[type]?.[field]||""} onChange={event=>setDocDetails({...docDetails,[type]:{...docDetails[type],[field]:event.target.value}})} placeholder={placeholder} className="input-field"/>)}<button disabled={busy} onClick={saveDocumentDetails} className="btn-primary sm:col-span-2">Save document details</button></div></details>}<button onClick={()=>preview(type)} className="btn-secondary"><Eye size={14}/>Preview</button><button onClick={()=>downloadProtectedDocument(viewing.reference,type,"pdf","admin")} className="btn-secondary"><Download size={14}/>PDF</button><button onClick={()=>downloadProtectedDocument(viewing.reference,type,"docx","admin")} className="btn-secondary"><Download size={14}/>Word</button><button disabled={busy} onClick={()=>deliver("email",type)} className="btn-secondary"><Mail size={14}/>Email</button><button disabled={busy} onClick={()=>deliver("whatsapp",type)} className="btn-secondary"><MessageCircle size={14}/>WhatsApp</button></div></div>)}
 <div className="flex flex-wrap items-center gap-2 rounded-xl bg-orange-50 p-3"><strong className="mr-auto text-sm">Invoice</strong><a href={`/admin/invoices?booking=${viewing.id}`} className="btn-secondary">Create / Edit</a><span className="text-xs text-slate-500">Finalize the invoice before delivery.</span></div><button disabled={busy} onClick={()=>action({action:"resend",event:"booking_confirmed"})} className="btn-secondary justify-self-start"><Send size={14}/>Resend confirmation</button></div></section>
 <h3 className="mt-7 font-bold">Uploaded tickets and supplier documents</h3><div className="mt-2 grid gap-2">{(viewing.documents||[]).filter(item=>["hotel_voucher","transport_voucher","ticket","other"].includes(item.document_type)&&String(item.storage_path||"").includes("/uploads/")).map(item=>{const label=item.display_name||item.document_type.replaceAll("_"," ");return <div key={item.id} className="flex flex-wrap items-center gap-1"><span className="mr-auto text-sm font-semibold">{label}</span><button onClick={()=>previewStored(item)} className="btn-secondary"><Eye size={14}/>Preview</button><button onClick={()=>downloadStoredDocument(item.id,item.original_filename||label,"admin")} className="btn-secondary"><Download size={14}/>Download</button><button disabled={busy} onClick={()=>deliver("email",item.document_type,item.id)} className="btn-secondary"><Mail size={14}/>Email</button><button disabled={busy} onClick={()=>deliver("whatsapp",item.document_type,item.id)} className="btn-secondary"><MessageCircle size={14}/>WhatsApp</button></div>})}</div>
 <div className="mt-4 grid gap-2 sm:grid-cols-4"><select value={upload.type} onChange={e=>setUpload({...upload,type:e.target.value})} className="input-field"><option value="ticket">Ticket</option><option value="hotel_voucher">Hotel voucher</option><option value="transport_voucher">Transport voucher</option><option value="other">Other</option></select><input value={upload.name} onChange={e=>setUpload({...upload,name:e.target.value})} placeholder="Document name" className="input-field"/><input type="file" accept="application/pdf,.pdf" onChange={e=>setUpload({...upload,file:e.target.files?.[0]||null})} className="input-field sm:col-span-1"/><button disabled={busy||!upload.file} onClick={uploadDocument} className="btn-primary"><Upload size={14}/>Upload PDF</button></div>
 <h3 className="mt-8 font-bold">Travellers</h3><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><tbody>{viewing.travellers?.map(item=><tr key={item.id} className="border-b"><td className="p-3">{item.full_name}</td><td className="p-3">{item.traveller_type}</td><td className="p-3">{item.nationality}</td><td className="p-3">{item.special_requirements||"—"}</td></tr>)}</tbody></table></div></section></div>}
 </div>;
}
