import { useEffect, useMemo, useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { defaultHeaderMenuOptions, loadSiteSettings, saveSiteSettings } from "../../data/siteConfig";

const blank=()=>({id:crypto.randomUUID(),section:"tours",subgroup:"domestic",label:"",slug:"",target:"",displayOrder:"",published:true});
const slugify=value=>String(value||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export default function AdminMenuOptions(){
 const [settings,setSettings]=useState(null),[packages,setPackages]=useState([]),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([loadSiteSettings(),fetch("/api/admin/packages",{headers:{Authorization:`Bearer ${sessionStorage.getItem("naystrip_admin_session")}`}}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d})]).then(([s,p])=>{setSettings(s);setPackages(p.packages||[])}).catch(e=>setError(e.message))},[]);
 const used=useMemo(()=>new Set(packages.flatMap(item=>item.policies?.menuCategoryIds||[])),[packages]);
 const update=(id,field,value)=>setSettings(s=>({...s,headerMenuOptions:s.headerMenuOptions.map(item=>item.id===id?{...item,[field]:value,...(field==="label"&&!item.slug?{slug:slugify(value)}:{}),...(field==="slug"&&!item.target?{target:`/packages/${slugify(value)}`}:{})}:item)}));
 const remove=id=>{if(used.has(id)){setError("This option is assigned to a package. Reassign those packages before deleting it.");return}setSettings(s=>({...s,headerMenuOptions:s.headerMenuOptions.filter(item=>item.id!==id)}))};
 const save=async()=>{setBusy(true);setError("");try{await saveSiteSettings(settings);setMessage("Header menu options published.")}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!settings)return <p>{error||"Loading menu options…"}</p>;
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-2xl">Header Categories</h1><p className="mt-1 text-sm text-slate-500">Manage labels, placement, ordering and publication for the public header.</p></div><div className="flex gap-2"><button onClick={()=>setSettings({...settings,headerMenuOptions:[...settings.headerMenuOptions,blank()]})} className="btn-secondary"><Plus size={15}/>Add option</button><button disabled={busy} onClick={save} className="btn-primary"><Save size={15}/>{busy?"Saving…":"Publish"}</button></div></div>{error&&<p role="alert" className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{message&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<div className="mt-6 grid gap-3">{settings.headerMenuOptions.map(item=><article key={item.id} className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2 xl:grid-cols-8"><input aria-label="Label" value={item.label} onChange={e=>update(item.id,"label",e.target.value)} placeholder="Label" className="input-field xl:col-span-2"/><select aria-label="Menu" value={item.section} onChange={e=>update(item.id,"section",e.target.value)} className="input-field"><option value="tours">Tours</option><option value="treks">Treks & Expeditions</option><option value="weekends">Weekend Getaways</option><option value="services">Travel Services</option></select><select aria-label="Subgroup" value={item.subgroup||""} onChange={e=>update(item.id,"subgroup",e.target.value)} className="input-field"><option value="">No subgroup</option><option value="domestic">Domestic</option><option value="international">International</option><option value="sahyadri">Sahyadri</option><option value="himalaya">Himalaya</option></select><input aria-label="Slug" value={item.slug} onChange={e=>update(item.id,"slug",slugify(e.target.value))} placeholder="slug" className="input-field"/><input aria-label="Target" value={item.target||""} onChange={e=>update(item.id,"target",e.target.value)} placeholder="/packages/slug" className="input-field"/><input aria-label="Display order" type="number" value={item.displayOrder??""} onChange={e=>update(item.id,"displayOrder",e.target.value)} placeholder="Order" className="input-field"/><div className="flex items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={item.published!==false} onChange={e=>update(item.id,"published",e.target.checked)}/>Published</label><button onClick={()=>remove(item.id)} disabled={used.has(item.id)} title={used.has(item.id)?"Assigned to a package":"Delete"} className="text-rose-600 disabled:text-slate-300"><Trash2 size={16}/></button></div></article>)}</div>{!settings.headerMenuOptions.length&&<button onClick={()=>setSettings({...settings,headerMenuOptions:defaultHeaderMenuOptions})} className="btn-secondary mt-5">Restore defaults</button>}</div>
}
