import {useEffect,useMemo,useState} from "react";
import {Plus} from "lucide-react";

const token=()=>sessionStorage.getItem("naystrip_admin_session");
const request=async(path,options={})=>{const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json"}});const data=await response.json();if(!response.ok)throw new Error(data.error);return data};
const empty={packageId:"",startDate:"",endDate:"",capacity:12,bookedSeats:0,price:"",advanceAmount:"",bookingCutoff:"",status:"open",meetingPoint:"",internalNotes:""};
const emptyBulk={scheduleName:"",availableDates:"",blockedDates:"",capacity:12,price:"",bookingCutoff:"",packageType:"all",packageIds:[]};
const splitDates=value=>[...new Set(String(value||"").split(/[\s,]+/).map(item=>item.trim()).filter(Boolean))];

export default function AdminDepartures(){
 const [departures,setDepartures]=useState([]),[packages,setPackages]=useState([]),[form,setForm]=useState(empty),[bulk,setBulk]=useState(emptyBulk),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{try{const [d,p]=await Promise.all([request("/api/admin/departures"),request("/api/admin/packages")]);setDepartures(d.departures);setPackages(p.packages)}catch(err){setError(err.message)}};
 useEffect(()=>{load()},[]);
 const eligible=useMemo(()=>packages.filter(item=>item.package_type!=="service"&&item.status!=="archived"&&(bulk.packageType==="all"||item.package_type===bulk.packageType)),[packages,bulk.packageType]);
 const submit=async event=>{event.preventDefault();try{await request("/api/admin/departures",{method:form.id?"PATCH":"POST",body:JSON.stringify(form)});setForm(empty);await load()}catch(err){setError(err.message)}};
 const applyBulk=async event=>{event.preventDefault();setError("");try{const dates=[...splitDates(bulk.availableDates).map(startDate=>({startDate,status:"open"})),...splitDates(bulk.blockedDates).map(startDate=>({startDate,status:"closed"}))];const result=await request("/api/admin/departures",{method:"POST",body:JSON.stringify({...bulk,action:"bulk",dates})});setNotice(`${result.created} package dates created${result.skipped?`; ${result.skipped} existing overrides preserved`:""}.`);setBulk(emptyBulk);await load()}catch(err){setError(err.message)}};
 const togglePackage=id=>setBulk({...bulk,packageIds:bulk.packageIds.includes(id)?bulk.packageIds.filter(value=>value!==id):[...bulk.packageIds,id]});
 return <div><h1 className="font-display text-2xl">Availability & Departures</h1><p className="mt-1 text-sm text-navy-500">Create dates once for multiple packages; edit individual rows below for package-specific overrides.</p>{error&&<p className="mt-4 bg-rose-50 p-3 text-sm">{error}</p>}{notice&&<p role="status" className="mt-4 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
 <form onSubmit={applyBulk} className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50/40 p-6"><h2 className="font-display text-xl text-[#173c34]">Create reusable availability schedule</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label><span className="label-field">Schedule name</span><input required value={bulk.scheduleName} onChange={e=>setBulk({...bulk,scheduleName:e.target.value})} className="input-field" placeholder="October Weekend Dates"/></label><label><span className="label-field">Available dates</span><textarea required rows="4" value={bulk.availableDates} onChange={e=>setBulk({...bulk,availableDates:e.target.value})} className="input-field" placeholder="2026-10-03&#10;2026-10-10"/></label><label><span className="label-field">Blocked dates (optional)</span><textarea rows="4" value={bulk.blockedDates} onChange={e=>setBulk({...bulk,blockedDates:e.target.value})} className="input-field" placeholder="2026-10-17"/></label>{[["Capacity","capacity","number"],["Price override","price","number"],["Booking cutoff","bookingCutoff","datetime-local"]].map(([label,key,type])=><label key={key}><span className="label-field">{label}</span><input type={type} min={type==="number"?0:undefined} value={bulk[key]} onChange={e=>setBulk({...bulk,[key]:e.target.value})} className="input-field"/></label>)}</div><div className="mt-5 flex flex-wrap items-end gap-3"><label><span className="label-field">Package type/category</span><select value={bulk.packageType} onChange={e=>setBulk({...bulk,packageType:e.target.value,packageIds:[]})} className="input-field min-w-52"><option value="all">All package types</option>{[...new Set(packages.filter(item=>item.package_type!=="service").map(item=>item.package_type))].map(type=><option key={type} value={type}>{type}</option>)}</select></label><button type="button" className="btn-secondary" onClick={()=>setBulk({...bulk,packageIds:eligible.map(item=>item.id)})}>Select all shown</button><button type="button" className="text-sm font-bold" onClick={()=>setBulk({...bulk,packageIds:[]})}>Clear</button></div><fieldset className="mt-4"><legend className="label-field">Apply to packages ({bulk.packageIds.length} selected)</legend><div className="mt-2 grid max-h-56 gap-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{eligible.map(item=><label key={item.id} className="flex gap-2 rounded-xl bg-white p-3 text-sm"><input type="checkbox" checked={bulk.packageIds.includes(item.id)} onChange={()=>togglePackage(item.id)}/><span>{item.title}</span></label>)}</div></fieldset><button className="btn-primary mt-5" disabled={!bulk.packageIds.length}><Plus size={15}/>Apply schedule</button></form>
 <form onSubmit={submit} className="mt-6 rounded-2xl border bg-white p-6"><h2 className="font-display text-xl">Package-specific departure / override</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label><span className="label-field">Package</span><select required value={form.packageId} onChange={e=>setForm({...form,packageId:e.target.value})} className="input-field"><option value="">Select</option>{packages.filter(item=>item.package_type!=="service").map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label>{[["Start date","startDate","date"],["Return date","endDate","date"],["Capacity","capacity","number"],["Booked seats","bookedSeats","number"],["Price override","price","number"],["Advance amount","advanceAmount","number"],["Booking cutoff","bookingCutoff","datetime-local"]].map(([label,key,type])=><label key={key}><span className="label-field">{label}</span><input type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="input-field"/></label>)}<label><span className="label-field">Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="input-field">{["open","filling_fast","sold_out","closed","completed","cancelled"].map(item=><option key={item}>{item}</option>)}</select></label><label><span className="label-field">Meeting point</span><input value={form.meetingPoint} onChange={e=>setForm({...form,meetingPoint:e.target.value})} className="input-field"/></label></div><button className="btn-primary mt-5"><Plus size={15}/>{form.id?"Update":"Add departure"}</button></form>
 <div className="mt-7 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left"><th className="p-4">Package</th><th className="p-4">Dates</th><th className="p-4">Seats</th><th className="p-4">Price</th><th className="p-4">Status</th><th className="p-4">Edit</th></tr></thead><tbody>{departures.map(item=><tr key={item.id} className="border-b"><td className="p-4">{item.package?.title}</td><td className="p-4">{item.start_date} – {item.end_date}</td><td className="p-4">{item.booked_seats}/{item.capacity}</td><td className="p-4">{item.price_override?`INR ${Number(item.price_override).toLocaleString("en-IN")}`:"Package price"}</td><td className="p-4">{item.status}</td><td className="p-4"><button onClick={()=>setForm({id:item.id,packageId:item.package_id,startDate:item.start_date,endDate:item.end_date,capacity:item.capacity,bookedSeats:item.booked_seats,price:item.price_override||"",advanceAmount:item.advance_amount||"",bookingCutoff:item.booking_cutoff?.slice(0,16)||"",status:item.status,meetingPoint:item.meeting_point||"",internalNotes:item.internal_notes||""})} className="btn-secondary">Edit</button></td></tr>)}</tbody></table></div></div>;
}
